import {
  Badge,
  ChildProfile,
  HabitActivity,
  Reward,
  ActivityCategory,
  JourneyPlan,
} from '@/types';

export const DEFAULT_BADGES: Badge[] = [
  {
    id: 'badge-first-task',
    code: 'firstTask',
    icon: '🌱',
    name: {
      vi: 'Khởi đầu xanh',
      en: 'First Step',
      fr: 'Premier pas',
      de: 'Erster Schritt',
      it: 'Primo passo',
      es: 'Primer paso',
      zh: '初出茅庐',
      ja: 'はじめの一歩',
      ko: '첫 걸음',
    },
    description: {
      vi: 'Hoàn thành nhiệm vụ đầu tiên',
      en: 'Complete your very first task',
      fr: 'Accomplis ta toute première mission',
      de: 'Schließe deine allererste Aufgabe ab',
      it: 'Completa la tua prima missione',
      es: 'Completa tu primera misión',
      zh: '完成你的第一个任务',
      ja: '最初のミッションをクリア',
      ko: '첫 번째 미션을 완료하세요',
    },
    criteriaType: 'firstTask',
    criteriaValue: 1,
  },
  {
    id: 'badge-streak-3',
    code: 'streak',
    icon: '🔥',
    name: {
      vi: 'Ngọn lửa 3 ngày',
      en: '3-Day Fire',
      fr: 'Flamme de 3 jours',
      de: '3-Tage-Flamme',
      it: 'Fiamma di 3 giorni',
      es: 'Llama de 3 días',
      zh: '3天火热连击',
      ja: '3日連続ファイヤー',
      ko: '3일 연속 불꽃',
    },
    description: {
      vi: 'Duy trì thói quen 3 ngày liên tục',
      en: 'Keep a 3-day completion streak',
      fr: 'Tiens une série de 3 jours',
      de: 'Halte eine 3-Tage-Serie',
      it: 'Mantieni una serie di 3 giorni',
      es: 'Mantén una racha de 3 días',
      zh: '连续3天完成习惯打卡',
      ja: '3日連続でミッションを達成',
      ko: '3일 연속으로 미션을 달성하세요',
    },
    criteriaType: 'streak',
    criteriaValue: 3,
  },
  {
    id: 'badge-streak-7',
    code: 'streak',
    icon: '⚡',
    name: {
      vi: 'Chiến binh 7 ngày',
      en: '7-Day Warrior',
      fr: 'Héros de 7 jours',
      de: '7-Tage-Held',
      it: 'Eroe di 7 giorni',
      es: 'Héroe de 7 días',
      zh: '7天习惯大师',
      ja: '7日連続マスター',
      ko: '7일 연속 마스터',
    },
    description: {
      vi: 'Duy trì thói quen 7 ngày liên tục',
      en: 'Keep a 7-day completion streak',
      fr: 'Tiens une série de 7 jours',
      de: 'Halte eine 7-Tage-Serie',
      it: 'Mantieni una serie di 7 giorni',
      es: 'Mantén una racha de 7 días',
      zh: '连续7天坚持好习惯',
      ja: '1週間まいにち達成！',
      ko: '일주일 동안 매일 실천했어요',
    },
    criteriaType: 'streak',
    criteriaValue: 7,
  },
  {
    id: 'badge-tasks-20',
    code: 'totalTasks',
    icon: '🏆',
    name: {
      vi: 'Siêu nhân việc tốt',
      en: 'Task Champion',
      fr: 'Champion des missions',
      de: 'Aufgaben-Champion',
      it: 'Campione delle missioni',
      es: 'Campeón de misiones',
      zh: '任务达人',
      ja: 'ミッションチャンピオン',
      ko: '미션 챔피언',
    },
    description: {
      vi: 'Hoàn thành tổng cộng 20 nhiệm vụ',
      en: 'Complete 20 total tasks',
      fr: 'Accomplis 20 missions au total',
      de: 'Schließe insgesamt 20 Aufgaben ab',
      it: 'Completa 20 missioni in totale',
      es: 'Completa 20 misiones en total',
      zh: '累计完成20项任务',
      ja: '合計20個のミッション達成',
      ko: '총 20개의 미션을 완료했어요',
    },
    criteriaType: 'totalTasks',
    criteriaValue: 20,
  },
  {
    id: 'badge-points-100',
    code: 'totalPoints',
    icon: '🌟',
    name: {
      vi: 'Vương miện 100 sao',
      en: '100 Stars Crown',
      fr: 'Couronne des 100 étoiles',
      de: '100-Sterne-Krone',
      it: 'Corona delle 100 stelle',
      es: 'Corona de 100 estrellas',
      zh: '百星闪耀',
      ja: '100スタークラウン',
      ko: '100별 왕관',
    },
    description: {
      vi: 'Tích lũy tổng cộng 100 sao',
      en: 'Earn a total of 100 stars',
      fr: 'Gagne 100 étoiles au total',
      de: 'Sammle insgesamt 100 Sterne',
      it: 'Guadagna 100 stelle in totale',
      es: 'Gana 100 estrellas en total',
      zh: '累计获得100颗星星',
      ja: '合計100スターを獲得',
      ko: '총 100개의 별을 모았어요',
    },
    criteriaType: 'totalPoints',
    criteriaValue: 100,
  },
];

export const INITIAL_PROFILES: ChildProfile[] = [
  {
    id: 'child-1',
    name: 'Nguyễn Minh An',
    nickname: 'Bé An (Leo) 🦁',
    showRealNameOnLeaderboard: false,
    isPublicOnLeaderboard: true,
    avatar: '🦁',
    themeColor: '#3b82f6',
    points: 85,
    totalEarned: 145,
    level: 2,
    streak: 4,
    age: 8,
    birthYear: 2018,
    ageStage: '6-12',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'child-2',
    name: 'Nguyễn Mai Chi',
    nickname: 'Bé Mai (Bunny) 🐰',
    showRealNameOnLeaderboard: false,
    isPublicOnLeaderboard: true,
    avatar: '🐰',
    themeColor: '#ec4899',
    points: 45,
    totalEarned: 65,
    level: 1,
    streak: 2,
    age: 4,
    birthYear: 2022,
    ageStage: '3-6',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'child-3',
    name: 'Bé Đậu Nhỏ',
    nickname: 'Bé Đậu (Baby) 👶',
    showRealNameOnLeaderboard: false,
    isPublicOnLeaderboard: true,
    avatar: '👶',
    themeColor: '#06b6d4',
    points: 35,
    totalEarned: 50,
    level: 1,
    streak: 3,
    age: 1,
    birthYear: 2025,
    ageStage: '0-3',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_ACTIVITIES: HabitActivity[] = [
  {
    id: 'act-1',
    childId: null,
    title: 'Nhan thí: Tươi cười chào buổi sáng',
    description: 'Nở nụ cười rạng rỡ và khoanh tay chào ông bà, bố mẹ khi ngủ dậy',
    icon: '😊',
    category: 'giving',
    points: 10,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'morning',
    durationMinutes: 0,
    requiresApproval: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-2',
    childId: null,
    title: 'Đánh răng sáng & tối đúng 2 phút',
    description: 'Chăm sóc hàm răng trắng tinh và khỏe mạnh',
    icon: '🪥',
    category: 'health',
    points: 10,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'morning',
    durationMinutes: 2,
    requiresApproval: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-3',
    childId: null,
    title: 'Văn hóa bàn ăn: Mời cơm & ngồi ăn không màn hình',
    description: 'Mời cả nhà ăn cơm, tập trung ăn ngon miệng, không xem điện thoại hay TV',
    icon: '🍚',
    category: 'nutrition',
    points: 15,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'afternoon',
    durationMinutes: 0,
    requiresApproval: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-4',
    childId: null,
    title: 'Sức học tập & Bài học tâm đắc hôm nay',
    description: 'Hoàn thành bài tập và chia sẻ với bố mẹ 1 điều hay bé học được trong ngày',
    icon: '💡',
    category: 'wisdom',
    points: 25,
    recurrenceType: 'weekdays',
    recurrenceDays: [1, 2, 3, 4, 5],
    timeOfDay: 'afternoon',
    durationMinutes: 30,
    requiresApproval: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-5',
    childId: null,
    title: 'Thân thí: Tự bưng bát đĩa & dọn đồ chơi',
    description: 'Chủ động cất bát đĩa vào bồn và lau dọn góc học tập ngăn nắp',
    icon: '🥣',
    category: 'capacity',
    points: 15,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'evening',
    durationMinutes: 0,
    requiresApproval: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-6',
    childId: null,
    title: 'Phẩm chất Tín: Chuẩn bị sách vở & ngủ trước 21h30',
    description: 'Giữ đúng lời hứa với bố mẹ, tự sắp xếp cặp sách và đi ngủ đúng giờ',
    icon: '🌙',
    category: 'virtue',
    points: 20,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'evening',
    durationMinutes: 0,
    requiresApproval: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-baby-1',
    childId: 'child-3',
    title: '[Thân giáo Ba Mẹ] Nụ cười rạng rỡ đón bé thức dậy',
    description: 'Bố mẹ luôn cười tươi rạng rỡ khi bế và trò chuyện cùng con buổi sáng (Nhan thí)',
    icon: '😊',
    category: 'giving',
    points: 15,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'morning',
    durationMinutes: 0,
    requiresApproval: false,
    isActive: true,
    targetAgeStage: '0-3',
    isParentRole: true,
    portrait16Key: 'vui_ve',
    boThi7Key: 'nhan',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-baby-2',
    childId: 'child-3',
    title: '[Thân giáo Ba Mẹ] Ôm ấp con & Nói lời yêu thương ấm áp',
    description: 'Ôm ấp vỗ về bé mỗi ngày, dùng giọng nói dịu dàng gọi tên con (Thân thí)',
    icon: '❤️',
    category: 'personality',
    points: 20,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'afternoon',
    durationMinutes: 5,
    requiresApproval: false,
    isActive: true,
    targetAgeStage: '0-3',
    isParentRole: true,
    portrait16Key: 'yeu_thuong',
    boThi7Key: 'than',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-baby-3',
    childId: 'child-3',
    title: '[Thân giáo Ba Mẹ] Mỉm cười bao dung khi bé làm đổ sữa/nước',
    description: 'Bố mẹ giữ tâm thái an vui, không dán nhãn, nhẹ nhàng dọn dẹp và làm mẫu cho con (Phòng thí)',
    icon: '🕊️',
    category: 'mindset',
    points: 20,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'afternoon',
    durationMinutes: 0,
    requiresApproval: false,
    isActive: true,
    targetAgeStage: '0-3',
    isParentRole: true,
    portrait16Key: 'bao_dung',
    boThi7Key: 'phong',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'act-baby-4',
    childId: 'child-3',
    title: '[Thân giáo Ba Mẹ] Đọc sách tranh giọng truyền cảm trước giờ ngủ',
    description: 'Cùng bé lật xem tranh, gieo hạt giống ngôn từ ánh sáng và thói quen đọc sách (Trí tuệ)',
    icon: '📖',
    category: 'wisdom',
    points: 20,
    recurrenceType: 'daily',
    recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
    timeOfDay: 'evening',
    durationMinutes: 15,
    requiresApproval: false,
    isActive: true,
    targetAgeStage: '0-3',
    isParentRole: true,
    portrait16Key: 'tri_tue',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    title: 'Xem phim hoạt hình 30 phút',
    description: 'Được tự chọn 1 tập phim hoạt hình yêu thích',
    icon: '📺',
    costPoints: 30,
    stock: -1,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rew-2',
    title: 'Được chọn món ăn tối yêu thích',
    description: 'Gia đình cùng ăn món bé thích nhất (pizza, gà rán, canh sườn...)',
    icon: '🍕',
    costPoints: 60,
    stock: -1,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rew-3',
    title: 'Mua 1 cuốn truyện tranh mới',
    description: 'Bố mẹ dẫn đi nhà sách chọn 1 cuốn sách/truyện yêu thích',
    icon: '📕',
    costPoints: 120,
    stock: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rew-4',
    title: 'Chuyến đi chơi công viên cuối tuần',
    description: 'Cả nhà cùng đi chơi công viên nước hoặc khu vui chơi',
    icon: '🎡',
    costPoints: 200,
    stock: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_GROUPS: import('@/types').GroupTeam[] = [
  {
    id: 'grp-1',
    name: 'Biệt Đội Siêu Anh Hùng Nhỏ',
    inviteCode: 'HERO01',
    icon: '🚀',
    memberChildIds: ['child-1', 'child-2', 'mock-global-1', 'mock-global-2'],
    weeklyTargetPoints: 300,
    rewardType: 'badge',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'grp-2',
    name: 'Vườn Sao Yêu Thương',
    inviteCode: 'STAR88',
    icon: '⭐',
    memberChildIds: ['child-1', 'mock-global-3'],
    weeklyTargetPoints: 250,
    rewardType: 'stars',
    createdAt: new Date().toISOString(),
  },
];

export interface HabitTemplate {
  title: string;
  category: ActivityCategory;
  points: number;
  icon: string;
  timeOfDay: 'morning' | 'afternoon' | 'evening' | 'anytime';
  durationMinutes?: number;
  requiresApproval?: boolean;
  pack:
    | 'mindset'
    | 'virtue'
    | 'personality'
    | 'giving'
    | 'wisdom'
    | 'capacity'
    | 'physical'
    | 'nutrition';
  description?: string;
}

export const WIT_HABIT_PACKS: {
  key: HabitTemplate['pack'];
  titleKey: string;
  icon: string;
  color: string;
  items: HabitTemplate[];
}[] = [
  // 1. THÓI QUEN ĂN UỐNG LÀNH MẠNH & BÀN ĂN (NEW)
  {
    key: 'nutrition',
    titleKey: 'witPackNutrition',
    icon: '🍱',
    color: 'from-emerald-500 to-green-600',
    items: [
      {
        title: 'Rửa sạch hai tay bằng xà phòng trước khi vào bàn ăn',
        category: 'nutrition',
        pack: 'nutrition',
        points: 10,
        icon: '🧼',
        timeOfDay: 'afternoon',
        durationMinutes: 1,
        description: 'Vệ sinh bàn tay sạch khuẩn để ăn ngon và bảo vệ đường tiêu hóa khỏe mạnh',
      },
      {
        title: 'Phẩm chất Lễ: Khoanh tay mời cả nhà trước khi ăn cơm',
        category: 'nutrition',
        pack: 'nutrition',
        points: 15,
        icon: '🥢',
        timeOfDay: 'afternoon',
        description: 'Lễ phép mời ông bà, bố mẹ và anh chị em cùng dùng bữa',
      },
      {
        title: 'Văn hóa bàn ăn: Ngồi ngay ngắn, không xem điện thoại / TV',
        category: 'nutrition',
        pack: 'nutrition',
        points: 20,
        icon: '📵',
        timeOfDay: 'evening',
        description: 'Tập trung nhai kỹ, cảm nhận vị ngon món ăn và trò chuyện vui vẻ cùng gia đình',
      },
      {
        title: 'Tự xúc ăn gọn gàng, không để rơi vãi thức ăn ra bàn',
        category: 'nutrition',
        pack: 'nutrition',
        points: 15,
        icon: '🍚',
        timeOfDay: 'afternoon',
        description: 'Giữ bàn ăn sạch sẽ, không bốc tay hay vung vãi cơm thức ăn',
      },
      {
        title: 'Ăn đa dạng các món & vui vẻ ăn hết phần rau xanh',
        category: 'nutrition',
        pack: 'nutrition',
        points: 20,
        icon: '🥦',
        timeOfDay: 'evening',
        description: 'Không kén ăn, bổ sung nhiều vitamin và chất xơ từ rau củ tươi ngon',
      },
      {
        title: 'Nhai kỹ no lâu, không ngậm thức ăn trong miệng',
        category: 'nutrition',
        pack: 'nutrition',
        points: 15,
        icon: '😋',
        timeOfDay: 'afternoon',
        description: 'Nhai đều đặn, nuốt nhẹ nhàng, ăn xong bữa đúng giờ không quá 30 phút',
      },
      {
        title: 'Thân thí: Tự bưng bát đĩa cất vào bồn rửa sau khi ăn',
        category: 'nutrition',
        pack: 'nutrition',
        points: 15,
        icon: '🥣',
        timeOfDay: 'evening',
        description: 'Chủ động dọn phần ăn của mình, rèn luyện tính tự lập và phụ giúp mẹ',
      },
      {
        title: 'Lấy khăn sạch lau bàn ăn giúp mẹ sau bữa cơm',
        category: 'nutrition',
        pack: 'nutrition',
        points: 15,
        icon: '🧽',
        timeOfDay: 'evening',
        description: 'Lau sạch bề mặt bàn ăn, để lại không gian sạch bong cho cả gia đình',
      },
      {
        title: 'Uống đủ nước ấm sau bữa ăn, không uống nước ngọt có ga',
        category: 'nutrition',
        pack: 'nutrition',
        points: 10,
        icon: '💧',
        timeOfDay: 'afternoon',
        description: 'Chọn nước lọc hoặc nước ấm thanh lọc cơ thể thay vì nước có đường',
      },
    ],
  },

  // 2. 7 BỐ THÍ ĐỜI NGƯỜI
  {
    key: 'giving',
    titleKey: 'witPackGiving',
    icon: '🎁',
    color: 'from-pink-500 to-rose-500',
    items: [
      {
        title: 'Nhan thí: Nở nụ cười chào đón người thân',
        category: 'giving',
        pack: 'giving',
        points: 10,
        icon: '😊',
        timeOfDay: 'morning',
        description: 'Bố thí nụ cười tươi tắn mỗi sáng gặp ông bà, bố mẹ và thầy cô',
      },
      {
        title: 'Nhãn thí: Ánh mắt trìu mến & nhìn nhận điểm tốt của bạn',
        category: 'giving',
        pack: 'giving',
        points: 15,
        icon: '👀',
        timeOfDay: 'anytime',
        description: 'Bố thí ánh mắt chứa đựng sự công nhận và yêu thương dành cho mọi người',
      },
      {
        title: 'Ngôn thí: Nói lời ái ngữ, khích lệ & khen ngợi',
        category: 'giving',
        pack: 'giving',
        points: 15,
        icon: '🗣️',
        timeOfDay: 'anytime',
        description: 'Dùng lời nói mang lại niềm tin, hy vọng, khen ngợi và động viên bạn bè',
      },
      {
        title: 'Tâm thí: Trân trọng biết ơn người khác giúp mình',
        category: 'giving',
        pack: 'giving',
        points: 15,
        icon: '💖',
        timeOfDay: 'evening',
        description: 'Bày tỏ lòng biết ơn chân thành trước bữa ăn và sự chăm sóc của gia đình',
      },
      {
        title: 'Phòng thí: Bao dung & tha thứ khi bạn vô ý làm phiền',
        category: 'giving',
        pack: 'giving',
        points: 20,
        icon: '🕊️',
        timeOfDay: 'anytime',
        description: 'Không giận dỗi, vui vẻ tha thứ và thông cảm khi bạn lỡ làm hỏng việc',
      },
      {
        title: 'Thân thí: Tận tay giúp đỡ xách đồ, dọn dẹp',
        category: 'giving',
        pack: 'giving',
        points: 15,
        icon: '🤝',
        timeOfDay: 'evening',
        description: 'Hành động thực tế hỗ trợ bố mẹ xách túi đồ, cất ghế, phụ việc nhà',
      },
      {
        title: 'Tọa thí: Nhường chỗ & chia sẻ kinh nghiệm cho em',
        category: 'giving',
        pack: 'giving',
        points: 20,
        icon: '🪑',
        timeOfDay: 'anytime',
        description: 'Nhường đồ chơi cho em hoặc hướng dẫn bạn làm một việc bé đã biết làm',
      },
    ],
  },

  // 3. PHẨM CHẤT ƯU TÚ
  {
    key: 'virtue',
    titleKey: 'witPackVirtue',
    icon: '💎',
    color: 'from-amber-500 to-yellow-500',
    items: [
      {
        title: 'Phẩm chất Nhân: Yêu thương & chia sẻ món ngon',
        category: 'virtue',
        pack: 'virtue',
        points: 15,
        icon: '❤️',
        timeOfDay: 'afternoon',
        description: 'Nuôi dưỡng lòng trắc ẩn, biết chia sẻ đồ ăn, đồ chơi với người khác',
      },
      {
        title: 'Phẩm chất Lễ: Lễ phép chào hỏi & cảm ơn, xin lỗi',
        category: 'virtue',
        pack: 'virtue',
        points: 15,
        icon: '🙇',
        timeOfDay: 'morning',
        description: 'Đi thưa về trình, khoanh tay chào người lớn và nói năng dạ vâng',
      },
      {
        title: 'Phẩm chất Nghĩa: Có trách nhiệm với việc được giao',
        category: 'virtue',
        pack: 'virtue',
        points: 20,
        icon: '⚖️',
        timeOfDay: 'evening',
        description: 'Ý thức trách nhiệm hoàn thành nhiệm vụ và tri ân những điều nhận được',
      },
      {
        title: 'Phẩm chất Trí: Đặt câu hỏi hay & tìm hiểu điều mới',
        category: 'virtue',
        pack: 'virtue',
        points: 20,
        icon: '🧠',
        timeOfDay: 'afternoon',
        durationMinutes: 15,
        description: 'Lắng nghe sáng suốt, tìm tòi nguyên lý hoạt động của thế giới xung quanh',
      },
      {
        title: 'Phẩm chất Tín: Giữ đúng lời hứa & đúng giờ hẹn',
        category: 'virtue',
        pack: 'virtue',
        points: 25,
        icon: '⏳',
        timeOfDay: 'evening',
        description: 'Làm đúng những gì đã hứa với bố mẹ và bạn bè, luôn đúng giờ',
      },
    ],
  },

  // 4. TÂM THÁI
  {
    key: 'mindset',
    titleKey: 'witPackMindset',
    icon: '☀️',
    color: 'from-indigo-500 to-blue-500',
    items: [
      {
        title: 'Tâm thái An vui: Mỉm cười bắt đầu ngày mới',
        category: 'mindset',
        pack: 'mindset',
        points: 15,
        icon: '🌈',
        timeOfDay: 'morning',
        description: 'Giữ tâm trạng bình an, không cáu gắt hay mè nheo buổi sáng',
      },
      {
        title: 'Tâm thái Bao dung: Tôn trọng sự khác biệt của bạn',
        category: 'mindset',
        pack: 'mindset',
        points: 20,
        icon: '🌿',
        timeOfDay: 'anytime',
        description: 'Chấp nhận và tôn trọng sở thích riêng của bạn bè, không chê bai',
      },
      {
        title: 'Trân trọng biết ơn: Viết/Nói 3 điều biết ơn mỗi ngày',
        category: 'mindset',
        pack: 'mindset',
        points: 20,
        icon: '📝',
        timeOfDay: 'evening',
        description: 'Trước khi đi ngủ, kể cho bố mẹ nghe 3 điều bé cảm thấy biết ơn hôm nay',
      },
    ],
  },

  // 5. KIỆN TOÀN NHÂN CÁCH
  {
    key: 'personality',
    titleKey: 'witPackPersonality',
    icon: '👑',
    color: 'from-purple-500 to-indigo-500',
    items: [
      {
        title: 'Nhân cách Vui vẻ: Mang lại tiếng cười cho gia đình',
        category: 'personality',
        pack: 'personality',
        points: 15,
        icon: '😄',
        timeOfDay: 'evening',
        description: 'Kể chuyện cười, hát vui vẻ hoặc hỏi thăm để bố mẹ vui sau giờ làm',
      },
      {
        title: 'Nhân cách Khiêm tốn: Lắng nghe không ngắt lời',
        category: 'personality',
        pack: 'personality',
        points: 15,
        icon: '👂',
        timeOfDay: 'anytime',
        description: 'Biết ghi nhận thành tích của người khác và khiêm tốn học hỏi',
      },
      {
        title: 'Nhân cách Chân thật: Trung thực nhận lỗi khi làm sai',
        category: 'personality',
        pack: 'personality',
        points: 25,
        icon: '🛡️',
        timeOfDay: 'anytime',
        requiresApproval: true,
        description: 'Dũng cảm nói thật, nhận lỗi chân thành và sẵn sàng sửa đổi',
      },
      {
        title: 'Nhân cách Hy vọng & Niềm tin: Động viên bạn bè vượt khó',
        category: 'personality',
        pack: 'personality',
        points: 20,
        icon: '🌟',
        timeOfDay: 'afternoon',
        description: 'Truyền niềm tin và nói lời khích lệ khi thấy người khác gặp khó khăn',
      },
    ],
  },

  // 6. TRÍ TUỆ & SỨC HỌC TẬP
  {
    key: 'wisdom',
    titleKey: 'witPackWisdom',
    icon: '📖',
    color: 'from-emerald-500 to-teal-500',
    items: [
      {
        title: 'Sức học tập: Đọc sách nuôi dưỡng tâm hồn 15 phút',
        category: 'wisdom',
        pack: 'wisdom',
        points: 20,
        icon: '📚',
        timeOfDay: 'afternoon',
        durationMinutes: 15,
        description: 'Đọc truyện tranh đạo đức, sách khoa học hoặc sách phát triển tư duy',
      },
      {
        title: 'Bài học tâm đắc: Chia sẻ 1 điều ngộ ra trong ngày',
        category: 'wisdom',
        pack: 'wisdom',
        points: 20,
        icon: '💡',
        timeOfDay: 'evening',
        description: 'Đúc kết bài học hay từ câu chuyện ở lớp, ở nhà hoặc sách vở',
      },
      {
        title: 'Chủ động hoàn thành bài tập về nhà không cần nhắc',
        category: 'wisdom',
        pack: 'wisdom',
        points: 25,
        icon: '✍️',
        timeOfDay: 'afternoon',
        durationMinutes: 30,
        requiresApproval: true,
        description: 'Tự giác ngồi vào bàn học tập trung và hoàn thành nhiệm vụ',
      },
    ],
  },

  // 7. NĂNG LỰC & TỐ CHẤT NHÂN TÀI
  {
    key: 'capacity',
    titleKey: 'witPackCapacity',
    icon: '⚡',
    color: 'from-cyan-500 to-blue-600',
    items: [
      {
        title: 'Gánh vác: Tự gấp chăn màn & sắp xếp giường',
        category: 'capacity',
        pack: 'capacity',
        points: 15,
        icon: '🛏️',
        timeOfDay: 'morning',
        description: 'Gánh vác trách nhiệm giữ gìn không gian sống ngăn nắp sạch đẹp',
      },
      {
        title: 'Kiên trì: Luyện tập nhạc cụ / vẽ tranh / viết chữ',
        category: 'capacity',
        pack: 'capacity',
        points: 20,
        icon: '🎨',
        timeOfDay: 'afternoon',
        durationMinutes: 20,
        description: 'Rèn luyện tính kiên nhẫn, không bỏ cuộc giữa chừng',
      },
      {
        title: 'Dũng cảm thay đổi: Từ bỏ 1 thói quen chưa tốt',
        category: 'capacity',
        pack: 'capacity',
        points: 30,
        icon: '🚀',
        timeOfDay: 'evening',
        requiresApproval: true,
        description: 'Tự giác hạn chế xem tivi, bớt mè nheo, kiên quyết thay đổi vì sự tiến bộ',
      },
    ],
  },

  // 8. THỂ CHẤT & SỨC KHỎE
  {
    key: 'physical',
    titleKey: 'physical',
    icon: '🏃',
    color: 'from-orange-500 to-amber-600',
    items: [
      {
        title: 'Vận động thể thao / Thể dục buổi sáng 15 phút',
        category: 'physical',
        pack: 'physical',
        points: 15,
        icon: '🏃',
        timeOfDay: 'morning',
        durationMinutes: 15,
        description: 'Tập thể dục, hít thở không khí trong lành, tăng cường sức bền',
      },
      {
        title: 'Đánh răng sáng & tối đúng 2 phút',
        category: 'physical',
        pack: 'physical',
        points: 10,
        icon: '🪥',
        timeOfDay: 'morning',
        durationMinutes: 2,
        description: 'Chăm sóc răng miệng sạch sẽ',
      },
    ],
  },
];

export const HABIT_TEMPLATES = WIT_HABIT_PACKS.flatMap((pack) => pack.items);

// ==========================================
// ROADMAP & JOURNEY PLANS (BY WEEK & BY MONTH)
// ==========================================
export const WEEKLY_JOURNEY_PLANS: JourneyPlan[] = [
  {
    id: 'week-1',
    type: 'weekly',
    periodLabel: 'Tuần 1',
    icon: '🌸',
    themeColor: '#3b82f6',
    title: {
      vi: 'Tuần 1: Nếp Sống Vui Vẻ & Lễ Phép',
      en: 'Week 1: Joyful & Polite Living',
      zh: '第一周：欢喜与礼貌素养',
      ja: '第1週：笑顔とあいさつの基本',
      ko: '1주차: 밝은 미소와 예의바른 생활',
    },
    description: {
      vi: 'Khởi động với nụ cười, lời chào hỏi, khoanh tay mời cơm và đi ngủ đúng giờ.',
      en: 'Kickstart with morning smiles, polite greetings, table invitations, and timely sleep.',
      zh: '以微笑、问候、餐前请饭与按时就寝开启好习惯之旅。',
      ja: '朝の笑顔、あいさつ、食事のあいさつ、早寝からスタート。',
      ko: '아침 미소, 인사, 식사 인사, 규칙적인 취침으로 시작합니다.',
    },
    habits: [
      {
        title: 'Nhan thí: Nở nụ cười chào đón người thân',
        description: 'Tươi cười khoanh tay chào ông bà, bố mẹ mỗi sáng',
        icon: '😊',
        category: 'giving',
        points: 10,
        timeOfDay: 'morning',
      },
      {
        title: 'Đánh răng sáng & tối đúng 2 phút',
        description: 'Vệ sinh răng miệng sạch thơm trước khi đi học',
        icon: '🪥',
        category: 'health',
        points: 10,
        timeOfDay: 'morning',
        durationMinutes: 2,
      },
      {
        title: 'Khoanh tay mời cả nhà trước khi ăn cơm',
        description: 'Lễ phép mời ông bà, bố mẹ cùng dùng bữa',
        icon: '🥢',
        category: 'nutrition',
        points: 15,
        timeOfDay: 'afternoon',
      },
      {
        title: 'Ngủ đúng giờ trước 21h30',
        description: 'Giữ đúng lời hứa, ngủ sớm để ngày mai khỏe khoắn',
        icon: '🌙',
        category: 'virtue',
        points: 15,
        timeOfDay: 'evening',
      },
    ],
  },
  {
    id: 'week-2',
    type: 'weekly',
    periodLabel: 'Tuần 2',
    icon: '🍱',
    themeColor: '#10b981',
    title: {
      vi: 'Tuần 2: Văn Hóa Bàn Ăn & Tự Lập Vệ Sinh',
      en: 'Week 2: Table Manners & Hygiene Independence',
      zh: '第二周：文明餐桌与独立卫生',
      ja: '第2週：食事マナーと衛生の自立',
      ko: '2주차: 식사 예절과 청결한 위생 자립',
    },
    description: {
      vi: 'Rửa tay trước khi ăn, ăn cơm không màn hình điện thoại, tự xúc ăn gọn và ăn rau.',
      en: 'Wash hands, screen-free meals, tidy self-feeding, and eating colorful veggies.',
      zh: '餐前洗手、就餐远离屏幕、自主进餐不掉屑、吃完蔬菜。',
      ja: '手洗い、食事中スマホ見ない、こぼさず食べる、野菜を食べる。',
      ko: '식전 손 씻기, 식사 중 화면 안 보기, 스스로 깔끔하게 먹기, 채소 먹기.',
    },
    habits: [
      {
        title: 'Rửa sạch hai tay bằng xà phòng trước khi ăn',
        description: 'Vệ sinh sạch khuẩn trước bữa ăn',
        icon: '🧼',
        category: 'nutrition',
        points: 10,
        timeOfDay: 'afternoon',
        durationMinutes: 1,
      },
      {
        title: 'Ngồi ăn ngay ngắn, không xem điện thoại / TV',
        description: 'Tập trung vào món ăn và trò chuyện với gia đình',
        icon: '📵',
        category: 'nutrition',
        points: 20,
        timeOfDay: 'afternoon',
      },
      {
        title: 'Tự xúc ăn gọn gàng & ăn hết phần rau xanh',
        description: 'Không kén ăn, giữ bàn ăn sạch sẽ',
        icon: '🥦',
        category: 'nutrition',
        points: 20,
        timeOfDay: 'evening',
      },
      {
        title: 'Tự bưng bát đĩa cất vào bồn rửa sau khi ăn',
        description: 'Tự lập dọn dẹp sau bữa ăn',
        icon: '🥣',
        category: 'nutrition',
        points: 15,
        timeOfDay: 'evening',
      },
    ],
  },
  {
    id: 'week-3',
    type: 'weekly',
    periodLabel: 'Tuần 3',
    icon: '🏡',
    themeColor: '#f59e0b',
    title: {
      vi: 'Tuần 3: Trân Trọng Biết Ơn & Gánh Vác Việc Nhà',
      en: 'Week 3: Gratitude & Household Contribution',
      zh: '第三周：知恩感恩与承担家务',
      ja: '第3週：感謝とお手伝いの実践',
      ko: '3주차: 감사하는 마음과 집안일 분담',
    },
    description: {
      vi: 'Nói lời biết ơn, tự gấp chăn màn, cất dọn đồ chơi và phụ mẹ lau bàn.',
      en: 'Speak words of thanks, make own bed, tidy up toys, and help wipe the table.',
      zh: '表达感恩之心、自己叠被子、整理玩具、帮妈妈擦桌子。',
      ja: 'ありがとうを言う、布団をたたむ、おもちゃを片付ける、机を拭く。',
      ko: '감사 표현하기, 스스로 이불 개기, 장난감 정리, 식탁 닦기 돕기.',
    },
    habits: [
      {
        title: 'Tự gấp chăn màn & sắp xếp giường ngăn nắp',
        description: 'Gánh vác giữ gìn phòng ngủ sạch đẹp',
        icon: '🛏️',
        category: 'capacity',
        points: 15,
        timeOfDay: 'morning',
      },
      {
        title: 'Cất đồ chơi vào giỏ gọn gàng sau khi chơi',
        description: 'Không để đồ chơi bừa bãi',
        icon: '🧸',
        category: 'capacity',
        points: 15,
        timeOfDay: 'evening',
      },
      {
        title: 'Lau sạch bàn ăn giúp mẹ sau bữa cơm',
        description: 'Phụ giúp mẹ giữ nhà cửa tinh tươm',
        icon: '🧽',
        category: 'nutrition',
        points: 15,
        timeOfDay: 'evening',
      },
      {
        title: 'Nói 3 điều biết ơn trước khi đi ngủ',
        description: 'Ghi nhận những điều tốt đẹp nhận được trong ngày',
        icon: '💖',
        category: 'mindset',
        points: 20,
        timeOfDay: 'evening',
      },
    ],
  },
  {
    id: 'week-4',
    type: 'weekly',
    periodLabel: 'Tuần 4',
    icon: '🧠',
    themeColor: '#8b5cf6',
    title: {
      vi: 'Tuần 4: Sức Học Tập & Trí Tuệ Sáng Suốt',
      en: 'Week 4: Learning Drive & Bright Wisdom',
      zh: '第四周：勤学力行与智慧启迪',
      ja: '第4週：学びの力と気づきの深まり',
      ko: '4주차: 배움의 즐거움과 지혜로운 성장',
    },
    description: {
      vi: 'Đọc sách 15 phút, ngộ ra bài học tâm đắc, tự giác làm bài tập và kiên trì rèn luyện.',
      en: 'Read 15 minutes, share key daily lesson, do homework independently, practice persistently.',
      zh: '阅读15分钟、分享每日感悟、自主完成作业、坚持不懈。',
      ja: '15分読書、今日学んだことを話す、自主的に宿題、諦めず練習。',
      ko: '15분 독서, 오늘의 깨달음 나누기, 스스로 숙제하기, 끈기 있게 실천.',
    },
    habits: [
      {
        title: 'Đọc sách nuôi dưỡng tâm hồn 15 phút',
        description: 'Đọc sách bổ ích mở rộng hiểu biết',
        icon: '📚',
        category: 'wisdom',
        points: 20,
        timeOfDay: 'afternoon',
        durationMinutes: 15,
      },
      {
        title: 'Chủ động hoàn thành bài tập về nhà',
        description: 'Tự giác học bài không đợi nhắc nhở',
        icon: '✍️',
        category: 'wisdom',
        points: 25,
        timeOfDay: 'afternoon',
        durationMinutes: 30,
        requiresApproval: true,
      },
      {
        title: 'Chia sẻ 1 bài học ngộ ra tâm đắc trong ngày',
        description: 'Đúc kết bài học hay kể cho bố mẹ nghe',
        icon: '💡',
        category: 'wisdom',
        points: 20,
        timeOfDay: 'evening',
      },
      {
        title: 'Kiên trì luyện tập nhạc cụ / vẽ tranh 20 phút',
        description: 'Không nản chí, làm đến cùng',
        icon: '🎨',
        category: 'capacity',
        points: 20,
        timeOfDay: 'afternoon',
        durationMinutes: 20,
      },
    ],
  },
];

export const MONTHLY_JOURNEY_PLANS: JourneyPlan[] = [
  {
    id: 'month-1',
    type: 'monthly',
    periodLabel: 'Tháng 1',
    icon: '🌱',
    themeColor: '#0ea5e9',
    title: {
      vi: 'Tháng 1: Khởi Động Tự Lập & Nề Nếp Bàn Ăn',
      en: 'Month 1: Independence & Dining Etiquette',
      zh: '第一月：生活自立与文明进餐',
      ja: '1ヶ月目：自立の芽生えと食事のしつけ',
      ko: '1개월차: 생활 자립과 올바른 식사 습관',
    },
    description: {
      vi: 'Tập trung rèn luyện các thói quen sinh hoạt cơ bản: vệ sinh, ăn uống lành mạnh, dọn giường và ngủ đúng giờ.',
      en: 'Focus on fundamental living habits: personal hygiene, healthy eating, bed tidying, and sleep rhythm.',
      zh: '专注于日常生活基础习惯：个人卫生、健康膳食、整理床铺与健康作息。',
      ja: '基本の生活習慣に集中：衛生、健康的な食事、ベッドメイキング、規則正しい睡眠。',
      ko: '기본 생활 습관 다지기: 위생, 건강한 식습관, 이불 정리, 바른 수면 리듬.',
    },
    habits: [
      {
        title: 'Đánh răng sáng & tối đúng 2 phút',
        description: 'Răng sạch thơm mát',
        icon: '🪥',
        category: 'health',
        points: 10,
        timeOfDay: 'morning',
        durationMinutes: 2,
      },
      {
        title: 'Tự gấp chăn màn ngăn nắp',
        description: 'Gấp chăn gối sau khi ngủ dậy',
        icon: '🛏️',
        category: 'capacity',
        points: 10,
        timeOfDay: 'morning',
      },
      {
        title: 'Rửa tay bằng xà phòng & khoanh tay mời cơm',
        description: 'Văn hóa lễ phép trên bàn ăn',
        icon: '🥢',
        category: 'nutrition',
        points: 15,
        timeOfDay: 'afternoon',
      },
      {
        title: 'Ăn cơm không màn hình điện thoại & ăn hết rau',
        description: 'Bảo vệ dạ dày và mắt sáng',
        icon: '🥦',
        category: 'nutrition',
        points: 20,
        timeOfDay: 'afternoon',
      },
      {
        title: 'Tự bưng bát đĩa cất vào bồn rửa',
        description: 'Rèn luyện tính tự phục vụ',
        icon: '🥣',
        category: 'nutrition',
        points: 15,
        timeOfDay: 'evening',
      },
      {
        title: 'Đi ngủ đúng giờ trước 21h30',
        description: 'Đảm bảo sức khỏe phát triển chiều cao',
        icon: '🌙',
        category: 'virtue',
        points: 20,
        timeOfDay: 'evening',
      },
    ],
  },
  {
    id: 'month-2',
    type: 'monthly',
    periodLabel: 'Tháng 2',
    icon: '☀️',
    themeColor: '#ec4899',
    title: {
      vi: 'Tháng 2: Bồi Dưỡng Tâm Thái & 7 Bố Thí Đời Người',
      en: 'Month 2: Mindset & 7 Life Gifts',
      zh: '第二月：涵养心态与生命七布施',
      ja: '2ヶ月目：豊かな心構えと7つの施し',
      ko: '2개월차: 평온한 마음가짐과 7가지 보시 실천',
    },
    description: {
      vi: 'Lan tỏa niềm vui bằng nụ cười, ánh mắt, lời khen ngợi, sự bao dung và tấm lòng biết ơn mỗi ngày.',
      en: 'Radiate positivity with smiles, warm eyes, praise, tolerance, and daily gratitude.',
      zh: '通过微笑、温和眼神、赞美、包容与感恩的心传递正能量。',
      ja: '笑顔、優しい目、励まし、思いやり、感謝で家庭を明るく。',
      ko: '미소, 따뜻한 눈빛, 칭찬, 배려, 감사하는 마음으로 긍정의 힘 나누기.',
    },
    habits: [
      {
        title: 'Nhan thí: Nở nụ cười chào đón người thân',
        description: 'Mỉm cười bắt đầu ngày mới',
        icon: '😊',
        category: 'giving',
        points: 10,
        timeOfDay: 'morning',
      },
      {
        title: 'Ngôn thí: Nói lời khích lệ & cảm ơn',
        description: 'Dùng lời ái ngữ mang lại niềm tin',
        icon: '🗣️',
        category: 'giving',
        points: 15,
        timeOfDay: 'anytime',
      },
      {
        title: 'Phòng thí: Bao dung & tha thứ khi bạn làm sai',
        description: 'Không giận dỗi, vui vẻ hòa đồng',
        icon: '🕊️',
        category: 'giving',
        points: 20,
        timeOfDay: 'anytime',
      },
      {
        title: 'Thân thí: Tận tay giúp đỡ bố mẹ việc nhà',
        description: 'Hành động thực tế phụ giúp gia đình',
        icon: '🤝',
        category: 'giving',
        points: 15,
        timeOfDay: 'evening',
      },
      {
        title: 'Tâm thí: Nói 3 điều trân trọng biết ơn mỗi tối',
        description: 'Nuôi dưỡng hạt mầm biết ơn',
        icon: '💖',
        category: 'mindset',
        points: 20,
        timeOfDay: 'evening',
      },
    ],
  },
  {
    id: 'month-3',
    type: 'monthly',
    periodLabel: 'Tháng 3',
    icon: '💎',
    themeColor: '#f59e0b',
    title: {
      vi: 'Tháng 3: Kiện Toàn 5 Phẩm Chất Ưu Tú',
      en: 'Month 3: Fostering 5 Core Virtues',
      zh: '第三月：健全五大核心品行',
      ja: '3ヶ月目：5つの徳（仁・礼・義・智・信）',
      ko: '3개월차: 5대 핵심 품성 기르기 (인·예·의·지·신)',
    },
    description: {
      vi: 'Rèn giũa Nhân (yêu thương), Lễ (lễ phép), Nghĩa (trách nhiệm), Trí (sáng suốt), Tín (uy tín đúng giờ).',
      en: 'Cultivate Benevolence (Love), Propriety (Respect), Righteousness (Responsibility), Wisdom, and Trustworthiness.',
      zh: '涵养仁爱、礼貌、担当、智慧探索与守时守信。',
      ja: '仁（愛）、礼（礼儀）、義（責任）、智（知恵）、信（約束・時間）を磨く。',
      ko: '사랑(인), 예의(예), 책임감(의), 지혜(지), 신뢰와 시간 약속(신) 실천하기.',
    },
    habits: [
      {
        title: 'Phẩm chất Lễ: Đi thưa về trình, dạ vâng',
        description: 'Lễ phép với người lớn',
        icon: '🙇',
        category: 'virtue',
        points: 15,
        timeOfDay: 'morning',
      },
      {
        title: 'Phẩm chất Nhân: Yêu thương & sẻ chia đồ ăn ngon',
        description: 'Biết nghĩ cho người khác',
        icon: '❤️',
        category: 'virtue',
        points: 15,
        timeOfDay: 'afternoon',
      },
      {
        title: 'Phẩm chất Trí: Đặt câu hỏi hay & tìm hiểu điều mới',
        description: 'Tìm tòi sáng tạo khoa học',
        icon: '🧠',
        category: 'virtue',
        points: 20,
        timeOfDay: 'afternoon',
        durationMinutes: 15,
      },
      {
        title: 'Phẩm chất Nghĩa: Trách nhiệm với việc được giao',
        description: 'Làm việc nghiêm túc, không bỏ dở',
        icon: '⚖️',
        category: 'virtue',
        points: 20,
        timeOfDay: 'evening',
      },
      {
        title: 'Phẩm chất Tín: Giữ đúng lời hứa & giờ giấc',
        description: 'Uy tín từ những việc nhỏ nhất',
        icon: '⏳',
        category: 'virtue',
        points: 25,
        timeOfDay: 'evening',
      },
    ],
  },
  {
    id: 'month-4',
    type: 'monthly',
    periodLabel: 'Tháng 4',
    icon: '🚀',
    themeColor: '#8b5cf6',
    title: {
      vi: 'Tháng 4: Khai Mở Trí Tuệ & Tố Chất Nhân Tài',
      en: 'Month 4: Expanding Wisdom & Talent Traits',
      zh: '第四月：开启大智慧与杰出英才特质',
      ja: '4ヶ月目：知恵の開花と才能の飛躍',
      ko: '4개월차: 지혜의 확장과 인재 자질 완성',
    },
    description: {
      vi: 'Sức học tập tự giác, ngộ bài học tâm đắc, dũng cảm nhận lỗi và kiên trì bền bỉ.',
      en: 'Autonomous learning drive, daily insights, courage to admit mistakes, and unrelenting perseverance.',
      zh: '自主学习力、每日顿悟收获、勇于承认错误、坚韧不拔。',
      ja: '自主学習、気づき、過ちを認める勇気、粘り強い継続力。',
      ko: '스스로 공부하기, 일상의 깨달음, 용기 있는 반성, 끈기 있는 도전.',
    },
    habits: [
      {
        title: 'Đọc sách nuôi dưỡng tâm hồn 20 phút',
        description: 'Mở rộng chân trời tri thức',
        icon: '📚',
        category: 'wisdom',
        points: 20,
        timeOfDay: 'afternoon',
        durationMinutes: 20,
      },
      {
        title: 'Chủ động hoàn thành bài tập về nhà',
        description: 'Tự giác không cần nhắc nhở',
        icon: '✍️',
        category: 'wisdom',
        points: 25,
        timeOfDay: 'afternoon',
        durationMinutes: 30,
        requiresApproval: true,
      },
      {
        title: 'Bài học tâm đắc: Chia sẻ 1 điều ngộ ra',
        description: 'Đúc kết bài học trưởng thành mỗi ngày',
        icon: '💡',
        category: 'wisdom',
        points: 20,
        timeOfDay: 'evening',
      },
      {
        title: 'Dũng cảm nhận lỗi & sửa đổi chân thành',
        description: 'Trung thực và dũng cảm tiến bộ',
        icon: '🛡️',
        category: 'personality',
        points: 25,
        timeOfDay: 'anytime',
        requiresApproval: true,
      },
      {
        title: 'Dũng cảm thay đổi: Từ bỏ thói quen chưa tốt',
        description: 'Kiên quyết thay đổi để giỏi hơn',
        icon: '🚀',
        category: 'capacity',
        points: 30,
        timeOfDay: 'evening',
        requiresApproval: true,
      },
    ],
  },
];
