import { AgeStage, HabitActivity, ActivityCategory } from '@/types';

export interface Portrait16Item {
  id: string;
  name: string;
  category: 'personality' | 'virtue' | 'capacity' | 'vision';
  icon: string;
  summary: string;
  actionsByStage: {
    '0-3': string; // Cha mẹ làm gương (Thân giáo)
    '3-6': string; // Định hình thói quen & 7 Bố thí nhỏ
    '6-12': string; // Bồi dưỡng phẩm chất & gánh vác
    '12-18': string; // Luật sắt & kiến tạo ước mơ
  };
}

export interface GivingItem {
  id: string;
  code: 'nhan' | 'nhan_mat' | 'ngon' | 'tam' | 'phong' | 'than' | 'toa';
  name: string;
  subName: string;
  icon: string;
  meaning: string;
  dailyPractice: string;
}

export const SEVEN_GIVINGS: GivingItem[] = [
  {
    id: 'g-nhan',
    code: 'nhan',
    name: 'Nhan thí',
    subName: 'Bố thí nụ cười',
    icon: '😊',
    meaning: 'Luôn nở nụ cười an vui, tươi tắn và đón nhận người khác với tâm thái hân hoan.',
    dailyPractice: 'Cười tươi chào hỏi ông bà, ba mẹ mỗi sáng thức dậy và khi trở về nhà.',
  },
  {
    id: 'g-nhan-mat',
    code: 'nhan_mat',
    name: 'Nhãn thí',
    subName: 'Bố thí ánh mắt',
    icon: '👁️',
    meaning: 'Ánh mắt chứa đựng sự yêu thương, trân trọng, nhìn thấy điểm sáng và sự chuyển hóa tốt đẹp của con/người khác.',
    dailyPractice: 'Nhìn thẳng vào mắt khi trò chuyện, ghi nhận và khen ngợi sự tiến bộ của bạn bè.',
  },
  {
    id: 'g-ngon',
    code: 'ngon',
    name: 'Ngôn thí',
    subName: 'Bố thí lời nói',
    icon: '🗣️',
    meaning: 'Dùng lời ái ngữ mang lại hy vọng, niềm tin, sự khích lệ và khẳng định giá trị.',
    dailyPractice: 'Nói lời cảm ơn, động viên khi bạn gặp khó khăn, không nói lời chê bai tiêu cực.',
  },
  {
    id: 'g-tam',
    code: 'tam',
    name: 'Tâm thí',
    subName: 'Bố thí lòng biết ơn',
    icon: '💖',
    meaning: 'Nuôi dưỡng lòng trân trọng biết ơn sâu sắc đối với vạn vật, con người và những gì mình đang có.',
    dailyPractice: 'Nói lời cảm ơn trước bữa cơm, trân trọng đồ dùng học tập và công sức của cha mẹ.',
  },
  {
    id: 'g-phong',
    code: 'phong',
    name: 'Phòng thí',
    subName: 'Bố thí lòng bao dung',
    icon: '🕊️',
    meaning: 'Dung lượng trái tim rộng mở, không dán nhãn lỗi lầm, sẵn sàng tha thứ và thấu hiểu.',
    dailyPractice: 'Mỉm cười tha thứ khi bạn lỡ tay làm hỏng đồ, lắng nghe lý do thay vì tức giận.',
  },
  {
    id: 'g-than',
    code: 'than',
    name: 'Thân thí',
    subName: 'Bố thí hành động nhân ái',
    icon: '🤝',
    meaning: 'Hành động phụng sự, giúp đỡ và chăm sóc người khác bằng bàn tay và sức lực cụ thể.',
    dailyPractice: 'Ôm hôn cha mẹ trước khi ngủ, phụ mẹ dọn mâm cơm, tưới cây, giúp bạn mang cặp sách.',
  },
  {
    id: 'g-toa',
    code: 'toa',
    name: 'Tọa thí',
    subName: 'Bố thí vị trí & cơ hội',
    icon: '🪑',
    meaning: 'Nhường nhịn vị trí tốt, chia sẻ cơ hội, chuyển giao tri thức và nâng đỡ người khác cùng tiến bộ.',
    dailyPractice: 'Nhường ghế xe bus/chỗ ngồi cho người lớn, chia sẻ đồ chơi yêu thích cùng bạn.',
  },
];

export const PORTRAITS_16: Portrait16Item[] = [
  // 9 NHÂN CÁCH
  {
    id: 'vui_ve',
    name: 'Vui vẻ',
    category: 'personality',
    icon: '😄',
    summary: 'Nhan thí, nụ cười rạng rỡ, tạo không khí hưng phấn và tích cực cho gia đình.',
    actionsByStage: {
      '0-3': 'Cha mẹ luôn cười rạng rỡ khi đón con; hát nhạc vui tươi khi làm việc nhà; chào đón mọi thành viên bằng sự nồng nhiệt.',
      '3-6': 'Bé tập mỉm cười chào mọi người (Nhan thí); kể chuyện vui cho ông bà nghe; hát múa tạo không khí gia đình.',
      '6-12': 'Làm việc nhà với tinh thần vui vẻ; lan tỏa năng lượng tích cực trong lớp; kể câu chuyện hài hước trong bữa ăn.',
      '12-18': 'Truyền cảm hứng sống lạc quan cho bạn bè; quản trị cảm xúc an vui; giữ nụ cười bình thản trước áp lực thi cử.',
    },
  },
  {
    id: 'hy_vong',
    name: 'Hy vọng',
    category: 'personality',
    icon: '🌈',
    summary: 'Ngôn từ ánh sáng, hướng đến tương lai tốt đẹp và khích lệ vượt khó.',
    actionsByStage: {
      '0-3': 'Cha mẹ nói về tương lai tốt đẹp; dùng ngôn từ tích cực khi gặp khó khăn; cùng trẻ quan sát cây xanh lớn lên.',
      '3-6': 'Khích lệ khi bạn ngã; nói lời "Lần sau mình sẽ làm được"; vẽ tranh về ước mơ tương lai.',
      '6-12': 'Nuôi dưỡng ước mơ và mục tiêu; động viên bạn bè khi kết quả chưa tốt; tự tin đặt câu hỏi tích cực.',
      '12-18': 'Kiến tạo tầm nhìn vượt qua nghịch cảnh; lan tỏa niềm tin vào tương lai cho đội nhóm; lập kế hoạch phát triển.',
    },
  },
  {
    id: 'niem_tin',
    name: 'Niềm tin',
    category: 'personality',
    icon: '⭐',
    summary: 'Tin tưởng vào Nhân ánh sáng, nhất quán lời nói và hành động.',
    actionsByStage: {
      '0-3': 'Khẳng định "Con làm được" khi con tập đi; tin tưởng tuyệt đối vào tiềm năng của con; nhất quán lời nói việc làm.',
      '3-6': 'Giữ lời hứa trả lại đồ chơi; tin tưởng cha mẹ đón đúng giờ; tự tin biểu diễn một tiết mục nhỏ trước nhà.',
      '6-12': 'Tin tưởng vào đồng đội trong các dự án nhóm; tự tin nhận trách nhiệm mới; giữ chữ tín trong bài vở.',
      '12-18': 'Kiên định với lý tưởng sống cao đẹp; tin tưởng vào con đường mình chọn; xây dựng uy tín cá nhân vững chắc.',
    },
  },
  {
    id: 'biet_on',
    name: 'Trân trọng biết ơn',
    category: 'personality',
    icon: '🙏',
    summary: 'Tâm thí, trân quý từng hạt cơm, đồ dùng và mọi nhân duyên trong đời.',
    actionsByStage: {
      '0-3': 'Nói lời cảm ơn thức ăn trước mặt con; trân quý từng hạt cơm; chăm sóc đồ dùng trong nhà nâng niu.',
      '3-6': 'Nói lời cảm ơn sau mỗi bữa ăn (Ngôn thí); giúp mẹ lau bát đĩa cẩn thận; giữ gìn đồ chơi sạch sẽ.',
      '6-12': 'Ghi 3 điều biết ơn mỗi ngày vào sổ; biết ơn thầy cô qua việc chăm học; trân trọng công sức nấu nướng của mẹ.',
      '12-18': 'Tri ân cội nguồn và tổ tiên; trân trọng biết ơn mọi trải nghiệm (kể cả thất bại); phụng sự cộng đồng.',
    },
  },
  {
    id: 'yeu_thuong',
    name: 'Yêu thương',
    category: 'personality',
    icon: '❤️',
    summary: 'Thân thí, ôm ấp, quan tâm chăm sóc người thân và vạn vật xung quanh.',
    actionsByStage: {
      '0-3': 'Ôm ấp con mỗi ngày; chăm sóc người thân khi ốm; dùng giọng nói ấm áp, đầy yêu thương khi gọi tên con.',
      '3-6': 'Ôm hôn cha mẹ trước khi ngủ (Thân thí); tưới cây cùng cha; chăm sóc thú cưng/búp bê dụng tâm.',
      '6-12': 'Chủ động chăm sóc em nhỏ hoặc ông bà; nấu món ăn đơn giản cho cả nhà; giúp đỡ bạn gặp khó khăn.',
      '12-18': 'Yêu thương nhân loại và phụng sự xã hội; tham gia hoạt động thiện nguyện; bảo vệ môi trường sống.',
    },
  },
  {
    id: 'bao_dung',
    name: 'Bao dung',
    category: 'personality',
    icon: '🕊️',
    summary: 'Phòng thí, không dán nhãn lỗi lầm, tha thứ và mở rộng dung lượng trái tim.',
    actionsByStage: {
      '0-3': 'Mỉm cười khi con làm đổ nước; không dán nhãn con "ngoan" hay "hư"; nhẹ nhàng hướng dẫn lại thay vì trách phạt.',
      '3-6': 'Sẵn sàng cho bạn mượn đồ chơi; tha lỗi khi bạn lỡ tay; lắng nghe lý do bạn làm sai thay vì khóc lóc.',
      '6-12': 'Bao dung cho lỗi lầm của em nhỏ; tôn trọng sự khác biệt của bạn bè; giữ hòa khí trong các cuộc tranh luận.',
      '12-18': 'Bao dung cho chính thiếu sót bản thân; thấu hiểu và biết ơn sự nghiêm khắc của cha mẹ; hòa giải mâu thuẫn.',
    },
  },
  {
    id: 'khiem_ton',
    name: 'Khiêm tốn',
    category: 'personality',
    icon: '🌱',
    summary: 'Tọa thí, lắng nghe cầu thị, không kiêu căng, nhường nhịn và học hỏi người khác.',
    actionsByStage: {
      '0-3': 'Cha mẹ lắng nghe ý kiến bạn đời; chào hỏi lễ phép với người cao tuổi; sẵn sàng cầu thị học hỏi điều mới.',
      '3-6': 'Nhường chỗ ngồi cho người lớn (Tọa thí); lắng nghe hướng dẫn của cô giáo; không khoe khoang đồ mới.',
      '6-12': 'Khiêm tốn khi nhận lời khen ngợi; giúp đỡ bạn yếu hơn mà không tự cao; học hỏi từ những người giỏi hơn.',
      '12-18': 'Đạt thành tựu lớn trong thầm lặng; luôn biết ơn những người đồng hành; khiêm tốn học hỏi tri thức mới.',
    },
  },
  {
    id: 'chan_that',
    name: 'Chân thật',
    category: 'personality',
    icon: '💎',
    summary: 'Giữ đúng lời hứa, dũng cảm nhận lỗi, sống thật với giá trị nội tâm ánh sáng.',
    actionsByStage: {
      '0-3': 'Giữ đúng lời hứa với con dù việc nhỏ nhất; không nói dối để trẻ ăn hay ngủ; sống thật với cảm xúc văn minh.',
      '3-6': 'Dũng cảm thừa nhận khi làm hỏng đồ; không nói dối để được thưởng quà; trả lại đồ chơi nhặt được cho bạn.',
      '6-12': 'Luôn nói thật với cha mẹ; trung thực trong thi cử và học tập; dũng cảm bảo vệ sự thật.',
      '12-18': 'Xây dựng bản sắc cá nhân chân thật; kiên định với các giá trị đạo đức đã chọn; chịu trách nhiệm 100% quyết định.',
    },
  },
  {
    id: 'tri_tue',
    name: 'Trí tuệ',
    category: 'personality',
    icon: '🧠',
    summary: 'Đọc sách sâu sắc, đặt câu hỏi tại sao, khai mở nhận thức nội tâm.',
    actionsByStage: {
      '0-3': 'Cha mẹ đọc sách mỗi tối; giải quyết mâu thuẫn bình tĩnh; luôn đặt câu hỏi gợi mở "Tại sao?" với sự vật quanh con.',
      '3-6': 'Tập phân loại đồ dùng logic; biết gọi tên cảm xúc cá nhân; nghe và kể lại các mẩu chuyện tư duy.',
      '6-12': 'Đọc ít nhất 1 cuốn sách mỗi tuần; đặt câu hỏi phản biện sâu sắc; rèn luyện tư duy quan sát - phân tích - đúc kết.',
      '12-18': 'Thấu hiểu các quy luật và nguyên lý vận hành cuộc sống; tư duy triết học sâu sắc; tĩnh tâm và thiền định mỗi ngày.',
    },
  },

  // 5 PHẨM CHẤT
  {
    id: 'le',
    name: 'Lễ (Lễ phép & Lẽ phải)',
    category: 'virtue',
    icon: '🙇',
    summary: 'Đi thưa về gửi, tôn trọng chuẩn mực văn hóa ứng xử, bảo vệ lẽ phải.',
    actionsByStage: {
      '0-3': 'Đi thưa về gửi với ông bà; mặc trang phục chỉnh tề khi ra ngoài; cư xử lịch thiệp với người lạ.',
      '3-6': 'Khoanh tay chào người lớn; biết dùng lời ái ngữ "Dạ, vâng"; tuân thủ nội quy sân chơi cộng đồng.',
      '6-12': 'Luôn chào hỏi hàng xóm lễ phép; bảo vệ lẽ phải khi thấy sự bất công; tuân thủ nghiêm túc nội quy trường lớp.',
      '12-18': 'Xây dựng văn hóa ứng xử tinh tế; giao tiếp ngoại giao chuẩn mực; bảo vệ lẽ phải và công bằng xã hội.',
    },
  },
  {
    id: 'nghia',
    name: 'Nghĩa (Trách nhiệm & Gánh vác)',
    category: 'virtue',
    icon: '🛡️',
    summary: 'Tự giác việc nhà, gánh vác trách nhiệm gia đình và phụng sự xã hội.',
    actionsByStage: {
      '0-3': 'Cha mẹ tự giác hoàn thành việc nhà; chăm sóc thú cưng chu đáo; bảo vệ môi trường sống xung quanh.',
      '3-6': 'Tự dọn đồ chơi sau khi dùng; phụ mẹ gấp quần áo nhỏ; biết giữ gìn vệ sinh chung nơi công cộng.',
      '6-12': 'Chủ động rửa bát sau mỗi bữa ăn; gánh vác việc đổ rác; lau dọn phòng ngủ ngăn nắp; chăm sóc thú cưng.',
      '12-18': 'Gánh vác trách nhiệm kinh tế nhỏ (làm thêm/tiết kiệm); lãnh đạo các tổ chức thanh niên; tự giác học ngoại ngữ.',
    },
  },
  {
    id: 'tri',
    name: 'Trí (Sáng suốt & Tỉnh thức)',
    category: 'virtue',
    icon: '🔍',
    summary: 'Phân tích vấn đề logic, chọn lọc thông tin lành mạnh, kiểm soát cảm xúc sáng suốt.',
    actionsByStage: {
      '0-3': 'Phân tích vấn đề dựa trên logic; biết chọn lọc thông tin; luôn bình thản trước các sự cố nhỏ.',
      '3-6': 'Biết chọn lọc trò chơi lành mạnh; đặt câu hỏi để hiểu rõ sự việc; học cách quan sát thế giới tỉ mỉ.',
      '6-12': 'Học cách quản lý tiền mừng tuổi thông minh; biết phân biệt hành vi đúng/sai trên mạng; kiên trì giải bài toán khó.',
      '12-18': 'Quản trị cảm xúc cá nhân sáng suốt; quản trị rủi ro; đưa ra các quyết định chiến lược cho tương lai.',
    },
  },
  {
    id: 'tin',
    name: 'Tín (Đúng giờ & Giữ lời)',
    category: 'virtue',
    icon: '⏰',
    summary: 'Đúng giờ, giữ đúng cam kết, thiết lập luật sắt kỷ luật tự thân.',
    actionsByStage: {
      '0-3': 'Đi làm và về nhà đúng giờ; ngủ nghỉ theo lịch trình khoa học; hoàn thành các cam kết cá nhân.',
      '3-6': 'Thức dậy ngay khi chuông reo; hoàn thành bữa ăn trong 30 phút; đúng hẹn khi đi chơi cùng bạn.',
      '6-12': 'Chuẩn bị đồ dùng học tập từ tối hôm trước; đi ngủ và thức dậy đúng giờ quy định; hoàn thành bài tập đúng hạn.',
      '12-18': 'Thực hiện kỷ luật thép: Thể dục 30 phút sáng không nghỉ; luật sắt mạng xã hội < 1 giờ/ngày; giữ chữ tín tuyệt đối.',
    },
  },

  // 2 NĂNG LỰC & TẦM NHÌN
  {
    id: 'quang_ba',
    name: 'Quảng bá',
    category: 'capacity',
    icon: '📢',
    summary: 'Nhắc đến điểm tốt của người khác, lan tỏa giá trị tri thức và truyền cảm hứng.',
    actionsByStage: {
      '0-3': 'Nhắc đến điểm tốt của người khác trước mặt con; chia sẻ tri thức hay; giới thiệu những cuốn sách giá trị.',
      '3-6': 'Khen món ăn mẹ nấu với bạn bè; nói về điểm tốt của anh/chị; chia sẻ những điều hay học được ở trường.',
      '6-12': 'Quảng bá về truyền thống tốt đẹp của gia đình; khen ngợi thành tích người khác dụng tâm; giới thiệu sách hay.',
      '12-18': 'Quảng bá siêu phàm: Xây dựng thương hiệu cá nhân chân thật; lan tỏa giá trị sống đẹp; truyền cảm hứng cho đội nhóm.',
    },
  },
  {
    id: 'giao_tiep',
    name: 'Giao tiếp thông thái',
    category: 'capacity',
    icon: '💬',
    summary: 'Nhãn thí, lắng nghe thấu cảm không ngắt lời, thuyết trình tự tin và hòa giải.',
    actionsByStage: {
      '0-3': 'Lắng nghe con không ngắt lời; giao tiếp bằng ánh mắt chân thành (Nhãn thí); dùng lời ái ngữ với tất cả mọi người.',
      '3-6': 'Nhìn thẳng mắt khi nói chuyện; không ngắt lời người lớn; biết cách hỏi mượn đồ chơi lịch sự.',
      '6-12': 'Tập thuyết trình trước đám đông tự tin; lắng nghe thấu cảm khi bạn buồn; học cách hòa giải mâu thuẫn giữa bạn bè.',
      '12-18': 'Đàm phán và thuyết phục đỉnh cao; giao tiếp ái ngữ truyền cảm hứng; dẫn dắt và truyền lửa cho tập thể.',
    },
  },
  {
    id: 'tam_nhin',
    name: 'Tầm nhìn & Kiến tạo ước mơ',
    category: 'vision',
    icon: '🔭',
    summary: 'Bản đồ cuộc đời, xác lập mục tiêu 5-10 năm, kiên định sứ mệnh lớn lao.',
    actionsByStage: {
      '0-3': 'Cha mẹ lập kế hoạch gia đình rõ ràng; viết nhật ký ước mơ cho con; chia sẻ về những dự định lớn lao hào hứng.',
      '3-6': 'Vẽ tranh về nghề nghiệp tương lai; lập danh sách việc muốn làm trong tuần; cùng cha mẹ xem bản đồ ước mơ.',
      '6-12': 'Lập mục tiêu học tập và phát triển cá nhân mỗi kỳ; tìm hiểu về các tấm gương vĩ nhân; vẽ bản đồ ước mơ 1-3 năm.',
      '12-18': 'Tự lập Vision Board 5-10 năm; xác lập danh sách 100 điều muốn làm trước tuổi 30; kết nối Mentor và kiên định sứ mệnh.',
    },
  },
];

export const SIX_GOLD_WORDS = [
  { word: 'Đơn giản', meaning: 'Chia nhỏ mọi kỹ năng để trẻ dễ dàng nắm bắt và tự tin hành động.' },
  { word: 'Vui vẻ', meaning: 'Tạo môi trường tràn đầy hưng phấn, nơi sự học và rèn luyện là một đặc ân.' },
  { word: 'Tin tưởng', meaning: 'Niềm tin tuyệt đối vào Nhân ánh sáng sẵn có bên trong con, ngay cả khi biểu hiện bên ngoài chưa như ý.' },
  { word: 'Nhẹ nhàng', meaning: 'Tiếp cận thấu cảm, kiên nhẫn bồi dưỡng, không dùng áp lực hay cưỡng cầu.' },
  { word: 'Thường xuyên', meaning: 'Lặp đi lặp lại bền bỉ mỗi ngày để tạo thành rãnh sâu trong tiềm thức.' },
  { word: 'Dụng tâm', meaning: 'Đặt trọn trái tim chứa đựng hình ảnh thành công của trẻ; dụng tâm nhìn thấy điểm sáng nhỏ nhất.' },
];

export const PARENT_SELF_CHECKLIST = [
  'Đơn giản: Mình đã chia nhỏ yêu cầu để con thấy việc gánh vác là dễ dàng chưa?',
  'Vui vẻ: Bầu không khí tương tác hôm nay có tràn đầy tiếng cười và sự khích lệ không?',
  'Tin tưởng: Mình có đang chứa đựng hình ảnh thành công của con ngay cả khi con thất bại không?',
  'Nhẹ nhàng: Lời nói của mình hôm nay có mang tính xây dựng và đầy ái ngữ không?',
  'Dụng tâm & Thường xuyên: Mình đã thực sự đặt trái tim vào việc làm gương cho con mỗi ngày chưa?',
];

export function getStageFromAge(age: number): AgeStage {
  if (age <= 3) return '0-3';
  if (age <= 6) return '3-6';
  if (age <= 12) return '6-12';
  return '12-18';
}

export function getStageInfo(stage: AgeStage) {
  switch (stage) {
    case '0-3':
      return {
        id: '0-3' as AgeStage,
        name: 'Giai đoạn 0-3 tuổi',
        range: '0-3 tuổi',
        label: '0 - 3 Tuổi',
        title: 'Thấm Nhuần Môi Trường & Thân Giáo',
        subtitle: 'Ba Mẹ Làm Gương • Rõ Hình Trong Tâm Trí Con',
        icon: '👶',
        color: 'from-blue-500 to-cyan-500',
        badgeColor: 'bg-blue-100 text-blue-800 dark:bg-blue-950/60 dark:text-blue-300',
        summary: 'Trẻ ở độ tuổi này như máy ảnh, chụp lại mọi hành động của cha mẹ vào tiềm thức. Cha mẹ thắp sáng 16 ngọn đèn thân giáo để làm gương rõ hình cho con.',
        isParentDriven: true,
      };
    case '3-6':
      return {
        id: '3-6' as AgeStage,
        name: 'Giai đoạn 3-6 tuổi',
        range: '3-6 tuổi',
        label: '3 - 6 Tuổi',
        title: 'Định Hình Thói Quen & 7 Bố Thí Nhỏ',
        subtitle: 'Bé Tự Lập Sơ Khởi • Thực Hành 7 Bố Thí',
        icon: '🧒',
        color: 'from-emerald-500 to-teal-500',
        badgeColor: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-300',
        summary: 'Hướng dẫn trẻ thực hành 7 Bố thí (Nhan, Nhãn, Ngôn, Tâm, Phòng, Thân, Tọa) và những thói quen tự lập dễ thương đầu đời.',
        isParentDriven: false,
      };
    case '6-12':
      return {
        id: '6-12' as AgeStage,
        name: 'Giai đoạn 6-12 tuổi',
        range: '6-12 tuổi',
        label: '6 - 12 Tuổi',
        title: 'Bồi Dưỡng 5 Phẩm Chất & Gánh Vác Việc Nhà',
        subtitle: 'Nhân - Lễ - Nghĩa - Trí - Tín • Trách Nhiệm Gia Đình',
        icon: '👦',
        color: 'from-amber-500 to-orange-500',
        badgeColor: 'bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-300',
        summary: 'Bồi dưỡng 5 Phẩm chất ưu tú thông qua gánh vác việc nhà, chăm sóc người thân, rèn luyện tư duy học tập và phụng sự gia đình.',
        isParentDriven: false,
      };
    case '12-18':
      return {
        id: '12-18' as AgeStage,
        name: 'Giai đoạn 12-18 tuổi',
        range: '12-18 tuổi',
        label: '12 - 18 Tuổi',
        title: 'Luật Sắt Bản Thân & Kiến Tạo Ước Mơ',
        subtitle: 'Kỷ Luật Tự Thân • Tầm Nhìn & Lãnh Đạo Thông Thái',
        icon: '🧑',
        color: 'from-purple-500 to-indigo-600',
        badgeColor: 'bg-purple-100 text-purple-800 dark:bg-purple-950/60 dark:text-purple-300',
        summary: 'Xác lập kỷ luật thép (Luật sắt), bản đồ cuộc đời Vision Board 5-10 năm, rèn luyện bản lĩnh thủ lĩnh và tâm thái an vui đủ đầy.',
        isParentDriven: false,
      };
  }
}

/**
 * Generate starter habits specifically adapted for the child's age stage
 */
export function generateAgeAdaptedHabits(
  childId: string | null,
  stage: AgeStage
): Omit<HabitActivity, 'id' | 'createdAt'>[] {
  const now = new Date().toISOString();

  if (stage === '0-3') {
    // 0-3: Cha mẹ thân giáo (Ba mẹ làm gương rõ hình cho bé)
    return [
      {
        childId,
        title: '[Thân giáo Ba Mẹ] Nụ cười rạng rỡ chào đón con',
        description: 'Luôn mỉm cười tươi tắn khi thức dậy và đón con; hát nhạc vui tươi khi làm việc nhà để tạo bầu không khí ấm áp.',
        icon: '😊',
        category: 'giving',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'morning',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '0-3',
        isParentRole: true,
        portrait16Key: 'vui_ve',
        boThi7Key: 'nhan',
      },
      {
        childId,
        title: '[Thân giáo Ba Mẹ] Nói lời cảm ơn thức ăn trước mặt con',
        description: 'Bố mẹ thể hiện lòng trân trọng biết ơn từng hạt cơm, thức ăn và đồ dùng trong nhà nâng niu trước mắt bé.',
        icon: '🍚',
        category: 'mindset',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'afternoon',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '0-3',
        isParentRole: true,
        portrait16Key: 'biet_on',
        boThi7Key: 'tam',
      },
      {
        childId,
        title: '[Thân giáo Ba Mẹ] Ôm ấp con & nói lời yêu thương',
        description: 'Dành những cái ôm ấm áp mỗi ngày, gọi tên con bằng giọng nói trìu mến yêu thương để bé cảm nhận tình thân.',
        icon: '❤️',
        category: 'personality',
        points: 20,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'afternoon',
        durationMinutes: 5,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '0-3',
        isParentRole: true,
        portrait16Key: 'yeu_thuong',
        boThi7Key: 'than',
      },
      {
        childId,
        title: '[Thân giáo Ba Mẹ] Mỉm cười bao dung khi con làm đổ nước',
        description: 'Không dán nhãn con hư hay la mắng; mỉm cười nhẹ nhàng hướng dẫn lại cách cầm cốc để bé học trong an vui.',
        icon: '🕊️',
        category: 'mindset',
        points: 20,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'anytime',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '0-3',
        isParentRole: true,
        portrait16Key: 'bao_dung',
        boThi7Key: 'phong',
      },
      {
        childId,
        title: '[Thân giáo Ba Mẹ] Đọc sách cho con nghe trước giờ ngủ',
        description: 'Đọc những mẩu chuyện tranh giàu hình ảnh tích cực, gieo hạt giống tri thức và tình yêu sách vào tiềm thức bé.',
        icon: '📖',
        category: 'wisdom',
        points: 20,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'evening',
        durationMinutes: 15,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '0-3',
        isParentRole: true,
        portrait16Key: 'tri_tue',
      },
      {
        childId,
        title: '[Thân giáo Ba Mẹ] Ngủ nghỉ đúng giờ & Giữ đúng lời hứa',
        description: 'Cha mẹ gương mẫu đi ngủ đúng giờ, tuyệt đối không nói dối để dụ trẻ ăn ngủ; giữ đúng lời hứa dù việc nhỏ.',
        icon: '🌙',
        category: 'virtue',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'evening',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '0-3',
        isParentRole: true,
        portrait16Key: 'tin',
      },
    ];
  }

  if (stage === '3-6') {
    // 3-6: Định hình thói quen & 7 Bố thí nhỏ
    return [
      {
        childId,
        title: 'Nhan thí: Mỉm cười chào cả nhà buổi sáng',
        description: 'Nở nụ cười thật tươi và chào ông bà, cha mẹ ngay khi thức dậy.',
        icon: '😊',
        category: 'giving',
        points: 10,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'morning',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '3-6',
        portrait16Key: 'vui_ve',
        boThi7Key: 'nhan',
      },
      {
        childId,
        title: 'Tự đánh răng sáng & tối đúng 2 phút',
        description: 'Tự giác lấy bàn chải, chải răng sạch bóng theo nhịp đồng hồ.',
        icon: '🪥',
        category: 'health',
        points: 10,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'morning',
        durationMinutes: 2,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '3-6',
        portrait16Key: 'tin',
      },
      {
        childId,
        title: 'Lễ phép: Khoanh tay mời cơm & Nói lời cảm ơn (Ngôn thí)',
        description: 'Mời cả nhà cùng dùng bữa và nói lời cảm ơn mẹ đã nấu món ngon.',
        icon: '🥢',
        category: 'nutrition',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'afternoon',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '3-6',
        portrait16Key: 'le',
        boThi7Key: 'ngon',
      },
      {
        childId,
        title: 'Thân thí: Tự cất đồ chơi gọn gàng sau khi chơi',
        description: 'Không để đồ chơi vung vãi, tự giác bỏ đồ chơi vào giỏ ngăn nắp.',
        icon: '🧸',
        category: 'capacity',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'evening',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '3-6',
        portrait16Key: 'nghia',
        boThi7Key: 'than',
      },
      {
        childId,
        title: 'Tọa thí: Chia sẻ đồ chơi & Nhường bạn bè',
        description: 'Sẵn sàng cho bạn cùng chơi đồ chơi hoặc nhường chỗ ngồi cho em nhỏ.',
        icon: '🪑',
        category: 'personality',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'anytime',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '3-6',
        portrait16Key: 'khiem_ton',
        boThi7Key: 'toa',
      },
      {
        childId,
        title: 'Ôm hôn chúc ba mẹ ngủ ngon trước 21h',
        description: 'Dành cái ôm ấm áp chúc ba mẹ ngủ ngon và lên giường đúng giờ.',
        icon: '🌙',
        category: 'giving',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'evening',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '3-6',
        portrait16Key: 'yeu_thuong',
        boThi7Key: 'than',
      },
    ];
  }

  if (stage === '6-12') {
    // 6-12: 5 Phẩm chất & Gánh vác việc nhà
    return [
      {
        childId,
        title: 'Phẩm chất Tín: Thức dậy đúng giờ & Tự gấp chăn màn',
        description: 'Tự giác thức dậy ngay khi có chuông, gấp chăn gối phẳng phiu.',
        icon: '🛏️',
        category: 'virtue',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'morning',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '6-12',
        portrait16Key: 'tin',
      },
      {
        childId,
        title: 'Gánh vác Nghĩa: Rửa bát & Dọn sạch bàn ăn sau bữa cơm',
        description: 'Chủ động rửa chén đĩa sạch sẽ, lau bề mặt bàn ăn phụ giúp gia đình.',
        icon: '🥣',
        category: 'virtue',
        points: 20,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'afternoon',
        durationMinutes: 10,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '6-12',
        portrait16Key: 'nghia',
      },
      {
        childId,
        title: 'Trí tuệ: Đọc sách 20 phút & Viết 1 bài học tâm đắc',
        description: 'Đọc sách khoa học, văn học hoặc kỹ năng, ghi lại 1 điều sâu sắc vào sổ.',
        icon: '💡',
        category: 'wisdom',
        points: 25,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'afternoon',
        durationMinutes: 20,
        requiresApproval: true,
        isActive: true,
        targetAgeStage: '6-12',
        portrait16Key: 'tri_tue',
      },
      {
        childId,
        title: 'Tâm thí: Ghi 3 điều biết ơn trong ngày vào sổ',
        description: 'Biết ơn bữa ăn ngon, biết ơn bạn bè giúp đỡ hoặc biết ơn cơ thể khỏe mạnh.',
        icon: '📝',
        category: 'mindset',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'evening',
        durationMinutes: 5,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '6-12',
        portrait16Key: 'biet_on',
        boThi7Key: 'tam',
      },
      {
        childId,
        title: 'Gánh vác Nhân: Kèm em học bài hoặc Giúp đỡ bạn bè',
        description: 'Kiên nhẫn hướng dẫn em nhỏ giải toán hoặc giúp bạn cùng tiến bộ.',
        icon: '🤝',
        category: 'virtue',
        points: 20,
        recurrenceType: 'weekdays',
        recurrenceDays: [1, 2, 3, 4, 5],
        timeOfDay: 'afternoon',
        durationMinutes: 15,
        requiresApproval: true,
        isActive: true,
        targetAgeStage: '6-12',
        portrait16Key: 'yeu_thuong',
      },
      {
        childId,
        title: 'Tự chuẩn bị sách vở tối hôm trước & Ngủ trước 21h30',
        description: 'Sắp xếp thời khóa biểu ngăn nắp, kiểm tra dụng cụ học tập trước khi ngủ.',
        icon: '🎒',
        category: 'virtue',
        points: 15,
        recurrenceType: 'daily',
        recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
        timeOfDay: 'evening',
        durationMinutes: 0,
        requiresApproval: false,
        isActive: true,
        targetAgeStage: '6-12',
        portrait16Key: 'tin',
      },
    ];
  }

  // 12-18: Luật sắt bản thân & Kiến tạo ước mơ
  return [
    {
      childId,
      title: 'Luật sắt kỷ luật: Tập thể dục 30 phút buổi sáng không nghỉ',
      description: 'Chạy bộ, tập cardio hoặc yoga 30 phút rèn luyện thể chất và ý chí kiên định.',
      icon: '🏃',
      category: 'physical',
      points: 25,
      recurrenceType: 'daily',
      recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
      timeOfDay: 'morning',
      durationMinutes: 30,
      requiresApproval: false,
      isActive: true,
      targetAgeStage: '12-18',
      portrait16Key: 'tin',
    },
    {
      childId,
      title: 'Quản lý 100% thời gian cá nhân & Kế hoạch tuần',
      description: 'Tự lập lịch học tập, sinh hoạt, cam kết thực hiện đúng deadline không đợi nhắc.',
      icon: '📅',
      category: 'virtue',
      points: 20,
      recurrenceType: 'daily',
      recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
      timeOfDay: 'morning',
      durationMinutes: 0,
      requiresApproval: false,
      isActive: true,
      targetAgeStage: '12-18',
      portrait16Key: 'tri',
    },
    {
      childId,
      title: 'Luật sắt mạng xã hội: Giới hạn giải trí màn hình < 1h/ngày',
      description: 'Chủ động kiểm soát thời gian lướt TikTok/Facebook/Game, dành thời gian phát triển bản thân.',
      icon: '📵',
      category: 'virtue',
      points: 30,
      recurrenceType: 'daily',
      recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
      timeOfDay: 'evening',
      durationMinutes: 0,
      requiresApproval: false,
      isActive: true,
      targetAgeStage: '12-18',
      portrait16Key: 'tin',
    },
    {
      childId,
      title: 'Tầm nhìn & Sứ mệnh: Cập nhật Vision Board & Mục tiêu 5 năm',
      description: 'Rà soát danh sách 100 điều ước trước tuổi 30, nghiên cứu định hướng ngành nghề tương lai.',
      icon: '🔭',
      category: 'wisdom',
      points: 30,
      recurrenceType: 'custom',
      recurrenceDays: [0], // Chủ nhật hàng tuần
      timeOfDay: 'afternoon',
      durationMinutes: 20,
      requiresApproval: true,
      isActive: true,
      targetAgeStage: '12-18',
      portrait16Key: 'tam_nhin',
    },
    {
      childId,
      title: 'Tĩnh tâm & Thiền định 15 phút mỗi tối',
      description: 'Tĩnh lặng quan sát nội tâm, giữ tâm thái an vui và buông bỏ áp lực không cần thiết.',
      icon: '🧘',
      category: 'mindset',
      points: 20,
      recurrenceType: 'daily',
      recurrenceDays: [0, 1, 2, 3, 4, 5, 6],
      timeOfDay: 'evening',
      durationMinutes: 15,
      requiresApproval: false,
      isActive: true,
      targetAgeStage: '12-18',
      portrait16Key: 'tri_tue',
    },
    {
      childId,
      title: 'Quảng bá & Lãnh đạo: Lan tỏa giá trị sống đẹp cho đội nhóm',
      description: 'Chia sẻ bài viết tư duy tích cực, gắn kết bạn bè hoặc tham gia phụng sự cộng đồng.',
      icon: '📢',
      category: 'capacity',
      points: 25,
      recurrenceType: 'weekdays',
      recurrenceDays: [1, 3, 5],
      timeOfDay: 'afternoon',
      durationMinutes: 0,
      requiresApproval: true,
      isActive: true,
      targetAgeStage: '12-18',
      portrait16Key: 'quang_ba',
      boThi7Key: 'ngon',
    },
  ];
}
