import type { HelpTranslationTable } from './help-topic-id';
import type { HelpText } from './help-topics';

export const HELP_TOPICS_ES: HelpTranslationTable<HelpText> = {
  'today.card': { title: 'El día de tu hijo', text: 'Resumen de hoy: tareas completadas de las programadas, racha y lo que necesita tu ayuda. Si tienes varios niños, elige uno en la fila superior.' },
  'approvals.tasks': { title: 'Tareas pendientes de aprobación', text: 'Tareas que tu hijo marcó como hechas y configuraste como «requieren aprobación». Pulsa Aprobar para darle las estrellas; Rechazar no le da ninguna. Requiere tu PIN si lo configuraste.' },
  'approvals.rewards': { title: 'Solicitudes de recompensas', text: 'Recompensas que tu hijo ha solicitado; las estrellas se descontaron al solicitarlas. Apruébalas y entrégalas. Si las rechazas, las estrellas vuelven a su cuenta.' },
  'support.prompt': { title: '¿Cómo fue hoy?', text: 'Opcional. Indica si tu hijo hizo un hábito solo, con un recordatorio o contigo, para que la aplicación sepa cuándo reducir los recordatorios. No se usa para comparar niños.' },
  'progress.summary': { title: 'Progreso de los hábitos', text: 'Cada hábito con una señal está en una etapa: elegir la señal, crear la rutina, reducir el apoyo y consolidarla. Es una guía para acompañar, no una puntuación.' },
  'today.actions': { title: 'Tareas pendientes para ti', text: 'Una franja reúne todo lo que espera tu atención: tareas por aprobar, solicitudes de recompensas y sugerencias de ajuste. Toca un elemento para ir directamente a la acción correspondiente. Si no hay nada pendiente, la franja te lo indica.' },
  'progress.graduation': { title: 'Dar por consolidado un hábito', text: 'Cuando tu hijo realiza un hábito por su cuenta durante varias semanas, la aplicación puede sugerir darlo por consolidado: sale de la lista diaria y queda en «Lo que ya sé hacer», sin perder estrellas ni historial. La aplicación vuelve a preguntarte cada mes. Tú decides y puedes deshacerlo.' },
  'progress.supportTrend': { title: 'Apoyo semana a semana', text: 'Las barras muestran cada semana si tu hijo hizo la actividad por su cuenta, con un recordatorio o contigo. La aplicación solo indica que «el apoyo está disminuyendo» cuando hay datos de al menos tres semanas seguidas y aumenta claramente lo que hace por su cuenta. No se usa para comparar niños.' },
  'coach.weeklyChange': { title: 'Un cambio para probar esta semana', text: 'Se sugiere un solo cambio cada vez para probar durante 7 días: hacerlo más sencillo, cambiar la hora, hacerlo juntos, cambiar la señal o reducir los recordatorios. Al cabo de 7 días, la aplicación pregunta si ayudó. No vuelve a sugerir durante 30 días algo que no haya ayudado.' },
  'coach.weeklyFocus': { title: 'Objetivos de la semana', text: 'Marcas algunas tareas entre las que tu hijo puede elegir. Al comenzar la semana, elige una o dos como objetivo y ve su progreso de 7 días. Si tiene menos de 6 años, elegís juntos. Si no elige, se usan los hábitos que está practicando.' },
  'weekly.review': { title: 'Revisión semanal', text: 'Una vez por semana, cinco minutos juntos: una cosa que elogiar, otra que ajustar y decidir si ya conviene añadir un hábito.' },
  'stats.weekly': { title: 'Tendencia de 7 días', text: 'Cada barra muestra cuántas tareas completó la familia ese día. Un día sin tareas hechas aparece como una barra vacía.' },
  'stats.print': { title: 'Imprimir la semana', text: 'Imprime una tabla de hábitos para la nevera o un informe semanal del número de veces y de los puntos obtenidos. Usa el cuadro de impresión del navegador.' },
  'stats.journal': { title: 'Diario de una línea', text: 'Frases que tu hijo escribe sobre lo que quiere recordar cada día. Solo él y tú pueden leerlas; no se miden. Puedes exportarlas a CSV: mantén el archivo privado.' },
  'stats.share': { title: 'Compartir un hito', text: 'Previsualiza y confirma el mensaje. El mensaje predeterminado no incluye nombre, edad, foto ni tareas del niño.' },
  'stats.deleteFamily': { title: 'Eliminar los datos familiares', text: 'Solo puede hacerlo el propietario de la familia. Elimina para siempre perfiles, hábitos, progreso, recompensas y dispositivos vinculados; no se puede deshacer. Debes escribir DELETE FAMILY.' },

  'habits.inUse': { title: 'Tareas en uso', text: 'Tareas asignadas actualmente. Filtra por niño, consulta las completadas en los últimos 7 días, edita, elimina o define una señal.' },
  'habits.library': { title: 'Biblioteca', text: 'Hábitos preparados para añadir al calendario. En vietnamita usa el marco de 47 hábitos por etapa de edad; los demás idiomas usan colecciones de plantillas.' },
  'habits.programs': { title: 'Programas', text: 'Crea hábitos paso a paso para un niño: elige unos pocos, define señales y sigue la etapa. Solo está disponible en vietnamita.' },
  'habits.framework': { title: 'Marco de 47 hábitos', text: 'Elige una etapa y un área, y lee su significado y cómo acompañarlo antes de añadirlo. Los hábitos añadidos aquí son para toda la familia; cambia «Asignar a» para dárselo a un solo niño.' },
  'habits.handbook': { title: 'Manual de 16 perfiles', text: 'Manual sobre 16 perfiles, 7 formas de dar y el arte de predicar con el ejemplo. Puedes aplicar a un niño un conjunto de acciones según su edad.' },
  'habits.cue': { title: 'Señal «si… entonces…»', text: 'Une un hábito a algo familiar o a una hora fija, con las palabras de tu hijo, por ejemplo: «Después de lavarme los dientes, leo una página». Una señal clara facilita empezar.' },
  'habits.programStart': { title: 'Empezar un programa', text: 'Tres pasos: elige los hábitos iniciales (es mejor uno o dos), define una señal para cada uno y confirma. Elegir más de lo recomendado solo muestra una advertencia.' },
  'habits.form.points': { title: 'Estrellas de recompensa', text: 'Estrellas que gana tu hijo al completar la tarea. Si requiere aprobación, se añaden solo después de que la apruebes.' },
  'habits.form.recurrence': { title: 'Repetición', text: 'Días en que aparece la tarea: todos los días, entre semana, fines de semana o los días que elijas.' },
  'habits.form.time': { title: 'Momento del día', text: 'Mañana, tarde, noche o en cualquier momento. La pantalla de tu hijo agrupa las tareas según esta opción.' },
  'habits.form.duration': { title: 'Tiempo de cuenta atrás', text: 'Minutos del temporizador, por ejemplo, 2 minutos para lavarse los dientes. Deja 0 si no necesitas temporizador.' },
  'habits.form.approval': { title: 'Requiere aprobación de los padres', text: 'Al activarlo, marcarla como hecha no da estrellas hasta aprobarla. Úsalo para tareas que quieres comprobar.' },
  'habits.form.assign': { title: 'Asignar a', text: 'Elige a todos los niños o a uno. Una tarea compartida aparece para todos.' },

  'journeys.overview': { title: 'Rutas por edad', text: 'Cinco etapas por edad, tres pasos cada una y un hábito nuevo por paso. Las semanas son momentos para empezar a revisar, no fechas límite. Elige un niño y pulsa Aplicar para añadir los hábitos.' },

  'rewards.manage': { title: 'Catálogo de recompensas', text: 'Recompensas que creas para canjear con estrellas. Tu hijo solicita, tú apruebas y luego entregas. Prioriza el tiempo juntos y las experiencias sobre los objetos.' },
  'rewards.templates': { title: 'Ideas de recompensas', text: 'Recompensas de experiencias y materiales con un coste de estrellas sugerido. Añádelas al catálogo y adáptalas a tu familia.' },

  'children.profiles': { title: 'Perfiles de los niños', text: 'Un perfil por niño: nombre, apodo, edad, mascota y color. El número de niños que puedes añadir depende de tu plan.' },
  'children.age': { title: 'Edad del niño', text: 'La edad define la etapa (0–3, 3–6, 6–12, 12–18), las sugerencias de hábitos y el aspecto de la pantalla de tu hijo.' },
  'children.leaderboard': { title: 'Tabla de clasificación', text: 'Los perfiles nuevos son privados. Un niño aparece en la tabla pública solo si la familia activa el uso compartido en Ajustes y lo selecciona, usando un apodo.' },
  'children.ageTheme': { title: 'Aspecto según la edad', text: 'La pantalla de tu hijo se adapta a su edad. Puedes fijar un tramo de edad o conservar el aspecto anterior; tu elección tiene prioridad sobre la del niño.' },
  'children.pairing': { title: 'Código de conexión', text: 'Cada niño tiene un código fijo que abre solo su perfil. Escanea el QR o introduce el código en el dispositivo de tu hijo. Requiere tu PIN si lo configuraste.' },
  'children.regenerate': { title: 'Nuevo código', text: 'Crear un código nuevo hace que el anterior deje de funcionar. Hazlo solo si crees que el código se ha revelado. Requiere PIN.' },
  'children.adjustPoints': { title: 'Añadir o quitar estrellas', text: 'Añade (número positivo) o descuenta estrellas (número negativo) con un motivo breve. Requiere PIN. Sirve para reconocer cosas fuera de las tareas asignadas.' },
  'children.ageBundle': { title: 'Paquete inicial por edad', text: 'Carga seis tareas iniciales adecuadas para la edad de tu hijo con un toque. Después puedes editarlas o eliminarlas.' },

  'settings.devices': { title: 'Dispositivos de los niños', text: 'Dispositivos vinculados, su propietario y última conexión. Revoca el acceso si se pierde un dispositivo o deja de usarse (requiere PIN).' },
  'settings.pwa': { title: 'Instalar la aplicación', text: 'Añade KidHabit a la pantalla de inicio para abrirlo como una aplicación. En iPhone: Safari → Compartir → Añadir a pantalla de inicio.' },
  'settings.caregivers': { title: 'Cuidadores', text: 'Invita a abuelos o familiares a ver el progreso con un enlace de un solo uso que caduca a las 72 horas. Solo pueden consultar. Revoca la invitación cuando quieras.' },
  'settings.pause': { title: 'Pausa familiar', text: 'Cuando la familia necesite descansar, elige Pausar: se ocultan los avisos de progreso y las rachas, la racha no se rompe y no se pierden estrellas ni recompensas. Pulsa Reanudar cuando estés listo.' },
  'settings.account': { title: 'Datos del cliente', text: 'Nombre y teléfono para recibir ayuda con la cuenta y los pagos. Puedes activar o desactivar las ofertas cuando quieras.' },
  'settings.coupon': { title: 'Código regalo', text: 'Introduce un código regalo para añadir días de uso. Cada familia lo usa una vez; demasiados intentos incorrectos lo bloquean unos minutos.' },
  'settings.referralCode': { title: 'Código de referido', text: 'Si te recomendó un amigo, introduce el código de 8 caracteres para obtener un 10 % de descuento en tu primer plan anual. Solo mientras la familia sea nueva y no haya pagado.' },
  'settings.affiliate': { title: 'Recomendar a amigos', text: 'Comparte tu enlace para ganar una comisión del 30 % cuando pague una familia nueva. La comisión se retiene 35 días; el retiro mínimo es de 200.000 VND y requiere tu PIN.' },
  'settings.familyData': { title: 'Datos familiares', text: 'Descarga una copia JSON de los datos de la familia. No contiene el PIN ni datos de pago, pero sí datos de tus hijos: mantén el archivo privado.' },
  'settings.leaderboardSharing': { title: 'Compartir la tabla de clasificación', text: 'Interruptor para toda la familia, desactivado de forma predeterminada. Al activarlo, solo aparecen los niños que elijas en su perfil, con apodo y sin nombre real ni edad.' },
  'settings.analytics': { title: 'Medición anónima', text: 'Permite medir datos generales sin nombres ni contenido. Aún no hay destino de recopilación, así que nada sale del dispositivo. Está desactivado de forma predeterminada.' },
  'settings.reminders': { title: 'Recordatorios', text: 'Solo para tareas o recompensas pendientes de tu aprobación, nunca publicidad. Puedes permitir notificaciones y desactivarlas cuando quieras.' },
  'settings.theme': { title: 'Aspecto', text: 'Claro, oscuro o según el dispositivo.' },
  'settings.pin': { title: 'PIN', text: 'Cuatro dígitos que protegen el área de padres. Tras introducirlo correctamente, este navegador queda desbloqueado durante 2 horas. Se necesita para aprobar, revocar dispositivos, pagar, eliminar datos y solicitar el retiro de tus comisiones por recomendación. Nunca lo compartas con tu hijo.' },

  'payment.plans': { title: 'Planes', text: 'Plan para un niño: 29.000 VND/mes (1 niño); Familia mensual: 49.000 VND/mes; Familia anual: 399.000 VND/año. Un solo pago, sin renovación automática.' },
  'payment.trial': { title: 'Prueba de 7 días', text: 'Gratis, sin tarjeta y sin cobro automático. Una vez por familia.' },
  'payment.memo': { title: 'Concepto de transferencia', text: 'Mantén el importe y el concepto exactos para que el sistema reconozca el pago. Puedes copiar cada dato o descargar el código QR.' },
  'payment.activation': { title: 'Cuándo se activa el plan', text: 'Cuando se confirme el pago, normalmente en segundos. Si no aparece, espera unos minutos y vuelve a abrir la aplicación; contacta con soporte con el código del pedido.' },
};
