import type { HelpTopicId } from './help-topic-id';

// The short explanation behind every "?" in the parent screens, and the part of the guide it opens. Loaded the first
// time a "?" is used, so none of this text weighs on the first download. Every topic must name a real guide section
// (a test checks), and a language without a text here reads the English one.

export type HelpText = { readonly title: string; readonly text: string };
export type HelpTopic = {
  readonly chapter: string;
  readonly anchor: string;
  readonly vi: HelpText;
  readonly en: HelpText;
};

const topic = (chapter: string, anchor: string, vi: readonly [string, string], en: readonly [string, string]): HelpTopic => ({
  chapter,
  anchor,
  vi: { title: vi[0], text: vi[1] },
  en: { title: en[0], text: en[1] },
});

const TODAY = 'hom-nay-va-duyet-viec';
const DESIGN = 'thiet-ke-thoi-quen';
const FAMILY = 'gia-dinh-va-cai-dat';
const PLANS = 'goi-va-thanh-toan';
const PRIVACY = 'bao-mat-va-rieng-tu';

export const HELP_TOPICS: Readonly<Record<HelpTopicId, HelpTopic>> = {
  'today.card': topic(TODAY, 'hom-nay',
    ['Hôm nay của bé', 'Tóm tắt ngày hôm nay của bé: số việc đã xong trên số việc theo lịch, chuỗi ngày và những việc cần ba mẹ làm. Có nhiều bé thì chọn bé ở hàng nút phía trên.'],
    ['Your child’s today', 'A summary of today: tasks done out of those scheduled, the streak and what needs you. With several children, choose one in the row above.']),
  'today.actions': topic(TODAY, 'can-xu-ly',
    ['Cần bạn xử lý', 'Một dải gom mọi thứ đang chờ ba mẹ: việc cần duyệt, yêu cầu đổi quà và gợi ý điều chỉnh. Bấm một mục để nhảy tới đúng chỗ cần làm. Không có gì chờ thì dải báo như vậy.'],
    ['Needs you', 'One strip that gathers everything waiting for you: tasks to approve, reward requests and adjustment suggestions. Tap an item to jump to where you act on it. When nothing is waiting, it says so.']),
  'approvals.tasks': topic(TODAY, 'duyet',
    ['Việc chờ duyệt', 'Những việc bé đã đánh dấu xong mà bạn đặt là "cần duyệt". Bấm Duyệt để cộng sao cho bé; Từ chối thì không cộng. Cần mã PIN nếu bạn đã đặt. Có thể tick nhiều việc rồi duyệt một lần (không tick sẵn; một lần PIN cho cả lô).'],
    ['Tasks waiting for approval', 'Tasks your child marked done that you set to "needs approval". Approve to give the stars; reject to give none. Needs your PIN if you set one. You can tick several tasks and approve them in one go (nothing is ticked for you; one PIN covers the batch).']),
  'approvals.rewards': topic(TODAY, 'duyet',
    ['Yêu cầu đổi quà', 'Quà bé xin đổi; sao đã được trừ lúc xin. Bạn duyệt rồi trao quà. Nếu từ chối, sao được hoàn lại cho bé.'],
    ['Reward requests', 'Rewards your child asked for; the stars were taken when they asked. Approve, then hand it over. If you reject, the stars go back.']),
  'support.prompt': topic(TODAY, 'muc-ho-tro',
    ['Hôm nay con làm thế nào?', 'Không bắt buộc. Ghi bé đã làm một thói quen một mình, cần nhắc hay làm cùng ba mẹ để ứng dụng biết khi nào nên giảm nhắc nhở. Không dùng để so sánh các bé.'],
    ['How did it go today?', 'Optional. Note whether your child did a habit alone, with a reminder or together, so the app knows when to ease off. Never used to compare children.']),
  'progress.summary': topic(TODAY, 'tien-trien',
    ['Tiến triển thói quen', 'Mỗi thói quen đã có tín hiệu nằm ở một giai đoạn: chọn tín hiệu, xây nếp, giảm hỗ trợ, thành nếp. Đây là gợi ý để đồng hành, không phải điểm số.'],
    ['Habit progress', 'Each habit with a cue sits in a stage: choosing the cue, building, easing support, established. It is a guide for you, not a score.']),
  'progress.graduation': topic(TODAY, 'tot-nghiep',
    ['Tốt nghiệp thói quen', 'Khi bé tự làm một thói quen đều nhiều tuần, ứng dụng gợi ý cho nó “tốt nghiệp”: rời danh sách hằng ngày, nằm ở “Con đã làm được”, không mất sao hay nhật ký. Mỗi tháng hỏi lại một chạm. Ba mẹ quyết định và có thể hoàn tác.'],
    ['Graduating a habit', 'When your child does a habit alone for several weeks, the app suggests letting it graduate: it leaves the daily list, stays under “What I can do”, and no stars or history are lost. It asks again monthly. You decide and can undo it.']),
  'progress.supportTrend': topic(TODAY, 'xu-huong-ho-tro',
    ['Mức hỗ trợ theo tuần', 'Biểu đồ cột cho thấy mỗi tuần bé tự làm, cần nhắc hay làm cùng. Ứng dụng chỉ nói “mức hỗ trợ đang giảm” khi có đủ ít nhất ba tuần liền dữ liệu và tỷ lệ tự làm tăng rõ. Không dùng để so sánh các bé.'],
    ['Support by week', 'The bars show, week by week, whether your child did it alone, with a reminder or together. The app says “support is easing” only with at least three weeks in a row of data and a clear rise in doing it alone. Never used to compare children.']),
  'weekly.review': topic(TODAY, 'nhin-lai-tuan',
    ['Nhìn lại tuần', 'Mỗi tuần một lần, cả nhà cùng nhìn lại 5 phút: một điều để khen, một điều cần chỉnh và có nên thêm thói quen mới chưa.'],
    ['Weekly look-back', 'Once a week, five minutes together: one thing to praise, one to adjust and whether to add a new habit.']),
  'stats.weekly': topic(TODAY, 'thong-ke',
    ['Xu hướng 7 ngày', 'Mỗi cột là số việc cả nhà đã hoàn thành trong ngày. Ngày không làm là cột trống.'],
    ['Seven-day trend', 'Each bar is how many tasks the family completed that day. A day with nothing done is an empty bar.']),
  'stats.print': topic(TODAY, 'thong-ke',
    ['In bảng và báo cáo tuần', 'In bảng thói quen để dán tủ lạnh, hoặc báo cáo tuần về số lượt và điểm đã làm. In qua hộp thoại in của trình duyệt.'],
    ['Print the week', 'Print a habit chart for the fridge or a weekly report of turns and points. It uses your browser’s print dialog.']),
  'stats.journal': topic(TODAY, 'thong-ke',
    ['Nhật ký một câu', 'Những câu bé tự ghi về điều muốn nhớ mỗi ngày. Chỉ bé và phụ huynh xem được, không dùng để đo lường. Có thể xuất CSV; file chứa chữ của bé nên hãy giữ riêng tư.'],
    ['One-line journal', 'The lines your child writes about what they want to remember. Only your child and you can read them; they are never measured. Export to CSV and keep the file private.']),
  'stats.share': topic(TODAY, 'thong-ke',
    ['Chia sẻ cột mốc', 'Xem trước rồi tự xác nhận chia sẻ một thông điệp của cả gia đình. Nội dung mặc định không có tên, tuổi, ảnh hay nhiệm vụ của trẻ.'],
    ['Share a milestone', 'Preview, then confirm yourself. The default message holds no child’s name, age, photo or tasks.']),
  'stats.deleteFamily': topic(PRIVACY, 'xoa-du-lieu',
    ['Xóa dữ liệu gia đình', 'Chỉ chủ gia đình làm được. Xóa vĩnh viễn hồ sơ bé, thói quen, tiến độ, quà và thiết bị đã ghép; không hoàn tác. Cần gõ đúng DELETE FAMILY.'],
    ['Delete family data', 'Only the family owner can. It permanently removes profiles, habits, progress, rewards and paired devices, and cannot be undone. You must type DELETE FAMILY.']),

  'habits.inUse': topic(DESIGN, 'quan-ly-viec',
    ['Việc đang dùng', 'Các việc đang giao cho bé. Lọc theo bé, xem số lần hoàn thành trong 7 ngày, sửa, xóa hoặc đặt tín hiệu.'],
    ['Tasks in use', 'The tasks now assigned. Filter by child, see completions in the last 7 days, edit, delete or set a cue.']),
  'habits.library': topic(DESIGN, 'thu-vien',
    ['Thư viện', 'Kho thói quen mẫu để thêm vào lịch. Tiếng Việt dùng Khung 47 thói quen theo giai đoạn tuổi; ngôn ngữ khác dùng các nhóm mẫu.'],
    ['Library', 'Ready-made habits to add to the schedule. Vietnamese uses the 47-habit framework by age stage; other languages use template packs.']),
  'habits.programs': topic(DESIGN, 'chuong-trinh',
    ['Chương trình', 'Xây thói quen từng bước cho một bé: chọn ít thói quen, đặt tín hiệu rồi theo dõi giai đoạn. Chỉ có ở tiếng Việt.'],
    ['Programs', 'Build habits step by step for one child: pick a few, set cues, then follow the stage. Vietnamese only.']),
  'habits.framework': topic(DESIGN, 'khung-47',
    ['Khung 47 thói quen', 'Chọn giai đoạn và lĩnh vực, đọc ý nghĩa và cách đồng hành trước khi thêm. Việc thêm từ khung là việc chung cho cả nhà; muốn giao riêng một bé thì sửa mục Giao cho.'],
    ['The 47-habit framework', 'Choose a stage and area, read the meaning and how to help before adding. Habits added here are for the whole family; change "Assign to" to give one to a single child.']),
  'habits.handbook': topic('khoa-hoc-thoi-quen', 'chan-dung',
    ['Cẩm nang 16 chân dung', 'Cẩm nang về 16 chân dung, 7 cách cho đi và nghệ thuật làm gương. Có thể áp dụng bộ hành động theo tuổi cho một bé.'],
    ['16-portrait handbook', 'A handbook of 16 portraits, 7 ways of giving and the art of leading by example. You can apply an age-based set of actions to a child.']),
  'habits.cue': topic(DESIGN, 'chuong-trinh',
    ['Tín hiệu "nếu… thì…"', 'Gắn thói quen với một việc quen thuộc hoặc một giờ cố định, theo lời của bé, ví dụ "Sau khi đánh răng, con đọc một trang sách". Tín hiệu rõ giúp bé bắt đầu dễ hơn.'],
    ['"If… then…" cue', 'Tie a habit to something familiar or a fixed time, in your child’s words, such as "After brushing my teeth I read a page". A clear cue makes starting easier.']),
  'habits.programStart': topic(DESIGN, 'chuong-trinh',
    ['Bắt đầu chương trình', 'Ba bước: chọn thói quen bắt đầu (nên chỉ một đến hai), đặt tín hiệu cho từng thói quen, rồi xác nhận. Chọn nhiều hơn mức gợi ý chỉ bị cảnh báo.'],
    ['Starting a program', 'Three steps: pick the habits to start (one or two is best), set a cue for each, then confirm. Choosing more than suggested only shows a warning.']),
  'habits.form.points': topic(DESIGN, 'tao-viec',
    ['Số sao thưởng', 'Số sao bé nhận khi hoàn thành. Việc cần duyệt chỉ cộng sao sau khi bạn duyệt.'],
    ['Star reward', 'The stars your child earns. For tasks that need approval they are added only after you approve.']),
  'habits.form.recurrence': topic(DESIGN, 'tao-viec',
    ['Lặp lại', 'Việc hiện vào những ngày nào: mỗi ngày, thứ 2 đến thứ 6, thứ 7 và chủ nhật, hoặc ngày tùy chọn.'],
    ['Repeat', 'Which days the task appears: every day, weekdays, weekends or days you choose.']),
  'habits.form.time': topic(DESIGN, 'tao-viec',
    ['Khung giờ', 'Buổi sáng, chiều, tối hoặc bất kỳ lúc nào. Màn hình của bé nhóm việc theo khung giờ này.'],
    ['Time of day', 'Morning, afternoon, evening or any time. Your child’s screen groups tasks by this.']),
  'habits.form.duration': topic(DESIGN, 'tao-viec',
    ['Thời gian đếm ngược', 'Số phút cho đồng hồ trên màn hình bé, ví dụ đánh răng 2 phút. Để 0 nếu không cần đếm giờ.'],
    ['Countdown time', 'Minutes for the timer on your child’s screen, such as 2 minutes of brushing. Leave 0 for no timer.']),
  'habits.form.approval': topic(DESIGN, 'tao-viec',
    ['Yêu cầu phụ huynh duyệt', 'Bật thì bé tick xong chưa được sao cho đến khi bạn duyệt. Hợp với việc bạn muốn tự kiểm tra.'],
    ['Needs your approval', 'When on, ticking does not give stars until you approve. Good for tasks you want to check.']),
  'habits.form.assign': topic(DESIGN, 'tao-viec',
    ['Giao cho', 'Chọn tất cả các bé hoặc một bé. Việc chung hiện cho mọi bé.'],
    ['Assign to', 'Pick all children or one. A shared task appears for every child.']),

  'journeys.overview': topic(DESIGN, 'lo-trinh',
    ['Lộ trình theo tuổi', 'Năm giai đoạn theo tuổi, mỗi giai đoạn ba bước, mỗi bước chỉ thêm một thói quen. Mốc tuần là nơi bắt đầu xem lại, không phải hạn chót. Chọn bé rồi Áp dụng để thêm thói quen vào lịch.'],
    ['Age roadmaps', 'Five age stages, three steps each, one new habit per step. Week marks are where to start looking back, not deadlines. Choose a child and Apply to add the habits.']),

  'rewards.manage': topic(DESIGN, 'kho-qua',
    ['Kho quà', 'Phần thưởng bạn tạo để bé dùng sao đổi. Bé xin đổi, bạn duyệt rồi trao quà. Nên ưu tiên thời gian bên nhau và trải nghiệm hơn đồ vật.'],
    ['Reward shelf', 'Rewards you create for your child to spend stars on. They ask, you approve, then hand it over. Time together and experiences beat things.']),
  'rewards.templates': topic(DESIGN, 'kho-qua',
    ['Gợi ý quà', 'Mẫu quà phi vật chất và quà vật chất có mục đích, kèm số sao gợi ý. Chọn Thêm vào kho quà rồi sửa lại tùy gia đình.'],
    ['Reward ideas', 'Experience and purposeful material rewards with a suggested star cost. Add to your shelf and adjust it for your family.']),

  'children.profiles': topic(FAMILY, 'ho-so',
    ['Hồ sơ các con', 'Mỗi bé một hồ sơ: tên, biệt danh, tuổi, linh vật và màu. Số bé được thêm phụ thuộc gói bạn dùng.'],
    ['Child profiles', 'One profile per child: name, nickname, age, mascot and colour. How many you can add depends on your plan.']),
  'children.age': topic(FAMILY, 'ho-so',
    ['Tuổi của bé', 'Tuổi quyết định giai đoạn (0–3, 3–6, 6–12, 12–18), gợi ý thói quen và giao diện màn hình của bé.'],
    ['Child’s age', 'Age sets the stage (0–3, 3–6, 6–12, 12–18), the habit suggestions and how your child’s screen looks.']),
  'children.leaderboard': topic(PRIVACY, 'bxh-cong-khai',
    ['Bảng xếp hạng', 'Bé mới mặc định riêng tư. Chỉ khi cả gia đình bật chia sẻ trong Cài đặt và bé được chọn thì bé mới lên bảng công khai, bằng biệt danh.'],
    ['Leaderboard', 'New profiles are private. A child appears on the public board only when the family turns sharing on in Settings and the child is chosen, under a nickname.']),
  'children.ageTheme': topic('man-hinh-be', 'giao-dien-tuoi',
    ['Giao diện theo tuổi', 'Màn hình bé tự đổi theo tuổi. Bạn có thể ghim một dải tuổi hoặc giữ giao diện cũ; lựa chọn của bạn được ưu tiên hơn lựa chọn của bé.'],
    ['Age-based look', 'Your child’s screen adapts to their age. You can pin an age band or keep the old look; your choice beats your child’s.']),
  'children.pairing': topic(FAMILY, 'ghep-thiet-bi',
    ['Mã kết nối', 'Mỗi bé có một mã cố định, chỉ mở đúng hồ sơ của bé. Quét QR hoặc nhập mã trên máy của bé. Cần PIN nếu đã đặt.'],
    ['Connection code', 'Each child has a fixed code that opens only their profile. Scan the QR or type the code on your child’s device. Needs your PIN if set.']),
  'children.regenerate': topic(FAMILY, 'ghep-thiet-bi',
    ['Làm mới mã', 'Cấp mã mới thì mã cũ hết hiệu lực. Chỉ làm khi nghi mã bị lộ. Cần PIN.'],
    ['New code', 'A new code makes the old one stop working. Do it only if you think the code leaked. Needs your PIN.']),
  'children.adjustPoints': topic(TODAY, 'chinh-sao',
    ['Thưởng hoặc trừ sao', 'Cộng thưởng (số dương) hay trừ (số âm) kèm lý do ngắn. Cần PIN. Dùng để ghi nhận ngoài các việc đã giao.'],
    ['Add or take stars', 'Reward (positive) or deduct (negative) with a short reason. Needs your PIN. For recognising things outside assigned tasks.']),
  'children.ageBundle': topic(FAMILY, 'ho-so',
    ['Gói thói quen theo tuổi', 'Nạp một chạm sáu việc khởi đầu hợp lứa tuổi của bé. Sau đó bạn vẫn sửa hoặc xóa được.'],
    ['Age starter pack', 'Load six starter tasks for your child’s age in one tap. You can edit or delete them afterwards.']),

  'settings.devices': topic(FAMILY, 'thiet-bi',
    ['Thiết bị của các bé', 'Danh sách máy đã ghép: của bé nào, lần truy cập gần nhất. Thu hồi quyền ngay khi mất máy hoặc không dùng nữa (cần PIN).'],
    ['Children’s devices', 'The paired devices: whose, and last seen. Revoke access as soon as a device is lost or no longer used (needs your PIN).']),
  'settings.pwa': topic(FAMILY, 'pwa',
    ['Cài ứng dụng', 'Cài KidHabit lên màn hình chính để mở nhanh như một ứng dụng. Trên iPhone: Safari → Chia sẻ → Thêm vào Màn hình chính.'],
    ['Install the app', 'Add KidHabit to your home screen to open it like an app. On iPhone: Safari → Share → Add to Home Screen.']),
  'settings.caregivers': topic(FAMILY, 'nguoi-cham-soc',
    ['Người chăm sóc', 'Mời ông bà hoặc người thân xem tiến độ bằng liên kết dùng một lần, hết hạn sau 72 giờ. Họ chỉ xem, không sửa được gì. Thu hồi lời mời bất cứ lúc nào.'],
    ['Caregivers', 'Invite grandparents or relatives to view progress with a one-time link that expires after 72 hours. They can only view. Revoke an invite any time.']),
  'settings.pause': topic(FAMILY, 'tam-nghi',
    ['Tạm nghỉ', 'Khi cả nhà cần nghỉ, bấm Tạm nghỉ: ẩn nhắc tiến độ và chuỗi, không phá chuỗi, không mất sao hay quà. Bấm Tiếp tục khi sẵn sàng.'],
    ['Family break', 'When the family needs a rest, choose Take a break: progress prompts and streaks are hidden, the streak is not broken and no stars or rewards are lost. Resume when ready.']),
  'settings.account': topic(FAMILY, 'tai-khoan',
    ['Thông tin khách hàng', 'Họ tên và số điện thoại để hỗ trợ tài khoản và thanh toán. Bạn bật hoặc tắt nhận ưu đãi bất cứ lúc nào.'],
    ['Customer details', 'Name and phone number for account and payment support. You can switch offers on or off any time.']),
  'settings.coupon': topic(PLANS, 'coupon',
    ['Mã tặng', 'Nhập mã tặng để cộng thêm ngày sử dụng. Mỗi gia đình dùng một mã một lần; thử sai quá nhiều sẽ bị khóa vài phút.'],
    ['Gift code', 'Enter a gift code to add days of use. Each family uses a code once; too many wrong tries lock it for a few minutes.']),
  'settings.referralCode': topic('gioi-thieu-ban-be', 'giam-10',
    ['Mã giới thiệu', 'Nếu bạn bè giới thiệu, nhập mã 8 ký tự để được giảm 10% Gói Năm lần đầu. Chỉ nhập được khi gia đình còn mới và chưa trả tiền.'],
    ['Referral code', 'If a friend referred you, enter the 8-character code for 10% off your first yearly plan. Only while the family is new and has not paid.']),
  'settings.affiliate': topic('gioi-thieu-ban-be', 'tham-gia',
    ['Giới thiệu bạn bè', 'Chia sẻ liên kết của bạn để nhận hoa hồng 30% khi gia đình mới trả tiền. Hoa hồng được giữ 35 ngày, rút tối thiểu 200.000đ và cần mã PIN.'],
    ['Refer friends', 'Share your link to earn 30% commission when a new family pays. Commission is held for 35 days; the minimum payout is 200,000 VND and needs your PIN.']),
  'settings.familyData': topic(FAMILY, 'du-lieu',
    ['Dữ liệu gia đình', 'Tải về bản sao JSON dữ liệu gia đình. File không chứa PIN hay thanh toán nhưng có dữ liệu của bé nên hãy giữ riêng tư.'],
    ['Family data', 'Download a JSON copy of the family’s data. It holds no PIN or payment details, but it does hold your children’s data, so keep it private.']),
  'settings.leaderboardSharing': topic(FAMILY, 'rieng-tu',
    ['Chia sẻ bảng xếp hạng', 'Công tắc cho cả gia đình, mặc định tắt. Bật thì chỉ những bé bạn chọn ở hồ sơ mới hiện, bằng biệt danh, không có tên thật hay tuổi.'],
    ['Leaderboard sharing', 'A family-wide switch, off by default. When on, only children you choose in their profile appear, by nickname, with no real name or age.']),
  'settings.analytics': topic(PRIVACY, 'do-luong',
    ['Đo lường ẩn danh', 'Cho phép đo lường chung, không chứa tên hay nội dung của bé. Hiện chưa có nơi nhận dữ liệu nên chưa có gì rời khỏi thiết bị. Mặc định tắt.'],
    ['Anonymous measurement', 'Allows general measurement with no names or content. There is no collection point yet, so nothing leaves the device. Off by default.']),
  'settings.reminders': topic(FAMILY, 'nhac-viec',
    ['Nhắc việc', 'Chỉ nhắc khi có việc hoặc quà chờ bạn duyệt, không quảng cáo. Có thể cho phép thông báo trên thiết bị; tắt bất cứ lúc nào.'],
    ['Reminders', 'Only when tasks or rewards wait for you, never advertising. You can allow device notifications and turn it off any time.']),
  'settings.theme': topic(FAMILY, 'giao-dien',
    ['Giao diện', 'Sáng, tối hoặc theo thiết bị.'],
    ['Appearance', 'Light, dark or follow the device.']),
  'settings.pin': topic(FAMILY, 'pin',
    ['Mã PIN', 'Bốn chữ số, bảo vệ khu quản lý. Nhập đúng thì trình duyệt này được mở khóa 2 giờ. Cần cho duyệt việc, thu hồi thiết bị, thanh toán, xóa dữ liệu và rút tiền giới thiệu. Không chia sẻ với bé.'],
    ['PIN', 'Four digits that protect the parent area. After a correct entry this browser stays unlocked for 2 hours. Needed to approve, revoke devices, pay, delete data and withdraw referral money. Never share it with your child.']),

  'payment.plans': topic(PLANS, 'cac-goi',
    ['Các gói', 'Gói Một Bé 29.000đ/tháng (1 bé), Gia Đình · Tháng 49.000đ, Gia Đình · Năm 399.000đ. Thanh toán một lần, không tự gia hạn.'],
    ['Plans', 'One Child 29,000 VND/month (1 child), Family Monthly 49,000 VND, Family Yearly 399,000 VND. One-off payment, no auto-renewal.']),
  'payment.trial': topic(PLANS, 'dung-thu',
    ['Dùng thử 7 ngày', 'Miễn phí, không cần thẻ, không tự trừ tiền. Mỗi gia đình một lần.'],
    ['7-day trial', 'Free, no card, no automatic charge. Once per family.']),
  'payment.memo': topic(PLANS, 'thanh-toan',
    ['Nội dung chuyển khoản', 'Giữ đúng số tiền và nội dung chuyển khoản để hệ thống nhận ra khoản thanh toán. Bạn có thể sao chép từng mục hoặc tải mã QR.'],
    ['Transfer memo', 'Keep the exact amount and memo so the system recognises your payment. You can copy each item or download the QR.']),
  'payment.activation': topic(PLANS, 'kich-hoat',
    ['Khi nào gói được mở', 'Ngay khi hệ thống xác nhận khoản tiền, thường trong vài giây. Nếu chưa thấy, chờ vài phút và mở lại; liên hệ hỗ trợ kèm mã đơn.'],
    ['When the plan opens', 'As soon as the payment is confirmed, usually within seconds. If not, wait a few minutes and reopen; contact support with the order code.']),
};
