import type { HelpTopicId } from './help-topic-id';
import type { HelpText } from './help-topics';

export const HELP_TOPICS_DE: Readonly<Record<HelpTopicId, HelpText>> = {
  'today.card': { title: 'Heute für Ihr Kind', text: 'Zusammenfassung des Tages: erledigte und geplante Aufgaben, die Serie und was Sie tun müssen. Bei mehreren Kindern wählen Sie eines oben aus.' },
  'approvals.tasks': { title: 'Aufgaben zur Freigabe', text: 'Erledigte Aufgaben mit „Freigabe erforderlich“. Genehmigen für Sterne; bei Ablehnung gibt es keine. PIN nötig, falls festgelegt.' },
  'approvals.rewards': { title: 'Belohnungsanfragen', text: 'Von Ihrem Kind angefragte Belohnungen; die Sterne wurden bei der Anfrage abgezogen. Genehmigen und aushändigen. Bei Ablehnung werden die Sterne zurückgegeben.' },
  'support.prompt': { title: 'Wie lief es heute?', text: 'Optional. Geben Sie an, ob Ihr Kind eine Gewohnheit allein, mit Erinnerung oder gemeinsam erledigt hat, damit die App weniger erinnert. Niemals zum Vergleich von Kindern.' },
  'progress.summary': { title: 'Gewohnheitsfortschritt', text: 'Jede Gewohnheit mit Auslöser hat eine Phase: Auslöser wählen, aufbauen, Unterstützung reduzieren, etabliert. Orientierung, keine Bewertung.' },
  'weekly.review': { title: 'Wöchentlicher Rückblick', text: 'Einmal pro Woche fünf Minuten gemeinsam: eine Sache zum Loben, eine zum Anpassen und ob eine neue Gewohnheit dazukommen soll.' },
  'stats.weekly': { title: 'Trend der letzten 7 Tage', text: 'Jeder Balken zeigt die erledigten Aufgaben der Familie an diesem Tag. Ohne Erledigungen bleibt er leer.' },
  'stats.print': { title: 'Woche drucken', text: 'Drucken Sie eine Gewohnheitentafel für den Kühlschrank oder einen Wochenbericht mit Anzahl und Punkten über den Druckdialog Ihres Browsers.' },
  'stats.journal': { title: 'Einzeiliges Tagebuch', text: 'Zeilen, die Ihr Kind zu Dingen schreibt, an die es sich erinnern möchte. Nur Sie und Ihr Kind können sie lesen; sie werden nicht gemessen. Als CSV exportierbar. Bewahren Sie die Datei privat auf.' },
  'stats.share': { title: 'Meilenstein teilen', text: 'Vorschau ansehen und selbst bestätigen. Die Standardnachricht enthält keinen Namen, kein Alter, Foto oder Kinderaufgaben.' },
  'stats.deleteFamily': { title: 'Familiendaten löschen', text: 'Nur der Familieninhaber kann dies tun. Profile, Gewohnheiten, Fortschritt, Belohnungen und gekoppelte Geräte werden dauerhaft gelöscht. Nicht rückgängig. DELETE FAMILY eingeben.' },

  'habits.inUse': { title: 'Verwendete Aufgaben', text: 'Derzeit zugewiesene Aufgaben. Nach Kind filtern, Erledigungen der letzten 7 Tage ansehen, bearbeiten, löschen oder Auslöser festlegen.' },
  'habits.library': { title: 'Bibliothek', text: 'Fertige Gewohnheiten für den Zeitplan. Auf Vietnamesisch gilt das 47-Gewohnheiten-Modell nach Altersstufen; andere Sprachen nutzen Vorlagenpakete.' },
  'habits.programs': { title: 'Programme', text: 'Gewohnheiten für ein Kind aufbauen: auswählen, Auslöser setzen und Phase verfolgen. Nur auf Vietnamesisch.' },
  'habits.framework': { title: '47-Gewohnheiten-Modell', text: 'Altersstufe und Bereich wählen, Bedeutung und Unterstützung lesen, dann hinzufügen. Hier hinzugefügte Gewohnheiten gelten für die Familie. Mit „Zuweisen an“ geben Sie eine nur einem Kind.' },
  'habits.handbook': { title: 'Handbuch der 16 Porträts', text: 'Ein Handbuch über 16 Porträts, 7 Arten des Gebens und die Kunst, mit gutem Beispiel voranzugehen. Sie können für ein Kind ein altersbezogenes Maßnahmenpaket anwenden.' },
  'habits.cue': { title: '„Wenn … dann …“-Auslöser', text: 'Gewohnheit mit Vertrautem oder fester Zeit verknüpfen, in den Worten des Kindes: „Nach dem Zähneputzen lese ich eine Seite.“ Ein klarer Auslöser erleichtert den Anfang.' },
  'habits.programStart': { title: 'Programm starten', text: 'Drei Schritte: Startgewohnheiten auswählen (eine oder zwei sind am besten), für jede einen Auslöser setzen und bestätigen. Mehr als empfohlen zeigt nur eine Warnung.' },
  'habits.form.points': { title: 'Sterne-Belohnung', text: 'Die Sterne für Ihr Kind. Bei freigabepflichtigen Aufgaben werden sie erst nach Ihrer Genehmigung gutgeschrieben.' },
  'habits.form.recurrence': { title: 'Wiederholung', text: 'Tage, an denen die Aufgabe erscheint: täglich, wochentags, am Wochenende oder nach Ihrer Auswahl.' },
  'habits.form.time': { title: 'Tageszeit', text: 'Morgen, Nachmittag, Abend oder jederzeit. Der Kinderbildschirm gruppiert Aufgaben danach.' },
  'habits.form.duration': { title: 'Countdown-Zeit', text: 'Minuten für den Timer auf dem Bildschirm Ihres Kindes, etwa 2 Minuten Zähneputzen. 0 bedeutet: kein Timer.' },
  'habits.form.approval': { title: 'Elternfreigabe erforderlich', text: 'Aktiviert: Beim Abhaken gibt es erst Sterne, nachdem Sie genehmigt haben. Für Aufgaben, die Sie prüfen möchten.' },
  'habits.form.assign': { title: 'Zuweisen an', text: 'Alle Kinder oder ein Kind auswählen. Gemeinsame Aufgaben erscheinen bei jedem Kind.' },

  'journeys.overview': { title: 'Fahrpläne nach Alter', text: 'Fünf Altersstufen mit drei Schritten und einer neuen Gewohnheit pro Schritt. Wochenmarken sind Rückblickpunkte, keine Fristen. Kind wählen und „Übernehmen“ tippen, um Gewohnheiten hinzuzufügen.' },

  'rewards.manage': { title: 'Belohnungsregal', text: 'Von Ihnen erstellte Belohnungen, für die Ihr Kind Sterne einlöst. Ihr Kind fragt an, Sie genehmigen und händigen aus. Gemeinsame Zeit und Erlebnisse sind besser als Dinge.' },
  'rewards.templates': { title: 'Belohnungsideen', text: 'Erlebnisse und sinnvolle Sachbelohnungen mit empfohlenen Sternkosten. Fügen Sie eine Belohnung zu Ihrem Regal hinzu und passen Sie sie an Ihre Familie an.' },

  'children.profiles': { title: 'Kinderprofile', text: 'Ein Profil pro Kind: Name, Spitzname, Alter, Maskottchen und Farbe. Wie viele Kinder Sie hinzufügen können, hängt von Ihrem Tarif ab.' },
  'children.age': { title: 'Alter des Kindes', text: 'Das Alter bestimmt die Stufe (0–3, 3–6, 6–12, 12–18), Gewohnheitenvorschläge und das Aussehen des Kinderbildschirms.' },
  'children.leaderboard': { title: 'Rangliste', text: 'Neue Profile sind privat. Ein Kind erscheint nur dann öffentlich, wenn die Familie das Teilen in den Einstellungen aktiviert und das Kind ausgewählt hat, und zwar unter einem Spitznamen.' },
  'children.ageTheme': { title: 'Altersgerechtes Aussehen', text: 'Der Kinderbildschirm passt sich dem Alter an. Sie können eine Altersstufe festlegen oder das alte Aussehen behalten; Ihre Wahl hat Vorrang.' },
  'children.pairing': { title: 'Verbindungscode', text: 'Jedes Kind hat einen festen Code, der nur sein Profil öffnet. QR-Code scannen oder Code auf dem Kindergerät eingeben. Bei festgelegter PIN ist diese nötig.' },
  'children.regenerate': { title: 'Neuer Code', text: 'Ein neuer Code macht den alten ungültig. Nur verwenden, wenn der Code vermutlich bekannt wurde. PIN erforderlich.' },
  'children.adjustPoints': { title: 'Sterne hinzufügen oder abziehen', text: 'Positive Zahl als Belohnung oder negative Zahl zum Abziehen, jeweils mit kurzem Grund. PIN erforderlich. Für Anerkennung außerhalb zugewiesener Aufgaben.' },
  'children.ageBundle': { title: 'Starterpaket nach Alter', text: 'Mit einem Tippen sechs altersgerechte Starteraufgaben laden. Danach bearbeitbar oder löschbar.' },

  'settings.devices': { title: 'Geräte der Kinder', text: 'Gekoppelte Geräte mit Kind und letztem Zugriff. Zugriff bei Verlust oder Nichtgebrauch sofort widerrufen. PIN erforderlich.' },
  'settings.pwa': { title: 'App installieren', text: 'KidHabit zum Startbildschirm hinzufügen und wie eine App öffnen. iPhone: Safari → Teilen → Zum Home-Bildschirm.' },
  'settings.caregivers': { title: 'Betreuungspersonen', text: 'Großeltern oder Verwandte mit einem einmaligen, nach 72 Stunden ablaufenden Link zum Ansehen einladen. Sie können nur ansehen. Einladung jederzeit widerrufbar.' },
  'settings.pause': { title: 'Familienpause', text: '„Pause machen“ blendet Fortschrittsimpulse und Serien aus, unterbricht die Serie aber nicht. Sterne und Belohnungen bleiben erhalten. Bei Bedarf fortsetzen.' },
  'settings.account': { title: 'Kundendaten', text: 'Name und Telefonnummer für Konto- und Zahlungshilfe. Angebote jederzeit ein- oder ausschalten.' },
  'settings.coupon': { title: 'Geschenkcode', text: 'Geschenkcode eingeben, um Nutzungstage hinzuzufügen. Einmal pro Familie; zu viele falsche Versuche sperren ihn einige Minuten.' },
  'settings.referralCode': { title: 'Empfehlungscode', text: '8-stelligen Code eines Freundes eingeben für 10 % Rabatt auf den ersten Jahrestarif. Nur für neue, noch nicht zahlende Familien.' },
  'settings.affiliate': { title: 'Freunde empfehlen', text: 'Link teilen und 30 % Provision erhalten, wenn eine neue Familie bezahlt. Auszahlung nach 35 Tagen, mindestens 200.000 VND, PIN erforderlich.' },
  'settings.familyData': { title: 'Familiendaten', text: 'Laden Sie eine JSON-Kopie der Familiendaten herunter. Sie enthält weder PIN noch Zahlungsdaten, aber Daten Ihrer Kinder. Bewahren Sie die Datei daher privat auf.' },
  'settings.leaderboardSharing': { title: 'Rangliste teilen', text: 'Familienweiter Schalter, standardmäßig aus. Aktiviert: Nur im Profil ausgewählte Kinder erscheinen unter Spitznamen, ohne echten Namen oder Alter.' },
  'settings.analytics': { title: 'Anonyme Messung', text: 'Allgemeine Messung ohne Namen oder Inhalte. Noch keine Datensammelstelle, daher verlässt nichts das Gerät. Standardmäßig aus.' },
  'settings.reminders': { title: 'Erinnerungen', text: 'Nur bei Aufgaben oder Belohnungen zur Freigabe, niemals Werbung. Gerätebenachrichtigungen erlauben und jederzeit ausschalten.' },
  'settings.theme': { title: 'Darstellung', text: 'Hell, dunkel oder wie auf dem Gerät.' },
  'settings.pin': { title: 'PIN', text: 'Vier Ziffern zum Schutz des Elternbereichs. Nach korrekter Eingabe bleibt dieser Browser 2 Stunden entsperrt. Nötig zum Genehmigen, Gerätewiderruf, Bezahlen, Löschen und Auszahlen von Empfehlungsprovisionen. Niemals mit dem Kind teilen.' },

  'payment.plans': { title: 'Tarife', text: 'Ein Kind: 29.000 VND/Monat (1 Kind), Familie monatlich: 49.000 VND, Familie jährlich: 399.000 VND. Einmalige Zahlung, keine automatische Verlängerung.' },
  'payment.trial': { title: '7-Tage-Test', text: 'Kostenlos, ohne Karte und automatische Abbuchung. Einmal pro Familie.' },
  'payment.memo': { title: 'Verwendungszweck', text: 'Betrag und Verwendungszweck exakt übernehmen, damit das System die Zahlung erkennt. Einträge kopieren oder QR-Code herunterladen.' },
  'payment.activation': { title: 'Tarif-Freischaltung', text: 'Nach Zahlungsbestätigung, meist innerhalb weniger Sekunden. Falls nicht: einige Minuten warten und erneut öffnen. Support mit Bestellcode kontaktieren.' },
};
