import type { HelpTranslationTable } from './help-topic-id';
import type { HelpText } from './help-topics';

export const HELP_TOPICS_IT: HelpTranslationTable<HelpText> = {
  'today.card': { title: 'Oggi del bambino', text: 'Un riepilogo di oggi: attività completate rispetto a quelle in programma, serie attiva e ciò che richiede il tuo intervento. Con più bambini, scegline uno nella riga qui sopra.' },
  'approvals.tasks': { title: 'Attività in attesa di approvazione', text: 'Attività segnate come completate dal bambino e impostate come "richiedono approvazione". Tocca Approva per assegnare le stelle; Rifiuta non ne assegna. Serve il PIN, se impostato.' },
  'approvals.rewards': { title: 'Richieste di premio', text: 'Premi richiesti dal bambino: le stelle sono state detratte al momento della richiesta. Approva e poi consegna il premio. Se rifiuti, le stelle vengono restituite.' },
  'support.prompt': { title: 'Com’è andata oggi?', text: 'Facoltativo. Indica se il bambino ha svolto un’abitudine da solo, con un promemoria o insieme a te, così l’app sa quando ridurre il supporto. Non viene usato per confrontare i bambini.' },
  'progress.summary': { title: 'Progresso delle abitudini', text: 'Ogni abitudine con un segnale si trova in una fase: scelta del segnale, costruzione, riduzione del supporto, consolidata. È una guida per te, non un punteggio.' },
  'today.actions': { title: 'Azioni che ti aspettano', text: 'Una barra raccoglie tutto ciò che richiede la tua attenzione: attività da approvare, richieste di premi e suggerimenti di modifica. Tocca una voce per passare direttamente all’azione. Se non c’è nulla in sospeso, la barra te lo indica.' },
  'progress.graduation': { title: 'Quando un’abitudine è consolidata', text: 'Quando tuo figlio svolge un’abitudine da solo per diverse settimane, l’app può suggerire di “concluderla”: scompare dall’elenco giornaliero e resta in «Cosa so fare», senza perdere stelle o cronologia. L’app te lo chiede di nuovo ogni mese. Decidi tu e puoi annullare.' },
  'progress.supportTrend': { title: 'Supporto settimana per settimana', text: 'Le barre mostrano, settimana per settimana, se tuo figlio ha svolto l’attività da solo, con un promemoria o insieme a te. L’app segnala che “il supporto sta diminuendo” solo dopo almeno tre settimane consecutive di dati e un chiaro aumento delle attività svolte da solo. Non serve a confrontare i bambini.' },
  'coach.weeklyChange': { title: 'Un cambiamento da provare questa settimana', text: 'Viene suggerito un solo cambiamento alla volta da provare per 7 giorni: semplificare, cambiare orario, fare insieme, cambiare segnale o ridurre i promemoria. Dopo 7 giorni l’app chiede se è stato utile. Non ripropone per 30 giorni ciò che non è stato d’aiuto.' },
  'coach.weeklyFocus': { title: 'Obiettivi della settimana', text: 'Indichi alcune attività tra cui tuo figlio può scegliere. All’inizio della settimana ne sceglie una o due come obiettivo e vede i progressi su 7 giorni. Se ha meno di 6 anni, scegliete insieme. Se non sceglie, si usano le abitudini che sta già esercitando.' },
  'weekly.review': { title: 'Riepilogo settimanale', text: 'Una volta alla settimana, cinque minuti insieme: una cosa da lodare, una da correggere e valutare se aggiungere una nuova abitudine.' },
  'stats.weekly': { title: 'Tendenza degli ultimi 7 giorni', text: 'Ogni barra indica le attività completate dalla famiglia quel giorno. Un giorno senza completamenti mostra una barra vuota.' },
  'stats.print': { title: 'Stampa la settimana', text: 'Stampa una tabella delle abitudini per il frigorifero o un report settimanale di turni e punti. Usa la finestra di stampa del browser.' },
  'stats.journal': { title: 'Diario di una riga', text: 'Le righe che il bambino scrive su ciò che vuole ricordare. Solo il bambino e tu potete leggerle; non vengono mai misurate. Esporta in CSV e conserva il file in privato.' },
  'stats.share': { title: 'Condividi un traguardo', text: 'Visualizza l’anteprima e conferma. Il messaggio predefinito non contiene nome, età, foto o attività del bambino.' },
  'stats.deleteFamily': { title: 'Elimina i dati della famiglia', text: 'Può farlo solo il proprietario della famiglia. Rimuove definitivamente profili, abitudini, progressi, premi e dispositivi associati e non può essere annullato. Devi digitare DELETE FAMILY.' },

  'habits.inUse': { title: 'Attività in uso', text: 'Le attività assegnate. Filtra per bambino, guarda i completamenti degli ultimi 7 giorni, modifica, elimina o imposta un segnale.' },
  'habits.library': { title: 'Libreria', text: 'Abitudini pronte da aggiungere al programma. L’italiano usa raccolte di modelli; il vietnamita usa il framework delle 47 abitudini per fasce d’età.' },
  'habits.programs': { title: 'Programmi', text: 'Costruisci le abitudini passo dopo passo: scegline alcune, imposta i segnali e segui la fase. Solo in vietnamita.' },
  'habits.framework': { title: 'Framework delle 47 abitudini', text: 'Scegli una fase e un’area, poi leggi il significato e come aiutare prima di aggiungere. Le abitudini aggiunte qui valgono per tutta la famiglia; cambia "Assegna a" per darle a un solo bambino.' },
  'habits.handbook': { title: 'Manuale dei 16 profili', text: 'Un manuale sui 16 profili, 7 modi di donare e l’arte di dare il buon esempio. Puoi applicare a un bambino una serie di azioni per età.' },
  'habits.cue': { title: 'Segnale "Se… allora…"', text: 'Collega un’abitudine a qualcosa di familiare o a un orario fisso, usando le parole del bambino, per esempio "Dopo aver lavato i denti leggo una pagina". Un segnale chiaro rende più facile iniziare.' },
  'habits.programStart': { title: 'Inizia un programma', text: 'Tre passaggi: scegli le abitudini da iniziare (una o due è l’ideale), imposta un segnale per ciascuna e poi conferma. Sceglierne più di quanto consigliato mostra solo un avviso.' },
  'habits.form.points': { title: 'Stelle premio', text: 'Le stelle guadagnate dal bambino. Per le attività da approvare, vengono assegnate solo dopo la tua approvazione.' },
  'habits.form.recurrence': { title: 'Ripetizione', text: 'Quando compare l’attività: ogni giorno, giorni feriali, fine settimana o giorni scelti da te.' },
  'habits.form.time': { title: 'Momento della giornata', text: 'Mattina, pomeriggio, sera o qualsiasi momento. La schermata del bambino raggruppa le attività così.' },
  'habits.form.duration': { title: 'Tempo del conto alla rovescia', text: 'Minuti per il timer nella schermata del bambino, per esempio 2 minuti per lavarsi i denti. Lascia 0 per non usare il timer.' },
  'habits.form.approval': { title: 'Richiede approvazione genitore', text: 'Se attivo, l’attività completata non assegna stelle finché non approvi. Utile per ciò che vuoi controllare.' },
  'habits.form.assign': { title: 'Assegna a', text: 'Scegli tutti i bambini o uno solo. Un’attività condivisa compare per ogni bambino.' },

  'journeys.overview': { title: 'Percorsi per età', text: 'Cinque fasce d’età, tre passaggi ciascuna e una nuova abitudine per passaggio. Le settimane indicano quando fare il punto, non sono scadenze. Scegli un bambino e tocca Applica per aggiungere le abitudini.' },

  'rewards.manage': { title: 'Scaffale dei premi', text: 'Premi che crei perché il bambino li riscatti con le stelle. Fa richiesta, tu approvi e poi consegni. Il tempo insieme e le esperienze valgono più degli oggetti.' },
  'rewards.templates': { title: 'Idee per i premi', text: 'Premi-esperienza e premi materiali scelti con uno scopo, con un costo in stelle suggerito. Aggiungili al tuo scaffale e adattali alla tua famiglia.' },

  'children.profiles': { title: 'Profili dei bambini', text: 'Un profilo per ogni bambino: nome, nickname, età, mascotte e colore. Il numero di bambini che puoi aggiungere dipende dal tuo piano.' },
  'children.age': { title: 'Età del bambino', text: 'L’età determina la fascia (0–3, 3–6, 6–12, 12–18), i suggerimenti sulle abitudini e l’aspetto della schermata del bambino.' },
  'children.leaderboard': { title: 'Classifica', text: 'I nuovi profili sono privati. Un bambino appare nella classifica pubblica solo quando la famiglia attiva la condivisione nelle Impostazioni e lo seleziona, usando un nickname.' },
  'children.ageTheme': { title: 'Aspetto in base all’età', text: 'La schermata del bambino si adatta all’età. Puoi fissare una fascia o mantenere l’aspetto precedente; la tua scelta prevale su quella del bambino.' },
  'children.pairing': { title: 'Codice di connessione', text: 'Ogni bambino ha un codice fisso che apre solo il suo profilo. Scansiona il QR o inserisci il codice sul suo dispositivo. Serve il PIN, se impostato.' },
  'children.regenerate': { title: 'Nuovo codice', text: 'Un nuovo codice rende inutilizzabile quello precedente. Fallo solo se pensi che il codice sia stato divulgato. Serve il PIN.' },
  'children.adjustPoints': { title: 'Aggiungi o togli stelle', text: 'Assegna o detrai stelle (numero positivo o negativo), con una breve motivazione. Serve il PIN. Per riconoscere ciò che esula dalle attività assegnate.' },
  'children.ageBundle': { title: 'Pacchetto iniziale per età', text: 'Carica con un tocco sei attività iniziali adatte all’età del bambino. In seguito puoi modificarle o eliminarle.' },

  'settings.devices': { title: 'Dispositivi dei bambini', text: 'I dispositivi associati, il proprietario e l’ultimo accesso. Revoca subito l’accesso se un dispositivo viene perso o non viene più usato (serve il PIN).' },
  'settings.pwa': { title: 'Installa l’app', text: 'Aggiungi KidHabit alla schermata Home per aprirlo come un’app. Su iPhone: Safari → Condividi → Aggiungi a Home.' },
  'settings.caregivers': { title: 'Persone che si prendono cura dei bambini', text: 'Invita nonni o familiari a vedere i progressi con un link monouso che scade dopo 72 ore. Possono solo visualizzare. Revoca l’invito in qualsiasi momento.' },
  'settings.pause': { title: 'Pausa della famiglia', text: 'Quando la famiglia ha bisogno di riposare, scegli Fai una pausa: i promemoria sui progressi e le serie vengono nascosti, la serie non si interrompe e non perdi stelle o premi. Riprendi quando siete pronti.' },
  'settings.account': { title: 'Dati del cliente', text: 'Nome e telefono per l’assistenza su account e pagamenti. Puoi attivare o disattivare le offerte in qualsiasi momento.' },
  'settings.coupon': { title: 'Codice regalo', text: 'Inserisci un codice regalo per aggiungere giorni di utilizzo. Ogni famiglia lo usa una volta; troppi tentativi errati lo bloccano per alcuni minuti.' },
  'settings.referralCode': { title: 'Codice di invito', text: 'Se ti ha invitato un amico, inserisci il codice di 8 caratteri per ottenere il 10% di sconto sul primo piano annuale. Solo mentre la famiglia è nuova e non ha ancora pagato.' },
  'settings.affiliate': { title: 'Invita amici', text: 'Condividi il tuo link per guadagnare una commissione del 30% quando una nuova famiglia paga. La commissione resta bloccata per 35 giorni; il pagamento minimo è di 200.000 VND e serve il PIN.' },
  'settings.familyData': { title: 'Dati della famiglia', text: 'Scarica una copia JSON dei dati della famiglia. Non contiene il PIN né i dati di pagamento, ma contiene i dati dei tuoi bambini: conservala in privato.' },
  'settings.leaderboardSharing': { title: 'Condivisione della classifica', text: 'Un interruttore per tutta la famiglia, disattivato in origine. Se attivo, compaiono solo i bambini scelti nel profilo, con nickname e senza nome reale o età.' },
  'settings.analytics': { title: 'Misurazione anonima', text: 'Consente misurazioni generali senza nomi né contenuti. Non esiste ancora un punto di raccolta, quindi nulla lascia il dispositivo. Disattivata in origine.' },
  'settings.reminders': { title: 'Promemoria', text: 'Solo per attività o premi in attesa della tua approvazione, mai pubblicità. Puoi consentire le notifiche sul dispositivo e disattivarle quando vuoi.' },
  'settings.theme': { title: 'Aspetto', text: 'Chiaro, scuro o come il dispositivo.' },
  'settings.pin': { title: 'PIN', text: 'Quattro cifre che proteggono l’area genitori. Dopo averlo inserito correttamente, questo browser resta sbloccato per 2 ore. Serve per approvare, revocare dispositivi, pagare, eliminare dati e richiedere il prelievo delle commissioni. Non condividerlo con il bambino.' },

  'payment.plans': { title: 'Piani', text: 'Piano Un Bambino: 29.000 VND al mese (1 bambino), Piano Famiglia · Mensile: 49.000 VND, Piano Famiglia · Annuale: 399.000 VND. Pagamento una tantum, senza rinnovo automatico.' },
  'payment.trial': { title: 'Prova di 7 giorni', text: 'Gratis, senza carta né addebito automatico. Una volta per famiglia.' },
  'payment.memo': { title: 'Causale del bonifico', text: 'Mantieni esattamente l’importo e la causale perché il sistema riconosca il pagamento. Puoi copiare ogni voce oppure scaricare il codice QR.' },
  'payment.activation': { title: 'Quando si attiva il piano', text: 'Non appena il pagamento viene confermato, di solito entro pochi secondi. Se non succede, aspetta qualche minuto e riapri; contatta l’assistenza indicando il codice dell’ordine.' },
};
