'use client';
import { useEffect, useState } from 'react';
import { UserRound } from 'lucide-react';
import { useTranslation } from '@/lib/i18n/context';
import { getAccountProfileCopy } from '@/lib/i18n/account-profile-copy';

export function AccountProfileCard() {
  const { language } = useTranslation();
  const copy = getAccountProfileCopy(language);
  const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [email,setEmail]=useState(''); const [consent,setConsent]=useState(false); const [notice,setNotice]=useState(''); const [coupon,setCoupon]=useState('');
  useEffect(()=>{void fetch('/api/account/profile').then(async r=>{if(!r.ok)return;const body=await r.json() as {profile:{display_name:string;email:string;phone:string|null;marketing_consent:boolean}};setName(body.profile.display_name);setEmail(body.profile.email);setPhone(body.profile.phone??'');setConsent(body.profile.marketing_consent);});},[]);
  const save=async()=>{setNotice(copy.saving);const response=await fetch('/api/account/profile',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({displayName:name,phone,marketingConsent:consent})});setNotice(response.ok?copy.saved:response.status===400?copy.invalidPhone:copy.saveFailed);};
  const redeem=async()=>{const r=await fetch('/api/coupons/redeem',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:coupon})});const b=await r.json() as {error?:string};setNotice(r.ok?copy.redeemed:b.error??copy.redeemFailed);};
  return <section className="space-y-4 rounded-3xl border border-slate-100 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h4 className="flex items-center gap-2 text-sm font-extrabold"><UserRound className="h-4 w-4 text-indigo-600"/>{copy.title}</h4><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">{copy.fullName}<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 font-normal dark:border-zinc-700 dark:bg-zinc-800"/></label><label className="text-sm font-bold">{copy.phone}<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 font-normal dark:border-zinc-700 dark:bg-zinc-800"/></label><label className="text-sm font-bold sm:col-span-2">{copy.email}<input value={email} disabled className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-100 px-3 font-normal text-slate-500 dark:border-zinc-700 dark:bg-zinc-800"/></label></div><label className="flex items-start gap-3 text-sm text-slate-600 dark:text-slate-300"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 h-4 w-4"/><span>{copy.consent}</span></label><div className="flex flex-wrap items-center gap-3"><button type="button" onClick={()=>void save()} className="min-h-11 rounded-xl bg-indigo-600 px-5 text-sm font-bold text-white">{copy.save}</button><input value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} placeholder={copy.coupon} className="min-h-11 rounded-xl border px-3 dark:bg-zinc-800"/><button type="button" onClick={()=>void redeem()} className="min-h-11 rounded-xl border px-4 text-sm font-bold">{copy.redeem}</button>{notice&&<span role="status" className="text-sm text-slate-500">{notice}</span>}</div></section>;
}
