import type { Language } from '@/types';

interface DeviceConnectCopy {
  close: string; connect: string; connecting: string; codeHelp: string; codeLabel: string;
  defaultFamily: string; dialogLabel: string; errorFallback: string; errorRequired: string;
  finish: string; guide: string; guideSteps: [string, string, string]; later: string;
  successBody: string; successSubtitle: string; successTitle: string; subtitle: string; title: string;
  welcomeChild: (name: string) => string; welcomeFamily: (name: string) => string;
}

interface ScannerCopy {
  readonly cameraDenied: string;
  readonly cameraUnavailable: string;
  readonly invalidQr: string;
  readonly manualFallback: string;
  readonly scanQr: string;
  readonly scannerLabel: string;
  readonly useManualCode: string;
}

const C: Record<Language, DeviceConnectCopy> = {
  vi:{close:'Đóng',connect:'🚀 Kết nối ngay',connecting:'Đang kết nối…',codeHelp:'Mã được giữ cố định cho đến khi phụ huynh chọn làm mới',codeLabel:'Mã kết nối của bé',defaultFamily:'Gia đình KidHabit',dialogLabel:'Kết nối thiết bị của bé',errorFallback:'Mã không đúng hoặc chưa được kích hoạt. Vui lòng kiểm tra lại.',errorRequired:'Vui lòng nhập mã kết nối hiển thị trên máy phụ huynh.',finish:'Bắt đầu nhiệm vụ của bé ⭐',guide:'Cách kết nối nhanh và an toàn:',guideSteps:['Mở KidHabit Hero trên thiết bị của phụ huynh.','Vào Chế độ phụ huynh và xem mã riêng của bé.','Quét QR hoặc nhập mã để thiết bị chỉ nhận hồ sơ, nhiệm vụ và phần thưởng của đúng bé này.'],later:'Để sau',successBody:'Thiết bị đã kết nối. Nhiệm vụ và phần thưởng của bé đã sẵn sàng.',successSubtitle:'Thiết bị chỉ được cấp quyền cho bé này',successTitle:'Liên kết thành công!',subtitle:'Quét QR hoặc nhập mã riêng của bé',title:'Bé vào bằng mã gia đình',welcomeChild:(n)=>`Chào mừng bé ${n}! 🌟`,welcomeFamily:(n)=>`Chào mừng đến với ${n}!`},
  en:{close:'Close',connect:'🚀 Connect now',connecting:'Connecting…',codeHelp:'The code stays the same until a parent refreshes it',codeLabel:"Child's connection code",defaultFamily:'KidHabit Family',dialogLabel:"Connect a child's device",errorFallback:'That code is invalid or inactive. Please check it and try again.',errorRequired:"Enter the code shown on the parent's device.",finish:"Start the child's tasks ⭐",guide:'Quick and secure connection:',guideSteps:["Open KidHabit Hero on the parent's device.","Open Parent mode and find this child's code.","Scan the QR or enter the code so this device receives only that child's profile, tasks, and rewards."],later:'Maybe later',successBody:"The device is connected. The child's tasks and rewards are ready.",successSubtitle:'This device can access this child only',successTitle:'Connected successfully!',subtitle:'Scan the QR or enter the child code',title:'Enter a family code',welcomeChild:(n)=>`Welcome, ${n}! 🌟`,welcomeFamily:(n)=>`Welcome to ${n}!`},
  fr:{close:'Fermer',connect:'🚀 Se connecter',connecting:'Connexion…',codeHelp:'Le code reste valable jusqu’à ce qu’un parent le renouvelle',codeLabel:'Code de connexion de l’enfant',defaultFamily:'Famille KidHabit',dialogLabel:'Connecter l’appareil de l’enfant',errorFallback:'Code incorrect ou inactif. Vérifiez-le puis réessayez.',errorRequired:'Saisissez le code affiché sur l’appareil du parent.',finish:'Commencer les missions ⭐',guide:'Connexion rapide et sécurisée :',guideSteps:['Ouvrez KidHabit Hero sur l’appareil du parent.','Ouvrez le mode Parent et trouvez le code de cet enfant.','Scannez le QR ou saisissez le code pour recevoir uniquement son profil, ses missions et ses récompenses.'],later:'Plus tard',successBody:'L’appareil est connecté. Les missions et récompenses sont prêtes.',successSubtitle:'Cet appareil accède uniquement à cet enfant',successTitle:'Connexion réussie !',subtitle:'Scannez le QR ou saisissez le code enfant',title:'Saisir un code famille',welcomeChild:(n)=>`Bienvenue ${n} ! 🌟`,welcomeFamily:(n)=>`Bienvenue dans ${n} !`},
  de:{close:'Schließen',connect:'🚀 Jetzt verbinden',connecting:'Verbindung…',codeHelp:'Der Code bleibt gültig, bis ein Elternteil ihn erneuert',codeLabel:'Verbindungscode des Kindes',defaultFamily:'KidHabit-Familie',dialogLabel:'Kindergerät verbinden',errorFallback:'Der Code ist ungültig oder inaktiv. Bitte prüfe ihn.',errorRequired:'Gib den Code vom Elterngerät ein.',finish:'Kinderaufgaben starten ⭐',guide:'Schnell und sicher verbinden:',guideSteps:['KidHabit Hero auf dem Elterngerät öffnen.','Elternmodus öffnen und den Code dieses Kindes anzeigen.','QR scannen oder Code eingeben, damit dieses Gerät nur die Daten dieses Kindes erhält.'],later:'Später',successBody:'Das Gerät ist verbunden. Aufgaben und Belohnungen sind bereit.',successSubtitle:'Dieses Gerät kann nur auf dieses Kind zugreifen',successTitle:'Erfolgreich verbunden!',subtitle:'QR scannen oder Kindercode eingeben',title:'Familiencode eingeben',welcomeChild:(n)=>`Willkommen, ${n}! 🌟`,welcomeFamily:(n)=>`Willkommen bei ${n}!`},
  it:{close:'Chiudi',connect:'🚀 Connetti ora',connecting:'Connessione…',codeHelp:'Il codice resta valido finché un genitore non lo rinnova',codeLabel:'Codice di connessione del bambino',defaultFamily:'Famiglia KidHabit',dialogLabel:'Connetti il dispositivo del bambino',errorFallback:'Codice errato o non attivo. Controlla e riprova.',errorRequired:'Inserisci il codice mostrato sul dispositivo del genitore.',finish:'Inizia le attività ⭐',guide:'Connessione rapida e sicura:',guideSteps:['Apri KidHabit Hero sul dispositivo del genitore.','Apri la modalità Genitore e trova il codice del bambino.','Scansiona il QR o inserisci il codice per ricevere solo i dati di questo bambino.'],later:'Più tardi',successBody:'Il dispositivo è connesso. Attività e premi sono pronti.',successSubtitle:'Questo dispositivo accede solo a questo bambino',successTitle:'Connessione riuscita!',subtitle:'Scansiona il QR o inserisci il codice',title:'Inserisci il codice famiglia',welcomeChild:(n)=>`Benvenuto, ${n}! 🌟`,welcomeFamily:(n)=>`Benvenuti in ${n}!`},
  es:{close:'Cerrar',connect:'🚀 Conectar ahora',connecting:'Conectando…',codeHelp:'El código sigue activo hasta que un adulto lo renueve',codeLabel:'Código de conexión del niño',defaultFamily:'Familia KidHabit',dialogLabel:'Conectar el dispositivo del niño',errorFallback:'El código no es válido o no está activo. Compruébalo.',errorRequired:'Introduce el código que aparece en el dispositivo del padre o madre.',finish:'Empezar las tareas ⭐',guide:'Conexión rápida y segura:',guideSteps:['Abre KidHabit Hero en el dispositivo del padre o madre.','Abre el modo Padres y busca el código del niño.','Escanea el QR o introduce el código para recibir solo los datos de este niño.'],later:'Más tarde',successBody:'El dispositivo está conectado. Las tareas y recompensas están listas.',successSubtitle:'Este dispositivo solo accede a este niño',successTitle:'¡Conexión completada!',subtitle:'Escanea el QR o introduce el código',title:'Introduce el código familiar',welcomeChild:(n)=>`¡Bienvenido, ${n}! 🌟`,welcomeFamily:(n)=>`¡Bienvenidos a ${n}!`},
  zh:{close:'关闭',connect:'🚀 立即连接',connecting:'正在连接…',codeHelp:'连接码会保持不变，直到家长主动刷新',codeLabel:'孩子的连接码',defaultFamily:'KidHabit 家庭',dialogLabel:'连接孩子的设备',errorFallback:'连接码不正确或未启用，请检查后重试。',errorRequired:'请输入父母设备上显示的连接码。',finish:'开始孩子的任务 ⭐',guide:'快速安全连接：',guideSteps:['在父母设备上打开 KidHabit Hero。','进入家长模式，找到这个孩子的连接码。','扫描二维码或输入连接码，此设备只会接收该孩子的数据。'],later:'稍后',successBody:'设备已连接，孩子的任务和奖励已准备好。',successSubtitle:'此设备只能访问这个孩子',successTitle:'连接成功！',subtitle:'扫描二维码或输入孩子的连接码',title:'输入家庭连接码',welcomeChild:(n)=>`欢迎你，${n}！🌟`,welcomeFamily:(n)=>`欢迎来到${n}！`},
  ja:{close:'閉じる',connect:'🚀 今すぐ連携',connecting:'連携中…',codeHelp:'保護者が更新するまで同じコードを利用できます',codeLabel:'子どもの接続コード',defaultFamily:'KidHabit ファミリー',dialogLabel:'子どもの端末を連携',errorFallback:'コードが正しくないか無効です。確認してください。',errorRequired:'保護者の端末に表示されたコードを入力してください。',finish:'子どものタスクを始める ⭐',guide:'すばやく安全に連携：',guideSteps:['保護者の端末で KidHabit Hero を開きます。','保護者モードでこの子のコードを表示します。','QRを読み取るかコードを入力すると、この子のデータだけが届きます。'],later:'あとで',successBody:'端末を連携しました。タスクと報酬の準備ができています。',successSubtitle:'この端末はこの子だけにアクセスできます',successTitle:'連携できました！',subtitle:'QRを読み取るか接続コードを入力',title:'家族コードを入力',welcomeChild:(n)=>`ようこそ、${n}！🌟`,welcomeFamily:(n)=>`${n}へようこそ！`},
  ko:{close:'닫기',connect:'🚀 지금 연결',connecting:'연결 중…',codeHelp:'부모가 새로 만들기 전까지 같은 코드를 사용할 수 있습니다',codeLabel:'아이 연결 코드',defaultFamily:'KidHabit 가족',dialogLabel:'아이 기기 연결',errorFallback:'코드가 올바르지 않거나 활성화되지 않았습니다. 확인해 주세요.',errorRequired:'부모 기기에 표시된 연결 코드를 입력해 주세요.',finish:'아이 과제 시작하기 ⭐',guide:'빠르고 안전하게 연결하기:',guideSteps:['부모 기기에서 KidHabit Hero를 여세요.','부모 모드에서 이 아이의 코드를 확인하세요.','QR을 스캔하거나 코드를 입력하면 이 아이의 데이터만 받습니다.'],later:'나중에',successBody:'기기가 연결되었습니다. 아이의 과제와 보상이 준비됐어요.',successSubtitle:'이 기기는 해당 아이에게만 접근합니다',successTitle:'연결 완료!',subtitle:'QR 스캔 또는 아이 코드 입력',title:'가족 코드 입력',welcomeChild:(n)=>`${n}, 환영해요! 🌟`,welcomeFamily:(n)=>`${n}에 오신 것을 환영합니다!`},
};

const S: Record<Language, ScannerCopy> = {
  vi:{cameraDenied:'KidHabit chưa được phép dùng camera.',cameraUnavailable:'Thiết bị hoặc trình duyệt này không hỗ trợ quét camera.',invalidQr:'Đây không phải mã QR kết nối KidHabit hợp lệ.',manualFallback:'Bạn vẫn có thể nhập mã bên dưới.',scanQr:'Quét QR',scannerLabel:'Máy quét mã QR kết nối',useManualCode:'Nhập mã thủ công'},
  en:{cameraDenied:'KidHabit does not have camera permission.',cameraUnavailable:'This device or browser does not support camera scanning.',invalidQr:'This is not a valid KidHabit connection QR.',manualFallback:'You can still enter the code below.',scanQr:'Scan QR',scannerLabel:'Connection QR scanner',useManualCode:'Enter code manually'},
  fr:{cameraDenied:'KidHabit n’a pas accès à la caméra.',cameraUnavailable:'Cet appareil ou navigateur ne permet pas le scan.',invalidQr:'Ce QR de connexion KidHabit n’est pas valide.',manualFallback:'Vous pouvez toujours saisir le code.',scanQr:'Scanner le QR',scannerLabel:'Scanner QR de connexion',useManualCode:'Saisir le code'},
  de:{cameraDenied:'KidHabit hat keine Kameraberechtigung.',cameraUnavailable:'Dieses Gerät oder dieser Browser unterstützt keinen Kamerascan.',invalidQr:'Dies ist kein gültiger KidHabit-Verbindungs-QR.',manualFallback:'Du kannst den Code weiterhin eingeben.',scanQr:'QR scannen',scannerLabel:'Verbindungs-QR-Scanner',useManualCode:'Code eingeben'},
  it:{cameraDenied:'KidHabit non ha il permesso di usare la fotocamera.',cameraUnavailable:'Questo dispositivo o browser non supporta la scansione.',invalidQr:'Questo QR di connessione KidHabit non è valido.',manualFallback:'Puoi comunque inserire il codice.',scanQr:'Scansiona QR',scannerLabel:'Scanner QR di connessione',useManualCode:'Inserisci il codice'},
  es:{cameraDenied:'KidHabit no tiene permiso para usar la cámara.',cameraUnavailable:'Este dispositivo o navegador no permite escanear con la cámara.',invalidQr:'Este QR de conexión KidHabit no es válido.',manualFallback:'Aún puedes introducir el código.',scanQr:'Escanear QR',scannerLabel:'Escáner QR de conexión',useManualCode:'Introducir código'},
  zh:{cameraDenied:'KidHabit 没有相机权限。',cameraUnavailable:'此设备或浏览器不支持相机扫描。',invalidQr:'这不是有效的 KidHabit 连接二维码。',manualFallback:'你仍可手动输入连接码。',scanQr:'扫描二维码',scannerLabel:'连接二维码扫描器',useManualCode:'手动输入连接码'},
  ja:{cameraDenied:'KidHabit にカメラの使用が許可されていません。',cameraUnavailable:'この端末またはブラウザはカメラ読み取りに対応していません。',invalidQr:'有効な KidHabit 接続QRではありません。',manualFallback:'コードを手入力できます。',scanQr:'QRをスキャン',scannerLabel:'接続QRスキャナー',useManualCode:'コードを手入力'},
  ko:{cameraDenied:'KidHabit에 카메라 권한이 없습니다.',cameraUnavailable:'이 기기나 브라우저는 카메라 스캔을 지원하지 않습니다.',invalidQr:'올바른 KidHabit 연결 QR이 아닙니다.',manualFallback:'연결 코드를 직접 입력할 수 있습니다.',scanQr:'QR 스캔',scannerLabel:'연결 QR 스캐너',useManualCode:'코드 직접 입력'},
};

export function getDeviceConnectCopy(language: Language): DeviceConnectCopy & ScannerCopy {
  return { ...C[language], ...S[language] };
}
