import type { Language } from '@/types';
import type { JournalCsvLabels } from '@/lib/child-journal';

type JournalCopy = {
  readonly childTitle: string;
  readonly childDescription: string;
  readonly inputLabel: string;
  readonly placeholder: string;
  readonly save: string;
  readonly saving: string;
  readonly saved: string;
  readonly error: string;
  readonly privacy: string;
  readonly parentTitle: string;
  readonly parentDescription: string;
  readonly empty: string;
  readonly export: string;
  readonly csv: JournalCsvLabels;
  readonly count: (current: number, maximum: number) => string;
};

export const journalCopy: Record<Language, JournalCopy> = {
  vi: { childTitle: 'Một điều con muốn ghi nhớ', childDescription: 'Viết một câu ngắn về điều con đã học, đã làm tốt hoặc muốn thử lại ngày mai.', inputLabel: 'Điều con muốn ghi nhớ hôm nay', placeholder: 'Hôm nay con đã…', save: 'Lưu nhật ký', saving: 'Đang lưu…', saved: 'Đã lưu cho hôm nay.', error: 'Chưa lưu được. Con thử lại nhé.', privacy: 'Chỉ con và phụ huynh xem được. Nội dung không dùng để đo lường.', parentTitle: 'Nhật ký một câu của con', parentDescription: 'Xem lại những điều con chủ động ghi nhớ theo từng ngày.', empty: 'Chưa có dòng nhật ký nào.', export: 'Xuất nhật ký', csv: { date: 'Ngày', childName: 'Tên bé', reflection: 'Điều con muốn ghi nhớ' }, count: (current, maximum) => `${current}/${maximum} ký tự` },
  en: { childTitle: 'One thing I want to remember', childDescription: 'Write one short sentence about what you learned, did well, or want to try again tomorrow.', inputLabel: 'What I want to remember today', placeholder: 'Today I…', save: 'Save journal', saving: 'Saving…', saved: 'Saved for today.', error: 'Could not save. Please try again.', privacy: 'Only you and your parent can see this. Journal text is never used for measurement.', parentTitle: "Your child's one-sentence journal", parentDescription: 'Review what your child chose to remember each day.', empty: 'No journal entries yet.', export: 'Export journal', csv: { date: 'Date', childName: 'Child', reflection: 'Reflection' }, count: (current, maximum) => `${current}/${maximum} characters` },
  fr: { childTitle: 'Une chose à retenir', childDescription: 'Écris une courte phrase sur ce que tu as appris, bien fait ou veux réessayer demain.', inputLabel: "Ce que je veux retenir aujourd'hui", placeholder: "Aujourd'hui, j'ai…", save: 'Enregistrer', saving: 'Enregistrement…', saved: "Enregistré pour aujourd'hui.", error: 'Enregistrement impossible. Réessaie.', privacy: "Seuls toi et tes parents pouvez voir ce texte. Il n'est jamais utilisé pour les mesures.", parentTitle: "Journal en une phrase de l'enfant", parentDescription: "Relisez ce que votre enfant a choisi de retenir chaque jour.", empty: 'Aucune note pour le moment.', export: 'Exporter le journal', csv: { date: 'Date', childName: 'Enfant', reflection: 'Réflexion' }, count: (current, maximum) => `${current}/${maximum} caractères` },
  de: { childTitle: 'Eine Sache, die ich behalten möchte', childDescription: 'Schreibe einen kurzen Satz darüber, was du gelernt, gut gemacht oder morgen erneut versuchen möchtest.', inputLabel: 'Was ich heute behalten möchte', placeholder: 'Heute habe ich…', save: 'Tagebuch speichern', saving: 'Wird gespeichert…', saved: 'Für heute gespeichert.', error: 'Speichern nicht möglich. Bitte erneut versuchen.', privacy: 'Nur du und deine Eltern können den Text sehen. Er wird nie für Messungen verwendet.', parentTitle: 'Ein-Satz-Tagebuch des Kindes', parentDescription: 'Sehen Sie, was Ihr Kind sich jeden Tag merken wollte.', empty: 'Noch keine Einträge.', export: 'Tagebuch exportieren', csv: { date: 'Datum', childName: 'Kind', reflection: 'Gedanke' }, count: (current, maximum) => `${current}/${maximum} Zeichen` },
  it: { childTitle: 'Una cosa che voglio ricordare', childDescription: 'Scrivi una breve frase su ciò che hai imparato, fatto bene o vuoi riprovare domani.', inputLabel: 'Ciò che voglio ricordare oggi', placeholder: 'Oggi ho…', save: 'Salva diario', saving: 'Salvataggio…', saved: 'Salvato per oggi.', error: 'Impossibile salvare. Riprova.', privacy: 'Solo tu e i tuoi genitori potete vederlo. Il testo non viene usato per le misurazioni.', parentTitle: 'Diario in una frase del bambino', parentDescription: 'Rileggi ciò che tuo figlio ha scelto di ricordare ogni giorno.', empty: 'Nessuna nota per ora.', export: 'Esporta diario', csv: { date: 'Data', childName: 'Bambino', reflection: 'Riflessione' }, count: (current, maximum) => `${current}/${maximum} caratteri` },
  es: { childTitle: 'Algo que quiero recordar', childDescription: 'Escribe una frase corta sobre lo que aprendiste, hiciste bien o quieres intentar de nuevo mañana.', inputLabel: 'Lo que quiero recordar hoy', placeholder: 'Hoy he…', save: 'Guardar diario', saving: 'Guardando…', saved: 'Guardado para hoy.', error: 'No se pudo guardar. Inténtalo de nuevo.', privacy: 'Solo tú y tus padres pueden verlo. El texto no se usa para mediciones.', parentTitle: 'Diario de una frase del niño', parentDescription: 'Revisa lo que tu hijo eligió recordar cada día.', empty: 'Todavía no hay notas.', export: 'Exportar diario', csv: { date: 'Fecha', childName: 'Niño', reflection: 'Reflexión' }, count: (current, maximum) => `${current}/${maximum} caracteres` },
  zh: { childTitle: '我想记住的一件事', childDescription: '用一句简短的话写下今天学到的、做得好的，或明天想再试一次的事。', inputLabel: '我今天想记住的事', placeholder: '今天我…', save: '保存日记', saving: '正在保存…', saved: '今天的内容已保存。', error: '暂时无法保存，请再试一次。', privacy: '只有你和家长可以查看，日记内容不会用于数据统计。', parentTitle: '孩子的一句话日记', parentDescription: '查看孩子每天主动记录的事情。', empty: '还没有日记内容。', export: '导出日记', csv: { date: '日期', childName: '孩子', reflection: '记录' }, count: (current, maximum) => `${current}/${maximum} 字` },
  ja: { childTitle: '覚えておきたいことを一つ', childDescription: '学んだこと、できたこと、明日もう一度やってみたいことを短い一文で書こう。', inputLabel: '今日覚えておきたいこと', placeholder: '今日は…', save: '日記を保存', saving: '保存中…', saved: '今日の分を保存しました。', error: '保存できませんでした。もう一度試してください。', privacy: 'あなたと保護者だけが見られます。日記の内容は計測に使いません。', parentTitle: '子どもの一文日記', parentDescription: '子どもが毎日自分で残した振り返りを確認できます。', empty: 'まだ日記はありません。', export: '日記を書き出す', csv: { date: '日付', childName: '子ども', reflection: '振り返り' }, count: (current, maximum) => `${current}/${maximum}文字` },
  ko: { childTitle: '기억하고 싶은 한 가지', childDescription: '배운 점, 잘한 점, 내일 다시 해 보고 싶은 일을 짧은 한 문장으로 써 보세요.', inputLabel: '오늘 기억하고 싶은 것', placeholder: '오늘 나는…', save: '일기 저장', saving: '저장 중…', saved: '오늘 기록을 저장했어요.', error: '저장하지 못했어요. 다시 시도해 주세요.', privacy: '아이와 보호자만 볼 수 있으며, 일기 내용은 측정에 사용하지 않습니다.', parentTitle: '아이의 한 문장 일기', parentDescription: '아이가 매일 스스로 남긴 내용을 확인하세요.', empty: '아직 기록이 없습니다.', export: '일기 내보내기', csv: { date: '날짜', childName: '아이', reflection: '기록' }, count: (current, maximum) => `${current}/${maximum}자` },
};
