import type { AgeStage, Language } from '@/types';

interface KidDashboardCopy {
  ageUnit: string; defaultReward: string; guide: string; handbook: string; infantDescription: string;
  infantJournal: (name: string) => string; infantStage: string; infantTag: string; nextDay: string;
  parentRole: string; portraitPractice: string; previousDay: string; setGoal: string;
  stageLabels: Record<AgeStage, string>;
}

const C: Record<Language, KidDashboardCopy> = {
  vi: { ageUnit:'tuổi',defaultReward:'Phần thưởng',guide:'Tra cứu',handbook:'Xem cẩm nang',infantDescription:'Bé quan sát và ghi nhớ từng cử chỉ của ba mẹ. Hãy thực hành 16 hành động nhân cách mỗi ngày để làm gương cho con.',infantJournal:(n)=>`🍼 Nhật ký làm gương của ba mẹ cho ${n}`,infantStage:'Giai đoạn Thấm nhuần môi trường (0–3 tuổi)',infantTag:'Ba mẹ làm gương',nextDay:'Ngày tiếp theo',parentRole:'Ba mẹ làm gương',portraitPractice:'Nuôi dưỡng 16 phẩm chất và 7 cách trao tặng mỗi ngày.',previousDay:'Ngày trước',setGoal:'Đặt làm mục tiêu',stageLabels:{'0-3':'Thấm nhuần môi trường (0–3 tuổi)','3-6':'Nền tảng thói quen (3–6 tuổi)','6-12':'Kỹ năng & trách nhiệm (6–12 tuổi)','12-18':'Tự lập & khát vọng (12–18 tuổi)'}},
  en: { ageUnit:'years old',defaultReward:'Reward',guide:'Explore',handbook:'View guide',infantDescription:'Young children absorb every gesture they see. Practice the 16 character-building actions each day to model them clearly.',infantJournal:(n)=>`🍼 Parent role-model journal for ${n}`,infantStage:'Environmental absorption stage (ages 0–3)',infantTag:'Parents model first',nextDay:'Next day',parentRole:'Parent role model',portraitPractice:'Nurture 16 character strengths and 7 ways of giving every day.',previousDay:'Previous day',setGoal:'Set as goal',stageLabels:{'0-3':'Early exploration (ages 0–3)','3-6':'Habit foundations (ages 3–6)','6-12':'Skills & responsibility (ages 6–12)','12-18':'Independence & purpose (ages 12–18)'}},
  fr: { ageUnit:'ans',defaultReward:'Récompense',guide:'Découvrir',handbook:'Voir le guide',infantDescription:'Les tout-petits absorbent chaque geste observé. Pratiquez chaque jour les 16 actions de caractère pour leur montrer l’exemple.',infantJournal:(n)=>`🍼 Journal des parents modèles pour ${n}`,infantStage:'Étape d’imprégnation du milieu (0–3 ans)',infantTag:'Les parents montrent l’exemple',nextDay:'Jour suivant',parentRole:'Parent modèle',portraitPractice:'Cultivez chaque jour 16 forces de caractère et 7 façons de donner.',previousDay:'Jour précédent',setGoal:'Définir comme objectif',stageLabels:{'0-3':'Premières découvertes (0–3 ans)','3-6':'Bases des habitudes (3–6 ans)','6-12':'Compétences et responsabilité (6–12 ans)','12-18':'Autonomie et projet (12–18 ans)'}},
  de: { ageUnit:'Jahre alt',defaultReward:'Belohnung',guide:'Entdecken',handbook:'Ratgeber ansehen',infantDescription:'Kleinkinder nehmen jede beobachtete Geste auf. Lebe die 16 Charakterhandlungen täglich vor, damit sie ein klares Beispiel sehen.',infantJournal:(n)=>`🍼 Vorbild-Tagebuch der Eltern für ${n}`,infantStage:'Phase der Umgebungsprägung (0–3 Jahre)',infantTag:'Eltern leben es vor',nextDay:'Nächster Tag',parentRole:'Eltern als Vorbild',portraitPractice:'Fördere täglich 16 Charakterstärken und 7 Arten des Gebens.',previousDay:'Vorheriger Tag',setGoal:'Als Ziel festlegen',stageLabels:{'0-3':'Frühes Entdecken (0–3 Jahre)','3-6':'Grundlagen der Gewohnheiten (3–6 Jahre)','6-12':'Fähigkeiten & Verantwortung (6–12 Jahre)','12-18':'Selbstständigkeit & Ziele (12–18 Jahre)'}},
  it: { ageUnit:'anni',defaultReward:'Premio',guide:'Scopri',handbook:'Vedi la guida',infantDescription:'I più piccoli assorbono ogni gesto che osservano. Pratica ogni giorno le 16 azioni del carattere per dare un esempio chiaro.',infantJournal:(n)=>`🍼 Diario dei genitori modello per ${n}`,infantStage:'Fase di assorbimento dell’ambiente (0–3 anni)',infantTag:'I genitori danno l’esempio',nextDay:'Giorno successivo',parentRole:'Genitore modello',portraitPractice:'Coltiva ogni giorno 16 punti di forza e 7 modi di donare.',previousDay:'Giorno precedente',setGoal:'Imposta come obiettivo',stageLabels:{'0-3':'Prime scoperte (0–3 anni)','3-6':'Basi delle abitudini (3–6 anni)','6-12':'Capacità e responsabilità (6–12 anni)','12-18':'Autonomia e obiettivi (12–18 anni)'}},
  es: { ageUnit:'años',defaultReward:'Recompensa',guide:'Explorar',handbook:'Ver guía',infantDescription:'Los más pequeños absorben cada gesto que observan. Practica a diario las 16 acciones de carácter para darles un ejemplo claro.',infantJournal:(n)=>`🍼 Diario de padres modelo para ${n}`,infantStage:'Etapa de absorción del entorno (0–3 años)',infantTag:'Los padres dan ejemplo',nextDay:'Día siguiente',parentRole:'Padres como modelo',portraitPractice:'Cultiva cada día 16 fortalezas de carácter y 7 formas de dar.',previousDay:'Día anterior',setGoal:'Fijar como objetivo',stageLabels:{'0-3':'Primeros descubrimientos (0–3 años)','3-6':'Bases de los hábitos (3–6 años)','6-12':'Habilidades y responsabilidad (6–12 años)','12-18':'Autonomía y propósito (12–18 años)'}},
  zh: { ageUnit:'岁',defaultReward:'奖励',guide:'查看',handbook:'查看指南',infantDescription:'幼儿会吸收看到的每一个动作。父母每天践行 16 项品格行动，用清晰的榜样影响孩子。',infantJournal:(n)=>`🍼 ${n}的父母榜样日志`,infantStage:'环境吸收阶段（0–3 岁）',infantTag:'父母先做榜样',nextDay:'下一天',parentRole:'父母榜样',portraitPractice:'每天培养 16 项品格优势和 7 种给予方式。',previousDay:'上一天',setGoal:'设为目标',stageLabels:{'0-3':'早期探索（0–3 岁）','3-6':'习惯基础（3–6 岁）','6-12':'能力与责任（6–12 岁）','12-18':'独立与目标（12–18 岁）'}},
  ja: { ageUnit:'歳',defaultReward:'ごほうび',guide:'見る',handbook:'ガイドを見る',infantDescription:'幼い子どもは目にした仕草を吸収します。16の人格づくりの行動を毎日実践し、分かりやすい手本を示しましょう。',infantJournal:(n)=>`🍼 ${n}の保護者お手本日記`,infantStage:'環境吸収期（0～3歳）',infantTag:'保護者がまずお手本に',nextDay:'次の日',parentRole:'保護者のお手本',portraitPractice:'16の人格的強みと7つの与え方を毎日育みます。',previousDay:'前の日',setGoal:'目標に設定',stageLabels:{'0-3':'初期の探索（0～3歳）','3-6':'習慣の基礎（3～6歳）','6-12':'力と責任（6～12歳）','12-18':'自立と目標（12～18歳）'}},
  ko: { ageUnit:'세',defaultReward:'보상',guide:'살펴보기',handbook:'가이드 보기',infantDescription:'어린아이는 눈으로 본 모든 행동을 흡수합니다. 매일 16가지 인성 행동을 실천해 분명한 본보기가 되어 주세요.',infantJournal:(n)=>`🍼 ${n}을 위한 부모 본보기 일지`,infantStage:'환경 흡수 단계(0~3세)',infantTag:'부모가 먼저 본보기',nextDay:'다음 날',parentRole:'부모 본보기',portraitPractice:'매일 16가지 인성 강점과 7가지 나눔 방법을 길러요.',previousDay:'이전 날',setGoal:'목표로 설정',stageLabels:{'0-3':'초기 탐색(0~3세)','3-6':'습관의 기초(3~6세)','6-12':'역량과 책임(6~12세)','12-18':'자립과 목표(12~18세)'}},
};

export function getKidDashboardCopy(language: Language): KidDashboardCopy { return C[language]; }
