import type { Language } from '@/types';

interface LandingUiCopy {
  backupInvalid:string; backupReadError:string; brushTeeth:string; childCodeButton:string; childCodeTitle:string;
  doneCount:(done:number,total:number)=>string; exploreJourney:string; gentleStart:string; habitCount:(count:number)=>string; iceCream:string;
  makeBed:string; meaning:string; mockChildName:string; noPlanning:string; oneTap:string; packBag:string;
  pillar:(index:number)=>string; practiceTools:string; readBooks:string; rewardStore:string;
  streak:(days:number)=>string; taskCount:(done:number,total:number)=>string; weekendMovie:string;
}

const C: Record<Language, LandingUiCopy> = {
  vi:{backupInvalid:'File sao lưu không hợp lệ. Dữ liệu hiện tại không bị thay đổi.',backupReadError:'Không thể đọc file sao lưu. Vui lòng thử lại.',brushTeeth:'Đánh răng 2 phút',childCodeButton:'Bé vào bằng mã',childCodeTitle:'Bé nhập mã gia đình từ máy ba mẹ',doneCount:(d,t)=>`${d}/${t} đã xong`,exploreJourney:'Khám phá lộ trình này',gentleStart:'Khởi đầu nhẹ nhàng',habitCount:(n)=>`${n} thói quen tiêu biểu`,iceCream:'Ăn kem cùng ba mẹ',makeBed:'Tự gấp chăn mền',meaning:'Ý nghĩa chuyển hóa với con',mockChildName:'Bé Minh An (Sư Tử Dũng Cảm)',noPlanning:'Không cần tốn công nghĩ việc:',oneTap:'Áp dụng 1 chạm vào bảng nhiệm vụ',packBag:'Cất cặp sách gọn gàng',pillar:(n)=>`Trụ cột #${n}/8`,practiceTools:'Công cụ hỗ trợ thực hành',readBooks:'Đọc sách 20 phút',rewardStore:'Kho quà',streak:(n)=>`Chuỗi ${n} ngày liên tiếp`,taskCount:(d,t)=>`${d}/${t} nhiệm vụ`,weekendMovie:'Xem phim cuối tuần'},
  en:{backupInvalid:'This backup file is invalid. Your current data was not changed.',backupReadError:'Could not read the backup file. Please try again.',brushTeeth:'Brush teeth for 2 minutes',childCodeButton:'Enter child code',childCodeTitle:'Enter the family code from a parent device',doneCount:(d,t)=>`${d}/${t} done`,exploreJourney:'Explore this journey',gentleStart:'A gentle start',habitCount:(n)=>`${n} featured habits`,iceCream:'Ice cream with parents',makeBed:'Make the bed independently',meaning:'How this helps your child grow',mockChildName:'Minh An (Brave Lion)',noPlanning:'No need to plan every task:',oneTap:'Add to the task board in one tap',packBag:'Put the school bag away neatly',pillar:(n)=>`Pillar #${n}/8`,practiceTools:'Tools that support daily practice',readBooks:'Read for 20 minutes',rewardStore:'Reward store',streak:(n)=>`${n}-day streak`,taskCount:(d,t)=>`${d}/${t} tasks`,weekendMovie:'Weekend movie'},
  fr:{backupInvalid:'Ce fichier de sauvegarde est invalide. Vos données actuelles n’ont pas été modifiées.',backupReadError:'Impossible de lire la sauvegarde. Réessayez.',brushTeeth:'Se brosser les dents pendant 2 minutes',childCodeButton:'Saisir le code enfant',childCodeTitle:'Saisissez le code familial de l’appareil du parent',doneCount:(d,t)=>`${d}/${t} terminées`,exploreJourney:'Découvrir ce parcours',gentleStart:'Un départ en douceur',habitCount:(n)=>`${n} habitudes présentées`,iceCream:'Une glace avec les parents',makeBed:'Faire son lit seul',meaning:'Comment cela aide votre enfant à grandir',mockChildName:'Minh An (Lion courageux)',noPlanning:'Plus besoin de tout planifier :',oneTap:'Ajouter au tableau en un geste',packBag:'Ranger soigneusement le cartable',pillar:(n)=>`Pilier n°${n}/8`,practiceTools:'Outils pour la pratique quotidienne',readBooks:'Lire pendant 20 minutes',rewardStore:'Boutique de récompenses',streak:(n)=>`Série de ${n} jours`,taskCount:(d,t)=>`${d}/${t} missions`,weekendMovie:'Film du week-end'},
  de:{backupInvalid:'Diese Sicherungsdatei ist ungültig. Deine aktuellen Daten wurden nicht verändert.',backupReadError:'Sicherungsdatei konnte nicht gelesen werden. Bitte erneut versuchen.',brushTeeth:'2 Minuten Zähne putzen',childCodeButton:'Kindercode eingeben',childCodeTitle:'Familiencode vom Elterngerät eingeben',doneCount:(d,t)=>`${d}/${t} erledigt`,exploreJourney:'Diese Reise entdecken',gentleStart:'Sanft anfangen',habitCount:(n)=>`${n} Beispielgewohnheiten`,iceCream:'Eis mit den Eltern',makeBed:'Das Bett selbst machen',meaning:'So unterstützt es die Entwicklung',mockChildName:'Minh An (Mutiger Löwe)',noPlanning:'Keine Aufgabenplanung nötig:',oneTap:'Mit einem Tipp zur Aufgabenliste',packBag:'Schultasche ordentlich wegräumen',pillar:(n)=>`Säule ${n}/8`,practiceTools:'Hilfen für die tägliche Praxis',readBooks:'20 Minuten lesen',rewardStore:'Belohnungsladen',streak:(n)=>`${n}-Tage-Serie`,taskCount:(d,t)=>`${d}/${t} Aufgaben`,weekendMovie:'Wochenendfilm'},
  it:{backupInvalid:'Il file di backup non è valido. I dati attuali non sono stati modificati.',backupReadError:'Impossibile leggere il backup. Riprova.',brushTeeth:'Lavarsi i denti per 2 minuti',childCodeButton:'Inserisci codice bambino',childCodeTitle:'Inserisci il codice famiglia dal dispositivo del genitore',doneCount:(d,t)=>`${d}/${t} completate`,exploreJourney:'Esplora questo percorso',gentleStart:'Un inizio graduale',habitCount:(n)=>`${n} abitudini in evidenza`,iceCream:'Gelato con i genitori',makeBed:'Rifare il letto in autonomia',meaning:'Come aiuta tuo figlio a crescere',mockChildName:'Minh An (Leone coraggioso)',noPlanning:'Non serve pianificare tutto:',oneTap:'Aggiungi alla bacheca con un tocco',packBag:'Riporre lo zaino in ordine',pillar:(n)=>`Pilastro ${n}/8`,practiceTools:'Strumenti per la pratica quotidiana',readBooks:'Leggere per 20 minuti',rewardStore:'Negozio premi',streak:(n)=>`Serie di ${n} giorni`,taskCount:(d,t)=>`${d}/${t} attività`,weekendMovie:'Film del fine settimana'},
  es:{backupInvalid:'El archivo de copia no es válido. Tus datos actuales no cambiaron.',backupReadError:'No se pudo leer la copia. Inténtalo de nuevo.',brushTeeth:'Cepillarse los dientes durante 2 minutos',childCodeButton:'Introducir código infantil',childCodeTitle:'Introduce el código familiar del dispositivo de los padres',doneCount:(d,t)=>`${d}/${t} completadas`,exploreJourney:'Explorar este recorrido',gentleStart:'Un comienzo gradual',habitCount:(n)=>`${n} hábitos destacados`,iceCream:'Helado con los padres',makeBed:'Hacer la cama sin ayuda',meaning:'Cómo ayuda a crecer a tu hijo',mockChildName:'Minh An (León valiente)',noPlanning:'Sin planificar cada tarea:',oneTap:'Añadir al tablero con un toque',packBag:'Guardar la mochila ordenadamente',pillar:(n)=>`Pilar ${n}/8`,practiceTools:'Herramientas para la práctica diaria',readBooks:'Leer durante 20 minutos',rewardStore:'Tienda de recompensas',streak:(n)=>`Racha de ${n} días`,taskCount:(d,t)=>`${d}/${t} tareas`,weekendMovie:'Película de fin de semana'},
  zh:{backupInvalid:'备份文件无效，当前数据未被更改。',backupReadError:'无法读取备份文件，请重试。',brushTeeth:'刷牙 2 分钟',childCodeButton:'输入孩子代码',childCodeTitle:'输入家长设备上的家庭码',doneCount:(d,t)=>`已完成 ${d}/${t}`,exploreJourney:'探索此成长旅程',gentleStart:'轻松开始',habitCount:(n)=>`${n} 个精选习惯`,iceCream:'和父母一起吃冰淇淋',makeBed:'独立整理床铺',meaning:'它如何帮助孩子成长',mockChildName:'明安（勇敢的小狮子）',noPlanning:'无需逐项规划：',oneTap:'一键加入任务板',packBag:'整齐收好书包',pillar:(n)=>`成长支柱 ${n}/8`,practiceTools:'每日实践辅助工具',readBooks:'阅读 20 分钟',rewardStore:'奖励商店',streak:(n)=>`连续 ${n} 天`,taskCount:(d,t)=>`${d}/${t} 项任务`,weekendMovie:'周末电影'},
  ja:{backupInvalid:'バックアップファイルが無効です。現在のデータは変更されていません。',backupReadError:'バックアップを読み込めませんでした。もう一度お試しください。',brushTeeth:'2分間歯を磨く',childCodeButton:'子どもコードを入力',childCodeTitle:'保護者の端末に表示された家族コードを入力',doneCount:(d,t)=>`${d}/${t} 完了`,exploreJourney:'このプランを見る',gentleStart:'無理なく始める',habitCount:(n)=>`注目の習慣 ${n} 個`,iceCream:'保護者とアイスを食べる',makeBed:'自分でベッドを整える',meaning:'子どもの成長につながる理由',mockChildName:'ミン・アン（勇敢なライオン）',noPlanning:'毎日の内容を考える手間なし：',oneTap:'ワンタップでタスク表に追加',packBag:'ランドセルをきれいに片付ける',pillar:(n)=>`成長の柱 ${n}/8`,practiceTools:'毎日の実践を支えるツール',readBooks:'20分読書する',rewardStore:'ごほうびストア',streak:(n)=>`${n}日連続`,taskCount:(d,t)=>`${d}/${t} タスク`,weekendMovie:'週末の映画'},
  ko:{backupInvalid:'백업 파일이 올바르지 않습니다. 현재 데이터는 변경되지 않았습니다.',backupReadError:'백업 파일을 읽지 못했습니다. 다시 시도하세요.',brushTeeth:'2분 동안 양치하기',childCodeButton:'아이 코드 입력',childCodeTitle:'부모 기기의 가족 코드를 입력하세요',doneCount:(d,t)=>`${d}/${t} 완료`,exploreJourney:'이 여정 살펴보기',gentleStart:'부담 없이 시작하기',habitCount:(n)=>`대표 습관 ${n}개`,iceCream:'부모님과 아이스크림 먹기',makeBed:'스스로 침대 정리하기',meaning:'아이의 성장에 도움이 되는 이유',mockChildName:'민안(용감한 사자)',noPlanning:'매번 할 일을 고민할 필요 없이:',oneTap:'한 번에 할 일 보드에 추가',packBag:'책가방을 깔끔하게 정리하기',pillar:(n)=>`성장 기둥 ${n}/8`,practiceTools:'매일의 실천을 돕는 도구',readBooks:'20분 독서하기',rewardStore:'보상 상점',streak:(n)=>`${n}일 연속`,taskCount:(d,t)=>`${d}/${t} 할 일`,weekendMovie:'주말 영화'},
};

export function getLandingUiCopy(language: Language): LandingUiCopy { return C[language]; }
