import type { AgeStage, Language } from '@/types';

type ParentRole = 'mother' | 'father' | 'grandparent' | 'guardian';

interface StageCopy {
  title: string;
  subtitle: string;
  summary: string;
  habitTitles: string[];
}

interface OnboardingCopy {
  ageLabel: string;
  ageUnit: string;
  autoLoad: string;
  back: string;
  childNameLabel: string;
  childNamePlaceholder: string;
  childNameRequired: string;
  close: string;
  complete: string;
  consent: string;
  consentRequired: string;
  contactHelp: string;
  contactLabel: string;
  contactPlaceholder: string;
  dialogLabel: string;
  familyRoleLabel: string;
  luckyMascot: (avatar: string) => string;
  nicknameLabel: string;
  nicknamePlaceholder: string;
  nicknamePrefix: string;
  parentNameLabel: string;
  parentNamePlaceholder: string;
  parentNameRequired: string;
  philosophyBody: string;
  philosophyTitle: string;
  previewBundle: (stage: string) => string;
  roles: Record<ParentRole, string>;
  saveError: string;
  saving: string;
  stageLabels: Record<AgeStage, string>;
  stages: Record<AgeStage, StageCopy>;
  stepOne: string;
  stepTwo: string;
  title: string;
  continue: string;
}

const COPY: Record<Language, OnboardingCopy> = {
  vi: {
    ageLabel:'Độ tuổi của bé hiện tại:',ageUnit:'tuổi',autoLoad:'Tự động nạp mẫu',back:'Quay lại',childNameLabel:'Họ và Tên bé *',childNamePlaceholder:'Ví dụ: Nguyễn Minh An…',childNameRequired:'Vui lòng nhập tên của bé yêu!',close:'Đóng',complete:'Hoàn Tất & Bắt Đầu Rèn Luyện',consent:'Tôi là cha mẹ/người giám hộ hợp pháp và đồng ý để KidHabit lưu dữ liệu hồ sơ, thói quen và tiến độ của bé nhằm cung cấp ứng dụng. Bảng xếp hạng công khai mặc định tắt và chỉ bật khi tôi chủ động chọn.',consentRequired:'Vui lòng xác nhận quyền quản lý dữ liệu của bé trước khi tiếp tục.',contactHelp:'Dữ liệu được bảo mật an toàn, dùng để đồng bộ lộ trình trên nhiều thiết bị.',contactLabel:'Số điện thoại hoặc Email (Tùy chọn)',contactPlaceholder:'Nhập để lưu trữ và nhận cẩm nang nuôi dạy con…',dialogLabel:'Thiết lập gia đình',familyRoleLabel:'Vai trò của bạn trong gia đình',luckyMascot:(a)=>`Linh vật may mắn của bé (${a})`,nicknameLabel:'Biệt danh của bé',nicknamePlaceholder:'Ví dụ: Bé Bo, Sóc Nhí, Cún Con…',nicknamePrefix:'Bé',parentNameLabel:'Tên của Ba Mẹ / Người nuôi dưỡng *',parentNamePlaceholder:'Ví dụ: Mẹ Lan, Bố Tuấn, Bà Ngoại…',parentNameRequired:'Vui lòng nhập tên của ba mẹ để tiện xưng hô trong ứng dụng nhé!',philosophyBody:'Trẻ học qua những gì các em quan sát mỗi ngày. Khi người lớn sống vui, tử tế và nhất quán, con sẽ có một hình mẫu rõ ràng để noi theo.',philosophyTitle:'“Trở thành trước khi giáo dục — người lớn làm gương”',previewBundle:(s)=>`Gói Hành Động Thích Ứng (${s})`,roles:{mother:'👩 Mẹ',father:'👨 Bố',grandparent:'👵 Ông / Bà',guardian:'🧑 Người giám hộ'},saveError:'Không thể lưu xác nhận quyền riêng tư. Vui lòng thử lại.',saving:'Đang lưu an toàn…',stageLabels:{'0-3':'0–3 tuổi','3-6':'3–6 tuổi','6-12':'6–12 tuổi','12-18':'12–18 tuổi'},stepOne:'Bước 1/2: Thông tin người nuôi dưỡng',stepTwo:'Bước 2/2: Thông tin bé & lộ trình theo tuổi',title:'Đăng Ký & Cá Nhân Hóa Theo Lứa Tuổi',continue:'Tiếp Tục: Thêm Thông Tin Bé',
    stages:{
      '0-3':{title:'Thấm nhuần môi trường & làm gương',subtitle:'Ba mẹ làm trước • Con quan sát mỗi ngày',summary:'Ở giai đoạn này, trẻ học chủ yếu bằng quan sát. Hãy tạo một môi trường ấm áp và nhất quán để con hấp thụ những thói quen tốt.',habitTitles:['Mỉm cười rạng rỡ chào đón con','Nói lời cảm ơn trước mặt con','Ôm con và nói lời yêu thương','Bình tĩnh hướng dẫn khi con làm đổ nước','Đọc sách cho con trước giờ ngủ','Ngủ đúng giờ và giữ lời hứa']},
      '3-6':{title:'Xây nền thói quen & sẻ chia',subtitle:'Tự lập bước đầu • Học cho đi bằng việc nhỏ',summary:'Trẻ bắt đầu tự làm những việc vừa sức, luyện lễ phép và học cách chia sẻ với người xung quanh.',habitTitles:['Mỉm cười chào cả nhà buổi sáng','Tự đánh răng sáng và tối đủ 2 phút','Mời cơm và nói lời cảm ơn','Tự cất đồ chơi sau khi chơi','Chia sẻ đồ chơi và nhường bạn','Ôm chúc ba mẹ ngủ ngon trước 21h']},
      '6-12':{title:'Kỹ năng, phẩm chất & trách nhiệm',subtitle:'Giữ lời • Học tập • Góp sức cho gia đình',summary:'Trẻ rèn trách nhiệm qua việc nhà, học tập chủ động, lòng biết ơn và những hành động giúp đỡ cụ thể.',habitTitles:['Dậy đúng giờ và tự gấp chăn','Rửa bát và dọn bàn sau bữa ăn','Đọc sách 20 phút và ghi một bài học','Ghi ba điều biết ơn trong ngày','Kèm em học hoặc giúp đỡ bạn','Chuẩn bị sách vở và ngủ trước 21h30']},
      '12-18':{title:'Tự lập, kỷ luật & khát vọng',subtitle:'Quản trị bản thân • Xây tầm nhìn tương lai',summary:'Thanh thiếu niên xây kỷ luật cá nhân, cân bằng công nghệ, xác định mục tiêu và đóng góp tích cực cho cộng đồng.',habitTitles:['Tập thể dục 30 phút mỗi sáng','Quản lý thời gian và kế hoạch tuần','Giới hạn giải trí màn hình dưới 1 giờ','Cập nhật bảng tầm nhìn và mục tiêu 5 năm','Tĩnh tâm 15 phút mỗi tối','Lan tỏa giá trị tích cực cho đội nhóm']},
    },
  },
  en: {
    ageLabel:"Child's current age:",ageUnit:'years old',autoLoad:'Add starter habits',back:'Back',childNameLabel:"Child's full name *",childNamePlaceholder:'For example: Alex Nguyen…',childNameRequired:"Please enter your child's name.",close:'Close',complete:'Finish & Start Building Habits',consent:"I am the child's parent or legal guardian and agree that KidHabit may store profile, habit, and progress data to provide the app. Public leaderboards are off by default and only activate when I choose.",consentRequired:"Please confirm that you are authorized to manage the child's data.",contactHelp:'Your data is protected and used to sync the family journey across devices.',contactLabel:'Phone number or email (optional)',contactPlaceholder:'For backup and family guidance…',dialogLabel:'Set up your family',familyRoleLabel:'Your role in the family',luckyMascot:(a)=>`Lucky mascot (${a})`,nicknameLabel:'Nickname',nicknamePlaceholder:'For example: Alex, Sunny, Little Bear…',nicknamePrefix:'Little',parentNameLabel:'Parent or caregiver name *',parentNamePlaceholder:'For example: Mom, Dad, Grandma…',parentNameRequired:'Please enter the caregiver name.',philosophyBody:'Children learn from what they see every day. When adults act with joy, kindness, and consistency, children have a clear example to follow.',philosophyTitle:'“Become the example before you teach”',previewBundle:(s)=>`Age-ready starter habits (${s})`,roles:{mother:'👩 Mother',father:'👨 Father',grandparent:'👵 Grandparent',guardian:'🧑 Guardian'},saveError:'Could not save the privacy consent. Please try again.',saving:'Saving securely…',stageLabels:{'0-3':'Ages 0–3','3-6':'Ages 3–6','6-12':'Ages 6–12','12-18':'Ages 12–18'},stepOne:'Step 1 of 2: Caregiver details',stepTwo:'Step 2 of 2: Child and age-based journey',title:"Create Your Family's Age-Based Plan",continue:'Continue: Add Your Child',
    stages:{
      '0-3':{title:'Absorb the environment & learn by example',subtitle:'Parents lead • Children observe every day',summary:'At this age, children learn mainly by watching. Create a warm, consistent environment where good habits are easy to absorb.',habitTitles:['Welcome your child with a bright smile','Say thank you in front of your child','Hug your child and speak with love','Guide calmly when something spills','Read together before bedtime','Keep bedtime routines and promises']},
      '3-6':{title:'Build habit foundations & sharing',subtitle:'Early independence • Giving through small acts',summary:'Children begin doing age-appropriate tasks, practicing courtesy, and learning to share with others.',habitTitles:['Smile and greet the family each morning','Brush teeth for two minutes morning and night','Invite others to eat and say thank you','Put toys away after playing','Share toys and take turns','Hug parents goodnight before 9 p.m.']},
      '6-12':{title:'Skills, character & responsibility',subtitle:'Keep promises • Learn • Help the family',summary:'Children build responsibility through chores, active learning, gratitude, and practical acts of help.',habitTitles:['Wake on time and make the bed','Wash dishes and clear the table','Read for 20 minutes and note one lesson','Write three things you appreciate','Help a sibling study or support a friend','Prepare school items and sleep before 9:30 p.m.']},
      '12-18':{title:'Independence, discipline & purpose',subtitle:'Manage yourself • Shape your future',summary:'Teens build self-discipline, balance technology, set meaningful goals, and contribute to their community.',habitTitles:['Exercise for 30 minutes each morning','Manage personal time and the weekly plan','Keep recreational screen time under one hour','Update a vision board and five-year goals','Practice 15 minutes of quiet reflection','Share positive values with your team']},
    },
  },
  fr: {
    ageLabel:'Âge actuel de l’enfant :',ageUnit:'ans',autoLoad:'Ajouter les habitudes',back:'Retour',childNameLabel:'Nom complet de l’enfant *',childNamePlaceholder:'Ex. : Camille Martin…',childNameRequired:'Veuillez saisir le nom de votre enfant.',close:'Fermer',complete:'Terminer et commencer',consent:'Je suis le parent ou le tuteur légal et j’accepte que KidHabit conserve les données de profil, d’habitudes et de progrès nécessaires au service. Le classement public est désactivé par défaut.',consentRequired:'Veuillez confirmer votre autorisation à gérer les données de l’enfant.',contactHelp:'Vos données sont protégées et servent à synchroniser le parcours familial entre les appareils.',contactLabel:'Téléphone ou e-mail (facultatif)',contactPlaceholder:'Ajoutez-en un pour la sauvegarde et les conseils…',dialogLabel:'Configurer la famille',familyRoleLabel:'Votre rôle dans la famille',luckyMascot:(a)=>`Mascotte porte-bonheur (${a})`,nicknameLabel:'Surnom',nicknamePlaceholder:'Ex. : Cami, Soleil, Petit Ours…',nicknamePrefix:'Petit',parentNameLabel:'Nom du parent ou de l’adulte référent *',parentNamePlaceholder:'Ex. : Maman, Papa, Mamie…',parentNameRequired:'Veuillez saisir le nom de l’adulte référent.',philosophyBody:'Les enfants apprennent de ce qu’ils voient chaque jour. Des adultes joyeux, bienveillants et constants leur offrent un modèle clair.',philosophyTitle:'« Montrer l’exemple avant d’enseigner »',previewBundle:(s)=>`Habitudes adaptées à l’âge (${s})`,roles:{mother:'👩 Mère',father:'👨 Père',grandparent:'👵 Grand-parent',guardian:'🧑 Tuteur'},saveError:'Impossible d’enregistrer le consentement. Réessayez.',saving:'Enregistrement sécurisé…',stageLabels:{'0-3':'0–3 ans','3-6':'3–6 ans','6-12':'6–12 ans','12-18':'12–18 ans'},stepOne:'Étape 1 sur 2 : adulte référent',stepTwo:'Étape 2 sur 2 : enfant et parcours par âge',title:'Créer un parcours familial personnalisé',continue:'Continuer : ajouter l’enfant',
    stages:{'0-3':{title:'S’imprégner du milieu et de l’exemple',subtitle:'Les parents guident • L’enfant observe',summary:'À cet âge, l’enfant apprend surtout en regardant. Créez un cadre chaleureux et constant.',habitTitles:['Accueillir l’enfant avec un grand sourire','Dire merci devant l’enfant','Faire un câlin et parler avec amour','Guider calmement en cas de maladresse','Lire ensemble avant le coucher','Respecter le coucher et ses promesses']},'3-6':{title:'Fonder les habitudes et le partage',subtitle:'Première autonomie • Petits gestes généreux',summary:'L’enfant commence à agir seul, à être poli et à partager avec les autres.',habitTitles:['Sourire et saluer la famille le matin','Se brosser les dents deux minutes matin et soir','Inviter à table et dire merci','Ranger ses jouets après avoir joué','Partager les jouets et attendre son tour','Faire un câlin avant 21 h']},'6-12':{title:'Compétences, caractère et responsabilité',subtitle:'Tenir parole • Apprendre • Aider la famille',summary:'L’enfant devient responsable grâce aux tâches, à l’apprentissage actif et à la gratitude.',habitTitles:['Se lever à l’heure et faire son lit','Faire la vaisselle et débarrasser','Lire 20 minutes et noter une leçon','Écrire trois motifs de gratitude','Aider un proche ou un camarade','Préparer ses affaires et dormir avant 21 h 30']},'12-18':{title:'Autonomie, discipline et projet',subtitle:'Se gérer • Construire son avenir',summary:'L’adolescent cultive sa discipline, équilibre le numérique et se fixe des objectifs porteurs de sens.',habitTitles:['Faire 30 minutes d’exercice le matin','Gérer son temps et son planning hebdomadaire','Limiter les écrans de loisir à une heure','Actualiser sa vision et ses objectifs à cinq ans','Méditer 15 minutes chaque soir','Partager des valeurs positives avec son groupe']}},
  },
  de: {
    ageLabel:'Aktuelles Alter des Kindes:',ageUnit:'Jahre',autoLoad:'Startgewohnheiten hinzufügen',back:'Zurück',childNameLabel:'Vollständiger Name des Kindes *',childNamePlaceholder:'Zum Beispiel: Alex Müller…',childNameRequired:'Bitte gib den Namen deines Kindes ein.',close:'Schließen',complete:'Fertigstellen und starten',consent:'Ich bin Elternteil oder gesetzliche Betreuungsperson und stimme zu, dass KidHabit Profil-, Gewohnheits- und Fortschrittsdaten für die App speichert. Öffentliche Ranglisten sind standardmäßig deaktiviert.',consentRequired:'Bitte bestätige, dass du die Daten des Kindes verwalten darfst.',contactHelp:'Deine Daten sind geschützt und synchronisieren den Familienweg auf mehreren Geräten.',contactLabel:'Telefon oder E-Mail (optional)',contactPlaceholder:'Für Sicherung und Familienimpulse hinzufügen…',dialogLabel:'Familie einrichten',familyRoleLabel:'Deine Rolle in der Familie',luckyMascot:(a)=>`Glücks-Maskottchen (${a})`,nicknameLabel:'Spitzname',nicknamePlaceholder:'Zum Beispiel: Alex, Sonnenschein…',nicknamePrefix:'Klein',parentNameLabel:'Name eines Elternteils oder Betreuers *',parentNamePlaceholder:'Zum Beispiel: Mama, Papa, Oma…',parentNameRequired:'Bitte gib den Namen der Betreuungsperson ein.',philosophyBody:'Kinder lernen aus dem, was sie täglich sehen. Freude, Freundlichkeit und Verlässlichkeit geben ihnen ein klares Vorbild.',philosophyTitle:'„Vorleben, bevor wir lehren“',previewBundle:(s)=>`Altersgerechte Startgewohnheiten (${s})`,roles:{mother:'👩 Mutter',father:'👨 Vater',grandparent:'👵 Großelternteil',guardian:'🧑 Betreuungsperson'},saveError:'Die Einwilligung konnte nicht gespeichert werden. Bitte versuche es erneut.',saving:'Wird sicher gespeichert…',stageLabels:{'0-3':'0–3 Jahre','3-6':'3–6 Jahre','6-12':'6–12 Jahre','12-18':'12–18 Jahre'},stepOne:'Schritt 1 von 2: Betreuungsperson',stepTwo:'Schritt 2 von 2: Kind und Altersweg',title:'Altersgerechten Familienplan erstellen',continue:'Weiter: Kind hinzufügen',
    stages:{'0-3':{title:'Umgebung aufnehmen und am Vorbild lernen',subtitle:'Eltern leben vor • Kinder beobachten',summary:'In diesem Alter lernen Kinder vor allem durch Beobachtung. Schaffe ein warmes, verlässliches Umfeld.',habitTitles:['Das Kind mit einem Lächeln begrüßen','Vor dem Kind Danke sagen','Umarmen und liebevoll sprechen','Bei kleinen Missgeschicken ruhig helfen','Vor dem Schlafengehen vorlesen','Schlafzeiten und Versprechen einhalten']},'3-6':{title:'Gewohnheiten und Teilen aufbauen',subtitle:'Erste Selbstständigkeit • Kleine gute Taten',summary:'Kinder übernehmen erste Aufgaben, üben Höflichkeit und lernen zu teilen.',habitTitles:['Morgens lächeln und die Familie begrüßen','Morgens und abends zwei Minuten Zähne putzen','Zum Essen einladen und Danke sagen','Spielzeug nach dem Spielen wegräumen','Spielzeug teilen und abwechseln','Eltern vor 21 Uhr gute Nacht wünschen']},'6-12':{title:'Fähigkeiten, Charakter und Verantwortung',subtitle:'Wort halten • Lernen • In der Familie helfen',summary:'Kinder übernehmen Verantwortung durch Aufgaben, aktives Lernen und Dankbarkeit.',habitTitles:['Pünktlich aufstehen und das Bett machen','Geschirr spülen und den Tisch abräumen','20 Minuten lesen und eine Erkenntnis notieren','Drei Dinge aufschreiben, für die man dankbar ist','Geschwistern oder Freunden helfen','Schulsachen vorbereiten und vor 21:30 schlafen']},'12-18':{title:'Selbstständigkeit, Disziplin und Ziele',subtitle:'Sich organisieren • Die Zukunft gestalten',summary:'Jugendliche entwickeln Disziplin, nutzen Technik bewusst und setzen sinnvolle Ziele.',habitTitles:['Jeden Morgen 30 Minuten trainieren','Zeit und Wochenplan selbst verwalten','Freizeit am Bildschirm auf eine Stunde begrenzen','Vision Board und Fünfjahresziele aktualisieren','Abends 15 Minuten zur Ruhe kommen','Positive Werte im Team weitergeben']}},
  },
  it: {
    ageLabel:'Età attuale del bambino:',ageUnit:'anni',autoLoad:'Aggiungi abitudini iniziali',back:'Indietro',childNameLabel:'Nome completo del bambino *',childNamePlaceholder:'Ad esempio: Luca Rossi…',childNameRequired:'Inserisci il nome del bambino.',close:'Chiudi',complete:'Completa e inizia',consent:'Sono il genitore o tutore legale e acconsento che KidHabit conservi i dati di profilo, abitudini e progressi necessari al servizio. Le classifiche pubbliche sono disattivate per impostazione predefinita.',consentRequired:'Conferma di essere autorizzato a gestire i dati del bambino.',contactHelp:'I dati sono protetti e servono a sincronizzare il percorso familiare tra dispositivi.',contactLabel:'Telefono o e-mail (facoltativo)',contactPlaceholder:'Aggiungilo per backup e consigli familiari…',dialogLabel:'Configura la famiglia',familyRoleLabel:'Il tuo ruolo in famiglia',luckyMascot:(a)=>`Mascotte portafortuna (${a})`,nicknameLabel:'Soprannome',nicknamePlaceholder:'Ad esempio: Luchi, Sole, Orsetto…',nicknamePrefix:'Piccolo',parentNameLabel:'Nome del genitore o tutore *',parentNamePlaceholder:'Ad esempio: Mamma, Papà, Nonna…',parentNameRequired:'Inserisci il nome del tutore.',philosophyBody:'I bambini imparano da ciò che vedono ogni giorno. Adulti gioiosi, gentili e coerenti offrono un esempio chiaro.',philosophyTitle:'“Dai l’esempio prima di insegnare”',previewBundle:(s)=>`Abitudini adatte all’età (${s})`,roles:{mother:'👩 Madre',father:'👨 Padre',grandparent:'👵 Nonno/a',guardian:'🧑 Tutore'},saveError:'Impossibile salvare il consenso. Riprova.',saving:'Salvataggio sicuro…',stageLabels:{'0-3':'0–3 anni','3-6':'3–6 anni','6-12':'6–12 anni','12-18':'12–18 anni'},stepOne:'Passaggio 1 di 2: tutore',stepTwo:'Passaggio 2 di 2: bambino e percorso per età',title:'Crea il percorso familiare personalizzato',continue:'Continua: aggiungi il bambino',
    stages:{'0-3':{title:'Assorbire l’ambiente e imparare dall’esempio',subtitle:'I genitori guidano • I bambini osservano',summary:'A questa età si impara soprattutto osservando. Crea un ambiente caldo e coerente.',habitTitles:['Accogliere il bambino con un sorriso','Dire grazie davanti al bambino','Abbracciare e parlare con amore','Guidare con calma dopo un piccolo incidente','Leggere insieme prima di dormire','Rispettare orari e promesse']},'3-6':{title:'Costruire abitudini e condivisione',subtitle:'Prima autonomia • Piccoli gesti generosi',summary:'Il bambino inizia a fare da sé, pratica la cortesia e impara a condividere.',habitTitles:['Sorridere e salutare la famiglia al mattino','Lavare i denti due minuti mattina e sera','Invitare a tavola e dire grazie','Riordinare i giochi dopo aver giocato','Condividere i giochi e aspettare il proprio turno','Abbracciare i genitori prima delle 21']},'6-12':{title:'Capacità, carattere e responsabilità',subtitle:'Mantenere la parola • Imparare • Aiutare',summary:'Il bambino cresce con compiti, apprendimento attivo e gratitudine.',habitTitles:['Alzarsi in orario e rifare il letto','Lavare i piatti e sparecchiare','Leggere 20 minuti e annotare una lezione','Scrivere tre cose per cui essere grati','Aiutare un fratello o un amico','Preparare la scuola e dormire prima delle 21:30']},'12-18':{title:'Autonomia, disciplina e obiettivi',subtitle:'Gestirsi • Costruire il futuro',summary:'L’adolescente sviluppa disciplina, equilibrio digitale e obiettivi significativi.',habitTitles:['Allenarsi 30 minuti ogni mattina','Gestire il tempo e il piano settimanale','Limitare lo svago su schermo a un’ora','Aggiornare visione e obiettivi a cinque anni','Riflettere in silenzio per 15 minuti','Condividere valori positivi con il gruppo']}},
  },
  es: {
    ageLabel:'Edad actual del niño:',ageUnit:'años',autoLoad:'Añadir hábitos iniciales',back:'Atrás',childNameLabel:'Nombre completo del niño *',childNamePlaceholder:'Por ejemplo: Alex García…',childNameRequired:'Escribe el nombre del niño.',close:'Cerrar',complete:'Finalizar y comenzar',consent:'Soy el padre, la madre o el tutor legal y acepto que KidHabit almacene los datos de perfil, hábitos y progreso necesarios para ofrecer la aplicación. La clasificación pública está desactivada por defecto.',consentRequired:'Confirma que estás autorizado para gestionar los datos del niño.',contactHelp:'Tus datos están protegidos y se usan para sincronizar el recorrido familiar entre dispositivos.',contactLabel:'Teléfono o correo (opcional)',contactPlaceholder:'Añádelo para copias y orientación familiar…',dialogLabel:'Configurar la familia',familyRoleLabel:'Tu papel en la familia',luckyMascot:(a)=>`Mascota de la suerte (${a})`,nicknameLabel:'Apodo',nicknamePlaceholder:'Por ejemplo: Alex, Sol, Osito…',nicknamePrefix:'Peque',parentNameLabel:'Nombre del padre, madre o tutor *',parentNamePlaceholder:'Por ejemplo: Mamá, Papá, Abuela…',parentNameRequired:'Escribe el nombre del cuidador.',philosophyBody:'Los niños aprenden de lo que ven cada día. La alegría, la bondad y la constancia de los adultos les dan un ejemplo claro.',philosophyTitle:'“Da ejemplo antes de enseñar”',previewBundle:(s)=>`Hábitos adaptados a la edad (${s})`,roles:{mother:'👩 Madre',father:'👨 Padre',grandparent:'👵 Abuelo/a',guardian:'🧑 Tutor/a'},saveError:'No se pudo guardar el consentimiento. Inténtalo de nuevo.',saving:'Guardando de forma segura…',stageLabels:{'0-3':'0–3 años','3-6':'3–6 años','6-12':'6–12 años','12-18':'12–18 años'},stepOne:'Paso 1 de 2: persona cuidadora',stepTwo:'Paso 2 de 2: niño y recorrido por edad',title:'Crea un plan familiar personalizado',continue:'Continuar: añadir al niño',
    stages:{'0-3':{title:'Absorber el entorno y aprender del ejemplo',subtitle:'Los padres guían • Los niños observan',summary:'A esta edad se aprende principalmente observando. Crea un entorno cálido y constante.',habitTitles:['Recibir al niño con una gran sonrisa','Dar las gracias delante del niño','Abrazar y hablar con cariño','Guiar con calma ante un pequeño accidente','Leer juntos antes de dormir','Respetar horarios y promesas']},'3-6':{title:'Crear hábitos y compartir',subtitle:'Primera autonomía • Pequeños actos generosos',summary:'El niño empieza a hacer tareas sencillas, practica la cortesía y aprende a compartir.',habitTitles:['Sonreír y saludar a la familia cada mañana','Cepillarse dos minutos por la mañana y la noche','Invitar a comer y dar las gracias','Guardar los juguetes después de jugar','Compartir juguetes y respetar turnos','Abrazar a los padres antes de las 21:00']},'6-12':{title:'Habilidades, carácter y responsabilidad',subtitle:'Cumplir • Aprender • Ayudar en familia',summary:'El niño asume responsabilidades con tareas, aprendizaje activo y gratitud.',habitTitles:['Levantarse a tiempo y hacer la cama','Lavar los platos y recoger la mesa','Leer 20 minutos y anotar una enseñanza','Escribir tres cosas que agradece','Ayudar a un hermano o amigo','Preparar la mochila y dormir antes de las 21:30']},'12-18':{title:'Autonomía, disciplina y propósito',subtitle:'Organizarse • Diseñar el futuro',summary:'El adolescente desarrolla disciplina, equilibrio digital y metas con sentido.',habitTitles:['Hacer ejercicio 30 minutos cada mañana','Gestionar el tiempo y el plan semanal','Limitar el ocio en pantalla a una hora','Actualizar la visión y las metas a cinco años','Reflexionar en silencio 15 minutos','Compartir valores positivos con el equipo']}},
  },
  zh: {
    ageLabel:'孩子目前的年龄：',ageUnit:'岁',autoLoad:'添加起步习惯',back:'返回',childNameLabel:'孩子的全名 *',childNamePlaceholder:'例如：王小明…',childNameRequired:'请输入孩子的姓名。',close:'关闭',complete:'完成并开始培养习惯',consent:'我是孩子的父母或法定监护人，同意 KidHabit 为提供服务保存孩子的档案、习惯和进度数据。公开排行榜默认关闭，只有我主动选择时才会开启。',consentRequired:'请确认您有权管理孩子的数据。',contactHelp:'您的数据会受到保护，并用于在多台设备间同步家庭成长计划。',contactLabel:'电话或电子邮箱（选填）',contactPlaceholder:'用于备份和接收家庭指导…',dialogLabel:'设置家庭',familyRoleLabel:'您在家庭中的角色',luckyMascot:(a)=>`幸运伙伴（${a}）`,nicknameLabel:'昵称',nicknamePlaceholder:'例如：小明、阳阳、小熊…',nicknamePrefix:'小',parentNameLabel:'父母或照护者姓名 *',parentNamePlaceholder:'例如：妈妈、爸爸、奶奶…',parentNameRequired:'请输入照护者姓名。',philosophyBody:'孩子每天都在观察中学习。成年人保持快乐、友善和一致，就是孩子最清晰的榜样。',philosophyTitle:'“教育之前，先成为榜样”',previewBundle:(s)=>`适龄起步习惯（${s}）`,roles:{mother:'👩 妈妈',father:'👨 爸爸',grandparent:'👵 祖父母',guardian:'🧑 监护人'},saveError:'无法保存隐私同意，请重试。',saving:'正在安全保存…',stageLabels:{'0-3':'0–3 岁','3-6':'3–6 岁','6-12':'6–12 岁','12-18':'12–18 岁'},stepOne:'第 1/2 步：照护者信息',stepTwo:'第 2/2 步：孩子和适龄计划',title:'创建适龄家庭成长计划',continue:'继续：添加孩子',
    stages:{'0-3':{title:'感知环境，向榜样学习',subtitle:'父母先做 • 孩子每天观察',summary:'这个阶段的孩子主要通过观察学习。请营造温暖、稳定的成长环境。',habitTitles:['用灿烂的笑容迎接孩子','在孩子面前表达感谢','拥抱孩子并温柔说话','发生小意外时冷静引导','睡前和孩子一起阅读','遵守作息并信守承诺']},'3-6':{title:'打好习惯与分享的基础',subtitle:'初步自理 • 从小事学会给予',summary:'孩子开始做力所能及的事，练习礼貌，并学习与他人分享。',habitTitles:['早晨微笑着问候家人','早晚认真刷牙两分钟','邀请家人用餐并说谢谢','玩完后自己收好玩具','分享玩具并轮流玩','晚上九点前拥抱父母道晚安']},'6-12':{title:'能力、品格与责任',subtitle:'信守承诺 • 主动学习 • 帮助家庭',summary:'孩子通过家务、主动学习、感恩和实际帮助建立责任感。',habitTitles:['按时起床并整理床铺','饭后洗碗并收拾餐桌','阅读 20 分钟并记下一点收获','写下当天三件感恩的事','帮助兄弟姐妹或朋友','准备好学习用品并在九点半前睡觉']},'12-18':{title:'独立、自律与志向',subtitle:'管理自己 • 规划未来',summary:'青少年培养自律，平衡数字生活，设定有意义的目标并积极贡献。',habitTitles:['每天早晨锻炼 30 分钟','管理个人时间和每周计划','娱乐屏幕时间控制在一小时内','更新愿景板和五年目标','每晚静心 15 分钟','向团队传递积极价值观']}},
  },
  ja: {
    ageLabel:'お子さまの現在の年齢：',ageUnit:'歳',autoLoad:'おすすめ習慣を追加',back:'戻る',childNameLabel:'お子さまの氏名 *',childNamePlaceholder:'例：山田 はる…',childNameRequired:'お子さまの名前を入力してください。',close:'閉じる',complete:'完了して習慣づくりを始める',consent:'私は子どもの保護者または法定代理人であり、KidHabit がサービス提供のためにプロフィール、習慣、進捗データを保存することに同意します。公開ランキングは初期設定で無効です。',consentRequired:'お子さまのデータを管理する権限があることを確認してください。',contactHelp:'データは保護され、複数端末で家族の歩みを同期するために使われます。',contactLabel:'電話番号またはメール（任意）',contactPlaceholder:'バックアップや子育てガイドの受信に使用…',dialogLabel:'家族を設定',familyRoleLabel:'ご家族での役割',luckyMascot:(a)=>`ラッキーマスコット（${a}）`,nicknameLabel:'ニックネーム',nicknamePlaceholder:'例：はる、ひなた、こぐま…',nicknamePrefix:'ちび',parentNameLabel:'保護者・養育者の名前 *',parentNamePlaceholder:'例：ママ、パパ、おばあちゃん…',parentNameRequired:'保護者の名前を入力してください。',philosophyBody:'子どもは毎日、目にする姿から学びます。大人の明るさ、優しさ、一貫した行動が分かりやすい手本になります。',philosophyTitle:'「教える前に、まず手本になる」',previewBundle:(s)=>`年齢に合ったおすすめ習慣（${s}）`,roles:{mother:'👩 母',father:'👨 父',grandparent:'👵 祖父母',guardian:'🧑 保護者'},saveError:'同意を保存できませんでした。もう一度お試しください。',saving:'安全に保存中…',stageLabels:{'0-3':'0～3歳','3-6':'3～6歳','6-12':'6～12歳','12-18':'12～18歳'},stepOne:'ステップ 1/2：保護者情報',stepTwo:'ステップ 2/2：お子さまと年齢別プラン',title:'年齢に合った家族プランを作成',continue:'次へ：お子さまを追加',
    stages:{'0-3':{title:'環境を感じ、手本から学ぶ',subtitle:'保護者が先に実践 • 子どもは毎日観察',summary:'この時期は主に見て学びます。温かく一貫した環境を整えましょう。',habitTitles:['笑顔でお子さまを迎える','お子さまの前で感謝を伝える','抱きしめて愛情を言葉にする','失敗したときも落ち着いて導く','寝る前に一緒に本を読む','生活リズムと約束を守る']},'3-6':{title:'習慣と分かち合いの土台を作る',subtitle:'初めての自立 • 小さな思いやり',summary:'自分でできることを増やし、礼儀や分かち合いを学びます。',habitTitles:['朝は笑顔で家族にあいさつする','朝晩二分間歯を磨く','食事のあいさつと感謝を伝える','遊んだ後はおもちゃを片づける','おもちゃを分け合い順番を守る','21時前に保護者へおやすみを伝える']},'6-12':{title:'力・人格・責任を育てる',subtitle:'約束 • 学び • 家族への貢献',summary:'家事、主体的な学び、感謝、具体的な手助けを通して責任感を育てます。',habitTitles:['時間どおりに起きて寝具を整える','食器を洗い食卓を片づける','20分読書して学びを一つ記録する','感謝したことを三つ書く','きょうだいや友だちを助ける','学用品を準備し21時30分までに眠る']},'12-18':{title:'自立・規律・志を育てる',subtitle:'自分を管理 • 未来を描く',summary:'自己管理、デジタルとのバランス、意味ある目標、社会への貢献を身につけます。',habitTitles:['毎朝30分運動する','自分の時間と週間計画を管理する','娯楽の画面時間を一時間以内にする','ビジョンと五年目標を更新する','毎晩15分静かに内省する','チームに前向きな価値観を広げる']}},
  },
  ko: {
    ageLabel:'아이의 현재 나이:',ageUnit:'세',autoLoad:'추천 습관 추가',back:'뒤로',childNameLabel:'아이의 이름 *',childNamePlaceholder:'예: 김하늘…',childNameRequired:'아이의 이름을 입력해 주세요.',close:'닫기',complete:'완료하고 습관 만들기 시작',consent:'저는 아이의 부모 또는 법적 보호자이며 KidHabit이 서비스 제공을 위해 프로필, 습관, 진행 데이터를 저장하는 데 동의합니다. 공개 순위표는 기본적으로 꺼져 있습니다.',consentRequired:'아이의 데이터를 관리할 권한이 있음을 확인해 주세요.',contactHelp:'데이터는 안전하게 보호되며 여러 기기에서 가족 여정을 동기화하는 데 사용됩니다.',contactLabel:'전화번호 또는 이메일(선택)',contactPlaceholder:'백업과 가족 가이드를 위해 추가하세요…',dialogLabel:'가족 설정',familyRoleLabel:'가족에서의 역할',luckyMascot:(a)=>`행운의 마스코트 (${a})`,nicknameLabel:'별명',nicknamePlaceholder:'예: 하늘이, 햇살, 꼬마곰…',nicknamePrefix:'꼬마',parentNameLabel:'부모 또는 보호자 이름 *',parentNamePlaceholder:'예: 엄마, 아빠, 할머니…',parentNameRequired:'보호자 이름을 입력해 주세요.',philosophyBody:'아이는 매일 눈으로 본 모습을 통해 배웁니다. 어른의 즐거움, 친절함, 일관된 행동이 분명한 본보기가 됩니다.',philosophyTitle:'“가르치기 전에 먼저 본보기가 되세요”',previewBundle:(s)=>`연령별 추천 습관 (${s})`,roles:{mother:'👩 어머니',father:'👨 아버지',grandparent:'👵 조부모',guardian:'🧑 보호자'},saveError:'개인정보 동의를 저장하지 못했습니다. 다시 시도해 주세요.',saving:'안전하게 저장 중…',stageLabels:{'0-3':'0~3세','3-6':'3~6세','6-12':'6~12세','12-18':'12~18세'},stepOne:'1/2단계: 보호자 정보',stepTwo:'2/2단계: 아이와 연령별 여정',title:'연령별 가족 성장 계획 만들기',continue:'계속: 아이 추가',
    stages:{'0-3':{title:'환경을 느끼고 본보기로 배우기',subtitle:'부모가 먼저 실천 • 아이는 매일 관찰',summary:'이 시기 아이는 주로 관찰하며 배웁니다. 따뜻하고 일관된 환경을 만들어 주세요.',habitTitles:['환한 미소로 아이를 맞이하기','아이 앞에서 감사 표현하기','안아 주고 사랑을 말하기','작은 실수에도 차분히 안내하기','잠들기 전 함께 책 읽기','수면 습관과 약속 지키기']},'3-6':{title:'습관과 나눔의 기초 만들기',subtitle:'첫 자립 • 작은 행동으로 나눔 배우기',summary:'아이는 할 수 있는 일을 스스로 하고 예절과 나눔을 익히기 시작합니다.',habitTitles:['아침마다 웃으며 가족에게 인사하기','아침저녁 2분 동안 양치하기','식사 인사와 감사 표현하기','놀고 난 뒤 장난감 정리하기','장난감을 나누고 차례 지키기','밤 9시 전에 부모님께 잘 자요 인사하기']},'6-12':{title:'역량, 인성, 책임 키우기',subtitle:'약속 • 배움 • 가족 돕기',summary:'집안일, 주도적 학습, 감사와 실제 도움을 통해 책임감을 기릅니다.',habitTitles:['제시간에 일어나 이불 정리하기','설거지하고 식탁 정리하기','20분 독서 후 배운 점 하나 쓰기','감사한 일 세 가지 쓰기','형제자매나 친구 돕기','학용품을 준비하고 9시 30분 전에 자기']},'12-18':{title:'자립, 규율, 목표 세우기',subtitle:'자기 관리 • 미래 설계',summary:'청소년은 자기 규율, 디지털 균형, 의미 있는 목표와 공동체 기여를 익힙니다.',habitTitles:['매일 아침 30분 운동하기','개인 시간과 주간 계획 관리하기','오락 화면 시간을 한 시간 이내로 제한하기','비전 보드와 5년 목표 업데이트하기','매일 저녁 15분 마음 가라앉히기','팀에 긍정적인 가치 전하기']}},
  },
};

export function getOnboardingCopy(language: Language): OnboardingCopy {
  return COPY[language];
}
