import type { Language } from '@/types';

type ParentReminderCopy = {
  readonly title: string;
  readonly description: string;
  readonly enable: string;
  readonly enabled: string;
  readonly disabled: string;
  readonly loading: string;
  readonly saving: string;
  readonly error: string;
  readonly allowDevice: string;
  readonly browserReady: string;
  readonly browserDenied: string;
  readonly inAppOnly: string;
  readonly pending: (count: number) => string;
};

export const parentReminderCopy: Record<Language, ParentReminderCopy> = {
  vi: { title: 'Nhắc việc cho phụ huynh', description: 'Chỉ nhắc khi có nhiệm vụ hoặc phần thưởng cần bạn duyệt. Không dùng cho quảng cáo và có thể tắt bất kỳ lúc nào.', enable: 'Cho phép nhắc việc cần xử lý', enabled: 'Đã bật lời nhắc.', disabled: 'Đang tắt. Không có lời nhắc nào được gửi.', loading: 'Đang tải lựa chọn…', saving: 'Đang lưu…', error: 'Chưa lưu được lựa chọn. Vui lòng thử lại.', allowDevice: 'Cho phép thông báo trên thiết bị', browserReady: 'Thiết bị đã sẵn sàng nhận thông báo.', browserDenied: 'Thiết bị đang chặn thông báo. Lời nhắc vẫn xuất hiện trong ứng dụng.', inAppOnly: 'Lời nhắc hiện chỉ xuất hiện trong ứng dụng.', pending: (count) => `Bạn có ${count} mục đang chờ xử lý.` },
  en: { title: 'Parent reminders', description: 'Get reminders only when a task or reward needs your review. Never used for advertising, and you can turn them off any time.', enable: 'Allow actionable reminders', enabled: 'Reminders are enabled.', disabled: 'Off. No reminders are sent.', loading: 'Loading your choice…', saving: 'Saving…', error: 'Could not save your choice. Please try again.', allowDevice: 'Allow notifications on this device', browserReady: 'This device is ready for notifications.', browserDenied: 'This device blocks notifications. Reminders still appear inside the app.', inAppOnly: 'Reminders currently appear only inside the app.', pending: (count) => `You have ${count} items waiting for review.` },
  fr: { title: 'Rappels pour les parents', description: 'Recevez un rappel uniquement lorsqu’une tâche ou une récompense attend votre validation. Jamais de publicité, désactivation à tout moment.', enable: 'Autoriser les rappels utiles', enabled: 'Les rappels sont activés.', disabled: 'Désactivés. Aucun rappel n’est envoyé.', loading: 'Chargement…', saving: 'Enregistrement…', error: 'Impossible d’enregistrer ce choix.', allowDevice: 'Autoriser les notifications sur cet appareil', browserReady: 'Cet appareil est prêt pour les notifications.', browserDenied: 'Les notifications sont bloquées. Les rappels restent visibles dans l’application.', inAppOnly: 'Les rappels apparaissent uniquement dans l’application.', pending: (count) => `${count} éléments attendent votre validation.` },
  de: { title: 'Eltern-Erinnerungen', description: 'Nur erinnern, wenn eine Aufgabe oder Belohnung geprüft werden muss. Keine Werbung und jederzeit abschaltbar.', enable: 'Hilfreiche Erinnerungen erlauben', enabled: 'Erinnerungen sind aktiviert.', disabled: 'Aus. Es werden keine Erinnerungen gesendet.', loading: 'Auswahl wird geladen…', saving: 'Wird gespeichert…', error: 'Auswahl konnte nicht gespeichert werden.', allowDevice: 'Benachrichtigungen auf diesem Gerät erlauben', browserReady: 'Dieses Gerät ist für Benachrichtigungen bereit.', browserDenied: 'Benachrichtigungen sind blockiert. Hinweise bleiben in der App sichtbar.', inAppOnly: 'Hinweise erscheinen derzeit nur in der App.', pending: (count) => `${count} Einträge warten auf Prüfung.` },
  it: { title: 'Promemoria per i genitori', description: 'Ricevi un promemoria solo quando un’attività o un premio richiede una verifica. Mai pubblicità e puoi disattivarlo in ogni momento.', enable: 'Consenti promemoria utili', enabled: 'I promemoria sono attivi.', disabled: 'Disattivati. Nessun promemoria viene inviato.', loading: 'Caricamento…', saving: 'Salvataggio…', error: 'Impossibile salvare la scelta.', allowDevice: 'Consenti notifiche su questo dispositivo', browserReady: 'Questo dispositivo è pronto per le notifiche.', browserDenied: 'Le notifiche sono bloccate. I promemoria restano visibili nell’app.', inAppOnly: 'I promemoria appaiono solo nell’app.', pending: (count) => `${count} elementi attendono una verifica.` },
  es: { title: 'Recordatorios para padres', description: 'Recibe avisos solo cuando una tarea o premio necesita revisión. Nunca se usan para publicidad y puedes desactivarlos cuando quieras.', enable: 'Permitir recordatorios útiles', enabled: 'Los recordatorios están activados.', disabled: 'Desactivados. No se envía ningún recordatorio.', loading: 'Cargando…', saving: 'Guardando…', error: 'No se pudo guardar la elección.', allowDevice: 'Permitir notificaciones en este dispositivo', browserReady: 'Este dispositivo está listo para recibir notificaciones.', browserDenied: 'Las notificaciones están bloqueadas. Los avisos siguen apareciendo dentro de la aplicación.', inAppOnly: 'Los avisos aparecen solo dentro de la aplicación.', pending: (count) => `Tienes ${count} elementos pendientes de revisión.` },
  zh: { title: '家长待办提醒', description: '仅在任务或奖励需要审核时提醒，不用于广告，并可随时关闭。', enable: '允许待办提醒', enabled: '提醒已开启。', disabled: '已关闭，不会发送提醒。', loading: '正在加载…', saving: '正在保存…', error: '无法保存选择，请重试。', allowDevice: '允许此设备发送通知', browserReady: '此设备已可接收通知。', browserDenied: '此设备已阻止通知，提醒仍会显示在应用内。', inAppOnly: '提醒目前仅显示在应用内。', pending: (count) => `有 ${count} 项内容等待审核。` },
  ja: { title: '保護者向けリマインダー', description: 'タスクやごほうびの確認が必要なときだけ通知します。広告には使用せず、いつでもオフにできます。', enable: '必要なリマインダーを許可する', enabled: 'リマインダーはオンです。', disabled: 'オフです。リマインダーは送信されません。', loading: '読み込み中…', saving: '保存中…', error: '選択を保存できませんでした。', allowDevice: 'この端末で通知を許可する', browserReady: 'この端末で通知を受け取れます。', browserDenied: '通知がブロックされています。アプリ内のリマインダーは表示されます。', inAppOnly: '現在はアプリ内にのみ表示されます。', pending: (count) => `${count} 件の確認待ちがあります。` },
  ko: { title: '부모님 할 일 알림', description: '미션이나 선물 확인이 필요할 때만 알려 드립니다. 광고에는 사용하지 않으며 언제든 끌 수 있습니다.', enable: '필요한 알림 허용', enabled: '알림이 켜져 있습니다.', disabled: '꺼져 있습니다. 알림을 보내지 않습니다.', loading: '불러오는 중…', saving: '저장 중…', error: '선택을 저장하지 못했습니다.', allowDevice: '이 기기에서 알림 허용', browserReady: '이 기기에서 알림을 받을 수 있습니다.', browserDenied: '알림이 차단되어 있습니다. 앱 안의 알림은 계속 표시됩니다.', inAppOnly: '현재 앱 안에서만 알림이 표시됩니다.', pending: (count) => `${count}개 항목이 확인을 기다리고 있습니다.` },
};
