import type { Language } from '@/types';
import type { SupportLevel } from '@/lib/habit-programs/types';

export type ParentTodayCopy = {
  readonly chooseChild: string; readonly todayOf: (name: string) => string;
  readonly doneOfTotal: (done: number, total: number) => string; readonly noTasksToday: string;
  readonly streak: (days: number) => string; readonly streakNote: string; readonly actionsTitle: string;
  readonly nothingToDo: string; readonly suggestionsWaiting: (count: number) => string; readonly seeSuggestions: string;
  readonly building: (count: number, limit: number) => string; readonly lastSevenDays: string;
  readonly doneOfSeven: (done: number) => string; readonly lean: Readonly<Record<SupportLevel, string>>;
  readonly dayDone: string; readonly dayMissed: string; readonly dayNone: string; readonly emptyTitle: string;
  readonly emptyBody: string; readonly emptyCta: string; readonly weeklyTitle: string; readonly weeklyIntro: string;
  readonly weeklyPraise: (title: string) => string; readonly weeklyAdjust: (title: string) => string;
  readonly weeklyAdd: string; readonly weeklyHold: string; readonly weeklyNoData: string;
};

const COPY: Record<Language, ParentTodayCopy> = {
  vi: {
    chooseChild: 'Chọn bé', todayOf: (name) => `Hôm nay của ${name}`, doneOfTotal: (done, total) => `${done} / ${total} việc đã xong`, noTasksToday: 'Hôm nay bé chưa có việc nào theo lịch', streak: (days) => `Chuỗi ${days} ngày`, streakNote: 'Bỏ lỡ một ngày không làm mất tiến triển', actionsTitle: 'Cần ba mẹ làm', nothingToDo: 'Hiện không có việc nào cần ba mẹ xử lý.', suggestionsWaiting: (count) => `Có ${count} gợi ý điều chỉnh cho thói quen của bé`, seeSuggestions: 'Xem gợi ý', building: (count, limit) => `Thói quen đang xây (${count} / ${limit})`, lastSevenDays: 'Bảy ngày gần nhất', doneOfSeven: (done) => `${done} / 7 ngày gần nhất`, lean: { alone: 'bé tự làm', prompted: 'cần nhắc', together: 'làm cùng ba mẹ' }, dayDone: 'đã làm', dayMissed: 'chưa làm', dayNone: 'không có lịch', emptyTitle: 'Chưa có thói quen nào đang xây', emptyBody: 'Chọn một thói quen và đặt tín hiệu nhắc (cùng giờ, cùng chỗ) để bắt đầu theo dõi tiến triển của bé.', emptyCta: 'Đặt tín hiệu cho thói quen đầu tiên', weeklyTitle: 'Nhìn lại tuần này (5 phút)', weeklyIntro: 'Mỗi tuần một lần, cùng nhìn lại thay vì nhắc từng ngày.', weeklyPraise: (title) => `Một điều để khen: bé đều đặn với “${title}”.`, weeklyAdjust: (title) => `Một điều cần chỉnh: “${title}” còn chưa đều. Thử làm nhỏ hơn hoặc đổi giờ.`, weeklyAdd: 'Các thói quen đang khá đều. Nếu muốn, thêm một thói quen mới (không vượt giới hạn cùng lúc).', weeklyHold: 'Chưa nên thêm thói quen mới. Giữ nhịp thêm một tuần.', weeklyNoData: 'Chưa đủ dữ liệu tuần này. Ghi nhận “bé làm thế nào” vài ngày để có nhận xét.',
  },
  en: {
    chooseChild: 'Choose a child', todayOf: (name) => `${name}’s day`, doneOfTotal: (done, total) => `${done} of ${total} tasks done`, noTasksToday: 'No tasks are scheduled for today', streak: (days) => `${days}-day streak`, streakNote: 'Missing a day does not undo progress', actionsTitle: 'Needs you', nothingToDo: 'Nothing needs you right now.', suggestionsWaiting: (count) => `${count} adjustment suggestion${count === 1 ? '' : 's'} for your child’s habits`, seeSuggestions: 'See suggestions', building: (count, limit) => `Habits being built (${count} of ${limit})`, lastSevenDays: 'Last seven days', doneOfSeven: (done) => `${done} of the last 7 days`, lean: { alone: 'did it alone', prompted: 'needed a reminder', together: 'did it with you' }, dayDone: 'done', dayMissed: 'not done', dayNone: 'not scheduled', emptyTitle: 'No habits are being built yet', emptyBody: 'Pick a habit and set a cue (same time, same place) to start following your child’s progress.', emptyCta: 'Set a cue for the first habit', weeklyTitle: 'Look back at this week (5 minutes)', weeklyIntro: 'Once a week, look back together instead of reminding every day.', weeklyPraise: (title) => `One thing to praise: steady work on “${title}”.`, weeklyAdjust: (title) => `One thing to adjust: “${title}” is not steady yet. Try making it smaller or changing the time.`, weeklyAdd: 'The habits are fairly steady. If you like, add one new habit (within the limit for this age).', weeklyHold: 'Hold off on a new habit. Keep the rhythm another week.', weeklyNoData: 'Not enough data this week. Record how your child did it for a few days to get a note.',
  },
  fr: {
    chooseChild: 'Choisir un enfant', todayOf: (name) => `La journée de ${name}`, doneOfTotal: (done, total) => `${done} tâche${done > 1 ? 's' : ''} sur ${total} terminée${done > 1 ? 's' : ''}`, noTasksToday: 'Aucune tâche prévue aujourd’hui', streak: (days) => `Série de ${days} jours`, streakNote: 'Un jour manqué ne fait pas perdre les progrès', actionsTitle: 'À faire par le parent', nothingToDo: 'Rien à faire pour le moment.', suggestionsWaiting: (count) => `${count} suggestion${count > 1 ? 's' : ''} d’ajustement pour les habitudes de votre enfant`, seeSuggestions: 'Voir les suggestions', building: (count, limit) => `Habitudes en construction (${count} sur ${limit})`, lastSevenDays: 'Les sept derniers jours', doneOfSeven: (done) => `${done} jour${done > 1 ? 's' : ''} sur les 7 derniers`, lean: { alone: 'a réussi seul', prompted: 'a eu besoin d’un rappel', together: 'a réussi avec vous' }, dayDone: 'fait', dayMissed: 'non fait', dayNone: 'non prévu', emptyTitle: 'Aucune habitude en construction', emptyBody: 'Choisissez une habitude et définissez un repère (même heure, même endroit) pour suivre les progrès de votre enfant.', emptyCta: 'Définir un repère pour la première habitude', weeklyTitle: 'Bilan de la semaine (5 minutes)', weeklyIntro: 'Une fois par semaine, faites le bilan ensemble au lieu de rappeler chaque jour.', weeklyPraise: (title) => `Un point à féliciter : la régularité pour « ${title} ».`, weeklyAdjust: (title) => `Un point à ajuster : « ${title} » manque encore de régularité. Essayez de réduire l’action ou de changer l’heure.`, weeklyAdd: 'Les habitudes sont assez régulières. Si vous le souhaitez, ajoutez-en une nouvelle (dans la limite de cet âge).', weeklyHold: 'Mieux vaut attendre avant d’ajouter une habitude. Gardez le rythme une semaine de plus.', weeklyNoData: 'Pas assez de données cette semaine. Notez comment votre enfant a fait pendant quelques jours pour obtenir un bilan.',
  },
  de: {
    chooseChild: 'Kind auswählen', todayOf: (name) => `${name}s Tag`, doneOfTotal: (done, total) => `${done} von ${total} Aufgaben erledigt`, noTasksToday: 'Für heute sind keine Aufgaben geplant', streak: (days) => `${days}-Tage-Serie`, streakNote: 'Ein verpasster Tag macht den Fortschritt nicht rückgängig', actionsTitle: 'Für Eltern', nothingToDo: 'Im Moment ist nichts zu tun.', suggestionsWaiting: (count) => `${count} Anpassungsvorschlag${count === 1 ? '' : 'e'} für die Gewohnheiten deines Kindes`, seeSuggestions: 'Vorschläge ansehen', building: (count, limit) => `Gewohnheiten im Aufbau (${count} von ${limit})`, lastSevenDays: 'Letzte sieben Tage', doneOfSeven: (done) => `${done} von 7 letzten Tagen`, lean: { alone: 'allein geschafft', prompted: 'brauchte eine Erinnerung', together: 'mit dir geschafft' }, dayDone: 'erledigt', dayMissed: 'nicht erledigt', dayNone: 'nicht geplant', emptyTitle: 'Noch keine Gewohnheit im Aufbau', emptyBody: 'Wähle eine Gewohnheit und lege einen Hinweis fest (gleiche Zeit, gleicher Ort), um den Fortschritt deines Kindes zu verfolgen.', emptyCta: 'Hinweis für die erste Gewohnheit festlegen', weeklyTitle: 'Diese Woche zurückblicken (5 Minuten)', weeklyIntro: 'Blickt einmal pro Woche gemeinsam zurück, statt jeden Tag zu erinnern.', weeklyPraise: (title) => `Etwas zum Loben: regelmäßiges Üben von „${title}“.`, weeklyAdjust: (title) => `Etwas anpassen: „${title}“ ist noch nicht regelmäßig. Versuche es kleiner zu machen oder die Uhrzeit zu ändern.`, weeklyAdd: 'Die Gewohnheiten laufen recht regelmäßig. Wenn du möchtest, füge eine neue hinzu (innerhalb des Alterslimits).', weeklyHold: 'Warte mit einer neuen Gewohnheit. Halte den Rhythmus noch eine Woche.', weeklyNoData: 'Diese Woche gibt es noch nicht genug Daten. Notiere einige Tage, wie dein Kind es gemacht hat, um eine Einschätzung zu erhalten.',
  },
  it: {
    chooseChild: 'Scegli un bambino', todayOf: (name) => `La giornata di ${name}`, doneOfTotal: (done, total) => `${done} attività su ${total} completate`, noTasksToday: 'Nessuna attività prevista per oggi', streak: (days) => `Serie di ${days} giorni`, streakNote: 'Saltare un giorno non annulla i progressi', actionsTitle: 'Cosa deve fare il genitore', nothingToDo: 'Al momento non c’è nulla da fare.', suggestionsWaiting: (count) => `${count} suggeriment${count === 1 ? 'o' : 'i'} per modificare le abitudini del bambino`, seeSuggestions: 'Vedi suggerimenti', building: (count, limit) => `Abitudini in costruzione (${count} di ${limit})`, lastSevenDays: 'Ultimi sette giorni', doneOfSeven: (done) => `${done} degli ultimi 7 giorni`, lean: { alone: 'fatto da solo', prompted: 'ha avuto bisogno di un promemoria', together: 'fatto con te' }, dayDone: 'fatto', dayMissed: 'non fatto', dayNone: 'non previsto', emptyTitle: 'Nessuna abitudine in costruzione', emptyBody: 'Scegli un’abitudine e imposta un segnale (stessa ora, stesso posto) per seguire i progressi del bambino.', emptyCta: 'Imposta un segnale per la prima abitudine', weeklyTitle: 'Rivedi questa settimana (5 minuti)', weeklyIntro: 'Una volta alla settimana, guardate indietro insieme invece di ricordarlo ogni giorno.', weeklyPraise: (title) => `Una cosa da lodare: la costanza con “${title}”.`, weeklyAdjust: (title) => `Una cosa da cambiare: “${title}” non è ancora costante. Prova a renderla più piccola o a cambiare orario.`, weeklyAdd: 'Le abitudini sono abbastanza costanti. Se vuoi, aggiungine una nuova (nel limite per questa età).', weeklyHold: 'Aspetta prima di aggiungere un’abitudine. Mantieni il ritmo per un’altra settimana.', weeklyNoData: 'Non ci sono ancora abbastanza dati per questa settimana. Segna per alcuni giorni come l’ha svolta il bambino per ricevere un commento.',
  },
  es: {
    chooseChild: 'Elegir un niño', todayOf: (name) => `El día de ${name}`, doneOfTotal: (done, total) => `${done} de ${total} tareas hechas`, noTasksToday: 'No hay tareas programadas para hoy', streak: (days) => `Racha de ${days} días`, streakNote: 'Perder un día no borra el progreso', actionsTitle: 'Tareas para los padres', nothingToDo: 'Ahora mismo no hay nada que hacer.', suggestionsWaiting: (count) => `${count} sugerencia${count === 1 ? '' : 's'} para ajustar los hábitos del niño`, seeSuggestions: 'Ver sugerencias', building: (count, limit) => `Hábitos en construcción (${count} de ${limit})`, lastSevenDays: 'Últimos siete días', doneOfSeven: (done) => `${done} de los últimos 7 días`, lean: { alone: 'lo hizo solo', prompted: 'necesitó un recordatorio', together: 'lo hizo contigo' }, dayDone: 'hecho', dayMissed: 'no hecho', dayNone: 'no programado', emptyTitle: 'Aún no hay hábitos en construcción', emptyBody: 'Elige un hábito y establece una señal (misma hora, mismo lugar) para empezar a seguir el progreso del niño.', emptyCta: 'Establecer una señal para el primer hábito', weeklyTitle: 'Revisar esta semana (5 minutos)', weeklyIntro: 'Una vez por semana, revisadlo juntos en lugar de recordar la tarea cada día.', weeklyPraise: (title) => `Algo que elogiar: la constancia con “${title}”.`, weeklyAdjust: (title) => `Algo que ajustar: “${title}” aún no es constante. Prueba a hacerlo más pequeño o cambia la hora.`, weeklyAdd: 'Los hábitos son bastante constantes. Si quieres, añade uno nuevo (sin superar el límite para esta edad).', weeklyHold: 'Espera antes de añadir un hábito nuevo. Mantén el ritmo una semana más.', weeklyNoData: 'No hay suficientes datos esta semana. Anota durante unos días cómo lo hizo el niño para recibir una valoración.',
  },
  zh: {
    chooseChild: '选择孩子', todayOf: (name) => `${name}的今天`, doneOfTotal: (done, total) => `已完成 ${done} / ${total} 项任务`, noTasksToday: '今天没有安排任务', streak: (days) => `连续 ${days} 天`, streakNote: '漏做一天不会抹去已有进步', actionsTitle: '需要家长处理', nothingToDo: '现在没有需要处理的事项。', suggestionsWaiting: (count) => `有 ${count} 条孩子习惯调整建议`, seeSuggestions: '查看建议', building: (count, limit) => `正在培养的习惯（${count} / ${limit}）`, lastSevenDays: '最近七天', doneOfSeven: (done) => `最近 7 天完成 ${done} 天`, lean: { alone: '孩子独立完成', prompted: '需要提醒', together: '和家长一起完成' }, dayDone: '已完成', dayMissed: '未完成', dayNone: '未安排', emptyTitle: '还没有正在培养的习惯', emptyBody: '选择一个习惯并设置提示（同一时间、同一地点），开始记录孩子的进步。', emptyCta: '为第一个习惯设置提示', weeklyTitle: '回顾本周（5 分钟）', weeklyIntro: '每周一起回顾一次，不必每天提醒。', weeklyPraise: (title) => `值得表扬的一点：坚持完成“${title}”。`, weeklyAdjust: (title) => `需要调整的一点：“${title}”还不够稳定。试着把任务变小或更换时间。`, weeklyAdd: '这些习惯已经比较稳定。如果愿意，可以添加一个新习惯（不要超过当前年龄上限）。', weeklyHold: '暂时不要添加新习惯，再保持一周节奏。', weeklyNoData: '本周数据还不够。记录孩子几天的完成方式，就能得到反馈。',
  },
  ja: {
    chooseChild: 'お子さまを選ぶ', todayOf: (name) => `${name}の今日`, doneOfTotal: (done, total) => `${total}件中${done}件完了`, noTasksToday: '今日は予定されたタスクがありません', streak: (days) => `${days}日連続`, streakNote: '1日できなくても、これまでの進歩は消えません', actionsTitle: '保護者がすること', nothingToDo: '今はすることがありません。', suggestionsWaiting: (count) => `習慣の調整案が${count}件あります`, seeSuggestions: '提案を見る', building: (count, limit) => `育てている習慣（${count} / ${limit}）`, lastSevenDays: '直近7日間', doneOfSeven: (done) => `直近7日間のうち${done}日完了`, lean: { alone: 'ひとりでできた', prompted: '声かけが必要', together: 'いっしょにできた' }, dayDone: 'できた', dayMissed: 'できなかった', dayNone: '予定なし', emptyTitle: 'まだ育てている習慣はありません', emptyBody: '習慣を選び、同じ時間・同じ場所の合図を設定して、お子さまの進歩を見守りましょう。', emptyCta: '最初の習慣に合図を設定', weeklyTitle: '今週を振り返る（5分）', weeklyIntro: '毎日声をかける代わりに、週1回いっしょに振り返りましょう。', weeklyPraise: (title) => `ほめたいこと：「${title}」を続けられています。`, weeklyAdjust: (title) => `調整したいこと：「${title}」はまだ安定していません。小さくするか時間を変えてみましょう。`, weeklyAdd: '習慣はかなり安定しています。よければ新しい習慣を1つ追加しましょう（年齢ごとの上限内で）。', weeklyHold: '新しい習慣の追加は少し待ちましょう。もう1週間リズムを続けます。', weeklyNoData: '今週はまだデータが足りません。数日間のお子さまの様子を記録すると、コメントを確認できます。',
  },
  ko: {
    chooseChild: '아이 선택', todayOf: (name) => `${name}의 오늘`, doneOfTotal: (done, total) => `${total}개 중 ${done}개 완료`, noTasksToday: '오늘 예정된 일이 없어요', streak: (days) => `${days}일 연속`, streakNote: '하루 빠져도 지금까지의 성장은 사라지지 않아요', actionsTitle: '부모님이 할 일', nothingToDo: '지금은 처리할 일이 없어요.', suggestionsWaiting: (count) => `아이 습관 조정 제안 ${count}개`, seeSuggestions: '제안 보기', building: (count, limit) => `만드는 중인 습관 (${count} / ${limit})`, lastSevenDays: '최근 7일', doneOfSeven: (done) => `최근 7일 중 ${done}일 완료`, lean: { alone: '혼자 해냈어요', prompted: '알림이 필요했어요', together: '부모님과 함께했어요' }, dayDone: '완료', dayMissed: '하지 않음', dayNone: '예정 없음', emptyTitle: '아직 만드는 중인 습관이 없어요', emptyBody: '습관을 고르고 같은 시간, 같은 장소에 신호를 정해 아이의 성장을 기록해 보세요.', emptyCta: '첫 습관에 신호 설정', weeklyTitle: '이번 주 돌아보기 (5분)', weeklyIntro: '매일 재촉하는 대신 일주일에 한 번 함께 돌아봐요.', weeklyPraise: (title) => `칭찬할 점: “${title}”을 꾸준히 했어요.`, weeklyAdjust: (title) => `조정할 점: “${title}”이 아직 꾸준하지 않아요. 더 작게 하거나 시간을 바꿔 보세요.`, weeklyAdd: '습관이 꽤 안정적이에요. 원한다면 새 습관 하나를 추가해 보세요 (연령별 한도 안에서).', weeklyHold: '새 습관 추가는 잠시 미뤄요. 한 주 더 리듬을 이어 가세요.', weeklyNoData: '이번 주 데이터가 아직 부족해요. 며칠 동안 아이가 어떻게 했는지 기록하면 의견을 확인할 수 있어요.',
  },
};

export function getParentTodayCopy(language: Language): ParentTodayCopy {
  return COPY[language] ?? COPY.en;
}
