import type { Language } from '@/types';
import type { ProfileCreateResult } from '@/lib/store/profile-actions';

type ProfileMutationCopy = {
  readonly deleteConfirm: (name: string) => string;
  readonly deleteError: string;
  readonly privacyError: string;
  readonly saveError: string;
  readonly saving: string;
  readonly mascotChecking: string;
  readonly mascotCheckError: string;
  readonly mascotCooldown: (date: string) => string;
};

const COPY: Record<Language, ProfileMutationCopy> = {
  vi: { deleteConfirm: (name) => `Xóa hồ sơ của ${name} và toàn bộ dữ liệu liên quan?`, deleteError: 'Không thể xóa hồ sơ. Vui lòng thử lại.', privacyError: 'Không thể lưu lựa chọn riêng tư. Vui lòng thử lại.', saveError: 'Không thể lưu hồ sơ của bé. Vui lòng thử lại.', saving: 'Đang lưu…', mascotChecking: 'Đang kiểm tra thời hạn đổi linh vật…', mascotCheckError: 'Chưa kiểm tra được thời hạn. Hãy đóng và thử lại.', mascotCooldown: (date) => `Bé có thể đổi linh vật tiếp từ ${date}. Vẫn có thể đổi màu.` },
  en: { deleteConfirm: (name) => `Delete ${name}'s profile and all related data?`, deleteError: 'The profile could not be deleted. Please try again.', privacyError: 'The privacy choice could not be saved. Please try again.', saveError: 'The child profile could not be saved. Please try again.', saving: 'Saving…', mascotChecking: 'Checking when you can change companions…', mascotCheckError: 'Could not check the date. Close and try again.', mascotCooldown: (date) => `You can change companions again from ${date}. You can still change the color.` },
  fr: { deleteConfirm: (name) => `Supprimer le profil de ${name} et toutes les données associées ?`, deleteError: 'Impossible de supprimer le profil. Réessayez.', privacyError: 'Impossible d’enregistrer ce choix de confidentialité.', saveError: 'Impossible d’enregistrer le profil. Réessayez.', saving: 'Enregistrement…', mascotChecking: 'Vérification du délai de changement…', mascotCheckError: 'Délai indisponible. Fermez et réessayez.', mascotCooldown: (date) => `Vous pourrez changer de compagnon à partir du ${date}. La couleur reste modifiable.` },
  de: { deleteConfirm: (name) => `Profil von ${name} und alle zugehörigen Daten löschen?`, deleteError: 'Das Profil konnte nicht gelöscht werden.', privacyError: 'Die Datenschutzeinstellung konnte nicht gespeichert werden.', saveError: 'Das Kinderprofil konnte nicht gespeichert werden.', saving: 'Wird gespeichert…', mascotChecking: 'Wechseltermin wird geprüft…', mascotCheckError: 'Termin nicht verfügbar. Bitte schließen und erneut versuchen.', mascotCooldown: (date) => `Ein neuer Begleiter ist ab ${date} möglich. Die Farbe kann weiterhin geändert werden.` },
  it: { deleteConfirm: (name) => `Eliminare il profilo di ${name} e tutti i dati correlati?`, deleteError: 'Impossibile eliminare il profilo.', privacyError: 'Impossibile salvare la scelta sulla privacy.', saveError: 'Impossibile salvare il profilo.', saving: 'Salvataggio…', mascotChecking: 'Verifica della data del prossimo cambio…', mascotCheckError: 'Data non disponibile. Chiudi e riprova.', mascotCooldown: (date) => `Puoi cambiare compagno dal ${date}. Puoi comunque cambiare il colore.` },
  es: { deleteConfirm: (name) => `¿Eliminar el perfil de ${name} y todos los datos relacionados?`, deleteError: 'No se pudo eliminar el perfil.', privacyError: 'No se pudo guardar la opción de privacidad.', saveError: 'No se pudo guardar el perfil.', saving: 'Guardando…', mascotChecking: 'Comprobando la próxima fecha de cambio…', mascotCheckError: 'No se pudo comprobar la fecha. Cierra e inténtalo de nuevo.', mascotCooldown: (date) => `Podrás cambiar de compañero a partir del ${date}. Aún puedes cambiar el color.` },
  zh: { deleteConfirm: (name) => `删除${name}的档案及所有相关数据？`, deleteError: '无法删除档案，请重试。', privacyError: '无法保存隐私选项，请重试。', saveError: '无法保存孩子档案，请重试。', saving: '正在保存…', mascotChecking: '正在查看下次更换时间…', mascotCheckError: '暂时无法查看时间，请关闭后重试。', mascotCooldown: (date) => `可从${date}起再次更换伙伴。颜色仍可修改。` },
  ja: { deleteConfirm: (name) => `${name}のプロフィールと関連データをすべて削除しますか？`, deleteError: 'プロフィールを削除できませんでした。', privacyError: 'プライバシー設定を保存できませんでした。', saveError: 'プロフィールを保存できませんでした。', saving: '保存中…', mascotChecking: '次に変更できる日時を確認中…', mascotCheckError: '日時を確認できません。閉じて再試行してください。', mascotCooldown: (date) => `${date}から仲間を再び変更できます。色は変更できます。` },
  ko: { deleteConfirm: (name) => `${name}의 프로필과 관련 데이터를 모두 삭제할까요?`, deleteError: '프로필을 삭제하지 못했습니다.', privacyError: '개인정보 설정을 저장하지 못했습니다.', saveError: '아이 프로필을 저장하지 못했습니다.', saving: '저장 중…', mascotChecking: '다음 변경 가능 시간을 확인하는 중…', mascotCheckError: '시간을 확인할 수 없습니다. 닫고 다시 시도하세요.', mascotCooldown: (date) => `${date}부터 친구를 다시 바꿀 수 있습니다. 색상은 계속 바꿀 수 있습니다.` },
};

export function getProfileMutationCopy(language: Language): ProfileMutationCopy {
  return COPY[language];
}

const ERROR_COPY: Record<Language, Record<Exclude<ProfileCreateResult, { success: true }>['code'], string>> = {
  vi: { authentication_required: 'Phiên đăng nhập đã hết hạn. Hãy đăng nhập lại.', family_membership_required: 'Chưa tìm thấy gia đình của bạn. Hãy tải lại trang.', invalid_profile_mutation: 'Một số thông tin chưa hợp lệ. Hãy kiểm tra và thử lại.', child_limit_reached: 'Gói hiện tại đã đạt giới hạn số bé. Hãy chọn gói phù hợp để thêm hồ sơ.', profile_not_found: 'Không tìm thấy hồ sơ cần cập nhật. Hãy tải lại trang.', profile_conflict: 'Yêu cầu này đã được xử lý. Hãy tải lại dữ liệu gia đình.', profile_service_unavailable: 'Kết nối đồng bộ đang gián đoạn. Hãy thử lại sau ít phút.', profile_mutation_failed: 'Chưa lưu được hồ sơ. Hãy thử lại.' },
  en: { authentication_required: 'Your session has expired. Please sign in again.', family_membership_required: 'Your family could not be found. Reload the page.', invalid_profile_mutation: 'Some details are invalid. Check them and try again.', child_limit_reached: 'Your plan has reached its child limit. Choose a suitable plan to add another profile.', profile_not_found: 'The profile could not be found. Reload the page.', profile_conflict: 'This request was already handled. Refresh your family data.', profile_service_unavailable: 'Cloud sync is temporarily unavailable. Try again in a few minutes.', profile_mutation_failed: 'The profile could not be saved. Please try again.' },
  fr: { authentication_required: 'Votre session a expiré. Reconnectez-vous.', family_membership_required: 'Votre famille est introuvable. Rechargez la page.', invalid_profile_mutation: 'Certaines informations sont invalides.', child_limit_reached: 'Votre formule a atteint sa limite de profils.', profile_not_found: 'Profil introuvable. Rechargez la page.', profile_conflict: 'Cette demande a déjà été traitée. Actualisez les données.', profile_service_unavailable: 'La synchronisation est momentanément indisponible.', profile_mutation_failed: 'Impossible d’enregistrer le profil.' },
  de: { authentication_required: 'Ihre Sitzung ist abgelaufen. Bitte erneut anmelden.', family_membership_required: 'Ihre Familie wurde nicht gefunden. Seite neu laden.', invalid_profile_mutation: 'Einige Angaben sind ungültig.', child_limit_reached: 'Ihr Tarif hat die Kindergrenze erreicht.', profile_not_found: 'Profil nicht gefunden. Seite neu laden.', profile_conflict: 'Diese Anfrage wurde bereits verarbeitet. Daten neu laden.', profile_service_unavailable: 'Die Cloud-Synchronisierung ist vorübergehend nicht verfügbar.', profile_mutation_failed: 'Das Profil konnte nicht gespeichert werden.' },
  it: { authentication_required: 'La sessione è scaduta. Accedi di nuovo.', family_membership_required: 'Famiglia non trovata. Ricarica la pagina.', invalid_profile_mutation: 'Alcuni dati non sono validi.', child_limit_reached: 'Il piano ha raggiunto il limite di profili.', profile_not_found: 'Profilo non trovato. Ricarica la pagina.', profile_conflict: 'Questa richiesta è già stata elaborata. Aggiorna i dati.', profile_service_unavailable: 'La sincronizzazione cloud non è al momento disponibile.', profile_mutation_failed: 'Impossibile salvare il profilo.' },
  es: { authentication_required: 'La sesión ha caducado. Inicia sesión de nuevo.', family_membership_required: 'No se encontró tu familia. Recarga la página.', invalid_profile_mutation: 'Algunos datos no son válidos.', child_limit_reached: 'Tu plan alcanzó el límite de perfiles.', profile_not_found: 'No se encontró el perfil. Recarga la página.', profile_conflict: 'Esta solicitud ya se procesó. Actualiza los datos.', profile_service_unavailable: 'La sincronización en la nube no está disponible temporalmente.', profile_mutation_failed: 'No se pudo guardar el perfil.' },
  zh: { authentication_required: '登录已过期，请重新登录。', family_membership_required: '找不到您的家庭，请刷新页面。', invalid_profile_mutation: '部分信息无效，请检查后重试。', child_limit_reached: '当前方案已达到孩子档案上限。', profile_not_found: '找不到该档案，请刷新页面。', profile_conflict: '该请求已处理，请刷新家庭数据。', profile_service_unavailable: '云同步暂时不可用，请稍后重试。', profile_mutation_failed: '无法保存孩子档案，请重试。' },
  ja: { authentication_required: 'セッションの有効期限が切れました。再度ログインしてください。', family_membership_required: 'ご家族が見つかりません。ページを再読み込みしてください。', invalid_profile_mutation: '入力内容の一部が無効です。', child_limit_reached: '現在のプランのプロフィール上限に達しました。', profile_not_found: 'プロフィールが見つかりません。再読み込みしてください。', profile_conflict: 'このリクエストは処理済みです。データを更新してください。', profile_service_unavailable: 'クラウド同期は一時的に利用できません。', profile_mutation_failed: 'プロフィールを保存できませんでした。' },
  ko: { authentication_required: '로그인 세션이 만료되었습니다. 다시 로그인해 주세요.', family_membership_required: '가족을 찾을 수 없습니다. 페이지를 새로고침해 주세요.', invalid_profile_mutation: '일부 정보가 올바르지 않습니다.', child_limit_reached: '현재 요금제의 아이 프로필 한도에 도달했습니다.', profile_not_found: '프로필을 찾을 수 없습니다. 새로고침해 주세요.', profile_conflict: '이미 처리된 요청입니다. 가족 데이터를 새로고침해 주세요.', profile_service_unavailable: '클라우드 동기화를 일시적으로 사용할 수 없습니다.', profile_mutation_failed: '아이 프로필을 저장하지 못했습니다.' },
};

export function getProfileMutationError(
  language: Language,
  result: Exclude<ProfileCreateResult, { success: true }>,
): string {
  const message = ERROR_COPY[language][result.code];
  return result.correlationId ? `${message} Mã hỗ trợ: ${result.correlationId}` : message;
}
