-- Generated from the shipped legacy habit catalog and all supported locales.
-- Only full template content and settings receive an ID; edited rows stay untouched.
begin;

with catalog (legacy_template_id, title, description, category, icon, points, time_of_day, duration_minutes, requires_approval) as (
  values
  ('WIT-CAP-01', 'Faire le lit proprement', 'Assumez la responsabilité de garder la chambre bien rangée.', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', 'Gánh vác: Tự gấp chăn màn & sắp xếp giường', 'Gánh vác trách nhiệm giữ gìn không gian sống ngăn nắp sạch đẹp', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', 'Haz la cama ordenadamente', 'Asuma la responsabilidad de mantener el dormitorio ordenado.', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', 'Machen Sie das Bett ordentlich', 'Übernehmen Sie die Verantwortung für Ordnung im Schlafzimmer.', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', 'Make the bed neatly', 'Take responsibility for keeping the bedroom tidy.', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', 'Rifai il letto in modo ordinato', 'Assumersi la responsabilità di mantenere in ordine la camera da letto.', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', 'ベッドをきれいに整える', '責任を持って寝室を整理整頓してください。', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', '把床铺收拾整齐', '负责保持卧室整洁。', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-01', '침대를 깔끔하게 정리하다', '침실을 깔끔하게 유지하는 데 책임을 져야 합니다.', 'capacity', '🛏️', 15, 'morning', 0, false),
  ('WIT-CAP-02', 'Coloque los juguetes cuidadosamente en la canasta después de jugar.', 'Evite que se dejen juguetes por ahí.', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', 'Kiên trì: Luyện tập nhạc cụ / vẽ tranh / viết chữ', 'Rèn luyện tính kiên nhẫn, không bỏ cuộc giữa chừng', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', 'Legen Sie die Spielsachen nach dem Spielen ordentlich in den Korb', 'Verhindern Sie, dass Spielzeug herumliegt.', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', 'Metti i giocattoli ordinatamente nel cestino dopo il gioco', 'Evita che i giocattoli vengano lasciati in giro.', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', 'Put toys neatly in the basket after play', 'Keep toys from being left around.', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', 'Rangez soigneusement les jouets dans le panier après avoir joué', 'Empêchez les jouets de rester à proximité.', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', '玩完后将玩具整齐地放入篮子里', '不要将玩具留在周围。', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', '遊んだ後はおもちゃをかごにきちんと入れてください', 'おもちゃをその辺に放置しないようにしましょう。', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-02', '놀이 후에는 장난감을 바구니에 가지런히 담아두세요', '장난감이 주변에 남지 않도록 하세요.', 'capacity', '🎨', 20, 'afternoon', 20, false),
  ('WIT-CAP-03', 'Aidez à essuyer la table à manger après le repas', 'Aidez à garder la maison familiale propre.', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', 'Aiuta a pulire il tavolo da pranzo dopo il pasto', 'Aiuta a mantenere pulita la casa della famiglia.', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', 'Ayuda a limpiar la mesa del comedor después de la comida.', 'Ayude a mantener limpia la casa familiar.', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', 'Dũng cảm thay đổi: Từ bỏ 1 thói quen chưa tốt', 'Tự giác hạn chế xem tivi, bớt mè nheo, kiên quyết thay đổi vì sự tiến bộ', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', 'Helfen Sie mit, den Esstisch nach dem Essen abzuwischen', 'Helfen Sie mit, das Zuhause der Familie sauber zu halten.', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', 'Help wipe the dining table after the meal', 'Help keep the family home clean.', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', '食後にダイニングテーブルを拭くのを手伝ってください', '家族の家をきれいに保つのに役立ちます。', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', '饭后帮忙擦餐桌', '帮助保持家庭清洁。', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-CAP-03', '식사 후에 식탁을 닦는 것을 도와주세요', '가족의 집을 깨끗하게 유지하도록 도와주세요.', 'capacity', '🚀', 30, 'evening', 0, true),
  ('WIT-GIV-01', 'Freundliches Lächeln: Begrüßen Sie die Familie herzlich', 'Lächle und grüße Großeltern und Eltern jeden Morgen.', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', 'Kind smile: Greet family warmly', 'Smile and greet grandparents and parents each morning.', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', 'Nhan thí: Nở nụ cười chào đón người thân', 'Bố thí nụ cười tươi tắn mỗi sáng gặp ông bà, bố mẹ và thầy cô', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', 'Sonrisa amable: Salude calurosamente a la familia.', 'Sonríe y saluda a los abuelos y padres cada mañana.', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', 'Sorriso gentile: saluta calorosamente la famiglia', 'Sorridi e saluta i nonni e i genitori ogni mattina.', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', 'Sourire aimable : Saluez chaleureusement la famille', 'Souriez et saluez les grands-parents et les parents chaque matin.', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', '亲切的微笑：热情地问候家人', '每天早上微笑着向祖父母和父母打招呼。', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', '優しい笑顔：家族を温かく迎えます', '毎朝、祖父母や両親に笑顔で挨拶しましょう。', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-01', '친절한 미소: 가족에게 따뜻하게 인사하기', '매일 아침 조부모님과 부모님들에게 미소를 지으며 인사하십시오.', 'giving', '😊', 10, 'morning', 0, false),
  ('WIT-GIV-02', 'Encouraging words: Offer praise and thanks', 'Use kind words that build confidence.', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', 'Ermutigende Worte: Loben und danken Sie', 'Verwenden Sie freundliche Worte, die Vertrauen aufbauen.', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', 'Mots encourageants : offrez des éloges et des remerciements', 'Utilisez des mots gentils qui renforcent la confiance.', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', 'Nhãn thí: Ánh mắt trìu mến & nhìn nhận điểm tốt của bạn', 'Bố thí ánh mắt chứa đựng sự công nhận và yêu thương dành cho mọi người', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', 'Palabras de aliento: Ofrezca elogios y agradecimiento.', 'Utilice palabras amables que generen confianza.', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', 'Parole incoraggianti: offri lodi e ringraziamenti', 'Usa parole gentili che creano fiducia.', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', '励ましの言葉：褒めたり感謝したりする', '自信を高めるような優しい言葉を使いましょう。', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', '鼓励的话：表扬和感谢', '使用友善的话语来建立信心。', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-02', '격려의 말: 칭찬과 감사를 드립니다', '자신감을 키우는 친절한 말을 사용하십시오.', 'giving', '👀', 15, 'anytime', 0, false),
  ('WIT-GIV-03', 'Encouraging words: Offer praise and thanks', 'Use kind words that build confidence.', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', 'Ermutigende Worte: Loben und danken Sie', 'Verwenden Sie freundliche Worte, die Vertrauen aufbauen.', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', 'Mots encourageants : offrez des éloges et des remerciements', 'Utilisez des mots gentils qui renforcent la confiance.', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', 'Ngôn thí: Nói lời ái ngữ, khích lệ & khen ngợi', 'Dùng lời nói mang lại niềm tin, hy vọng, khen ngợi và động viên bạn bè', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', 'Palabras de aliento: Ofrezca elogios y agradecimiento.', 'Utilice palabras amables que generen confianza.', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', 'Parole incoraggianti: offri lodi e ringraziamenti', 'Usa parole gentili che creano fiducia.', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', '励ましの言葉：褒めたり感謝したりする', '自信を高めるような優しい言葉を使いましょう。', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', '鼓励的话：表扬和感谢', '使用友善的话语来建立信心。', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-03', '격려의 말: 칭찬과 감사를 드립니다', '자신감을 키우는 친절한 말을 사용하십시오.', 'giving', '🗣️', 15, 'anytime', 0, false),
  ('WIT-GIV-04', 'Dankbarkeit: Sagen Sie jeden Abend drei Danksagungen', 'Pflegen Sie eine tägliche Gewohnheit der Dankbarkeit.', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', 'Gratitud: comparte tres agradecimientos cada noche.', 'Fomente un hábito diario de gratitud.', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', 'Gratitude: Share three appreciations each night', 'Nurture a daily habit of gratitude.', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', 'Gratitude : partagez trois appréciations chaque soir', 'Entretenez une habitude quotidienne de gratitude.', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', 'Gratitudine: condividi tre apprezzamenti ogni sera', 'Coltiva un’abitudine quotidiana alla gratitudine.', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', 'Tâm thí: Trân trọng biết ơn người khác giúp mình', 'Bày tỏ lòng biết ơn chân thành trước bữa ăn và sự chăm sóc của gia đình', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', '感恩：每晚分享三个感激之情', '养成每天感恩的习惯。', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', '感謝: 毎晩3つの感謝を共有する', '日々の感謝の習慣を育みます。', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-04', '감사: 매일 밤 세 가지 감사의 말을 나눕니다.', '매일 감사하는 습관을 기르십시오.', 'giving', '💖', 15, 'evening', 0, false),
  ('WIT-GIV-05', 'Phòng thí: Bao dung & tha thứ khi bạn vô ý làm phiền', 'Không giận dỗi, vui vẻ tha thứ và thông cảm khi bạn lỡ làm hỏng việc', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', 'Tolerance: Forgive a friend’s mistake', 'Let go of anger and get along cheerfully.', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', 'Tolerancia: perdona el error de un amigo', 'Deja ir la ira y llévate bien con alegría.', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', 'Toleranz: Verzeihen Sie den Fehler eines Freundes', 'Lassen Sie die Wut los und kommen Sie fröhlich miteinander aus.', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', 'Tolleranza: perdona l’errore di un amico', 'Lascia andare la rabbia e vai avanti allegramente.', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', 'Tolérance : pardonner l''erreur d''un ami', 'Abandonnez la colère et entendez-vous joyeusement.', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', '宽容：原谅朋友的错误', '放下愤怒，愉快地相处。', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', '寛容：友人の間違いを許す', '怒りを手放して明るく付き合いましょう。', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-05', '관용: 친구의 실수를 용서한다', '분노를 버리고 유쾌하게 지내십시오.', 'giving', '🕊️', 20, 'anytime', 0, false),
  ('WIT-GIV-06', 'Des mains serviables : aider les parents dans les tâches ménagères', 'Soutenir la famille par des actions concrètes.', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', 'Helpful hands: Help parents with housework', 'Support the family through practical action.', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', 'Hilfreiche Hände: Helfen Sie Eltern bei der Hausarbeit', 'Unterstützen Sie die Familie durch praktisches Handeln.', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', 'Mani utili: Aiuta i genitori nelle faccende domestiche', 'Sostenere la famiglia attraverso azioni concrete.', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', 'Manos útiles: ayudan a los padres con las tareas del hogar', 'Apoyar a la familia a través de acciones prácticas.', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', 'Thân thí: Tận tay giúp đỡ xách đồ, dọn dẹp', 'Hành động thực tế hỗ trợ bố mẹ xách túi đồ, cất ghế, phụ việc nhà', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', '帮手：帮助父母做家务', '用实际行动支持家人。', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', '役立つ手助け：両親の家事を手伝う', '実践的な行動を通じて家族をサポートします。', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-06', '도움의 손길: 부모님의 집안일을 도와주세요', '실제적인 행동을 통해 가족을 지원하십시오.', 'giving', '🤝', 15, 'evening', 0, false),
  ('WIT-GIV-07', 'Amabilidad: Comparte algo delicioso.', 'Piensa en las necesidades de los demás.', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', 'Freundlichkeit: Teilen Sie etwas Leckeres', 'Denken Sie an die Bedürfnisse anderer.', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', 'Gentilezza: condividi qualcosa di delizioso', 'Pensa ai bisogni degli altri.', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', 'Gentillesse : partagez quelque chose de délicieux', 'Pensez aux besoins des autres.', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', 'Kindness: Share something delicious', 'Think about the needs of others.', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', 'Tọa thí: Nhường chỗ & chia sẻ kinh nghiệm cho em', 'Nhường đồ chơi cho em hoặc hướng dẫn bạn làm một việc bé đã biết làm', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', '優しさ：おいしいものをシェアする', '他の人のニーズについて考えてみましょう。', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', '善良：分享好吃的东西', '想想别人的需要。', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-GIV-07', '친절: 맛있는 것을 나눠주세요', '다른 사람들의 필요 사항에 대해 생각해 보십시오.', 'giving', '🪑', 20, 'anytime', 0, false),
  ('WIT-MIN-01', 'Dankbarkeit: Sagen Sie jeden Abend drei Danksagungen', 'Pflegen Sie eine tägliche Gewohnheit der Dankbarkeit.', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', 'Gratitud: comparte tres agradecimientos cada noche.', 'Fomente un hábito diario de gratitud.', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', 'Gratitude: Share three appreciations each night', 'Nurture a daily habit of gratitude.', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', 'Gratitude : partagez trois appréciations chaque soir', 'Entretenez une habitude quotidienne de gratitude.', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', 'Gratitudine: condividi tre apprezzamenti ogni sera', 'Coltiva un’abitudine quotidiana alla gratitudine.', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', 'Tâm thái An vui: Mỉm cười bắt đầu ngày mới', 'Giữ tâm trạng bình an, không cáu gắt hay mè nheo buổi sáng', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', '感恩：每晚分享三个感激之情', '养成每天感恩的习惯。', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', '感謝: 毎晩3つの感謝を共有する', '日々の感謝の習慣を育みます。', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-01', '감사: 매일 밤 세 가지 감사의 말을 나눕니다.', '매일 감사하는 습관을 기르십시오.', 'mindset', '🌈', 15, 'morning', 0, false),
  ('WIT-MIN-02', 'Tolerance: Forgive a friend’s mistake', 'Let go of anger and get along cheerfully.', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', 'Tolerancia: perdona el error de un amigo', 'Deja ir la ira y llévate bien con alegría.', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', 'Toleranz: Verzeihen Sie den Fehler eines Freundes', 'Lassen Sie die Wut los und kommen Sie fröhlich miteinander aus.', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', 'Tolleranza: perdona l’errore di un amico', 'Lascia andare la rabbia e vai avanti allegramente.', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', 'Tolérance : pardonner l''erreur d''un ami', 'Abandonnez la colère et entendez-vous joyeusement.', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', 'Tâm thái Bao dung: Tôn trọng sự khác biệt của bạn', 'Chấp nhận và tôn trọng sở thích riêng của bạn bè, không chê bai', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', '宽容：原谅朋友的错误', '放下愤怒，愉快地相处。', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', '寛容：友人の間違いを許す', '怒りを手放して明るく付き合いましょう。', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-02', '관용: 친구의 실수를 용서한다', '분노를 버리고 유쾌하게 지내십시오.', 'mindset', '🌿', 20, 'anytime', 0, false),
  ('WIT-MIN-03', 'Freundliches Lächeln: Begrüßen Sie die Familie herzlich', 'Beginnen Sie den Tag mit einem Lächeln.', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', 'Kind smile: Greet family warmly', 'Start the day with a smile.', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', 'Sonrisa amable: Salude calurosamente a la familia.', 'Empieza el día con una sonrisa.', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', 'Sorriso gentile: saluta calorosamente la famiglia', 'Inizia la giornata con un sorriso.', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', 'Sourire aimable : Saluez chaleureusement la famille', 'Commencez la journée avec le sourire.', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', 'Trân trọng biết ơn: Viết/Nói 3 điều biết ơn mỗi ngày', 'Trước khi đi ngủ, kể cho bố mẹ nghe 3 điều bé cảm thấy biết ơn hôm nay', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', '亲切的微笑：热情地问候家人', '以微笑开始新的一天。', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', '優しい笑顔：家族を温かく迎えます', '笑顔で一日を始めましょう。', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-MIN-03', '친절한 미소: 가족에게 따뜻하게 인사하기', '웃는 얼굴로 하루를 시작해 보세요.', 'mindset', '📝', 20, 'evening', 0, false),
  ('WIT-NUT-01', 'Lavarsi entrambe le mani con sapone prima di mangiare', 'Elimina i germi prima di ogni pasto.', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', 'Lávese ambas manos con jabón antes de comer.', 'Limpie los gérmenes antes de cada comida.', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', 'Rửa sạch hai tay bằng xà phòng trước khi vào bàn ăn', 'Vệ sinh bàn tay sạch khuẩn để ăn ngon và bảo vệ đường tiêu hóa khỏe mạnh', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', 'Se laver les deux mains avec du savon avant de manger', 'Nettoyez les germes avant chaque repas.', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', 'Waschen Sie vor dem Essen beide Hände mit Seife', 'Entfernen Sie Keime vor jeder Mahlzeit.', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', 'Wash both hands with soap before eating', 'Clean away germs before every meal.', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', '吃饭前用肥皂洗手', '每餐前清除细菌。', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', '食べる前に両手を石鹸で洗いましょう', '毎食前に細菌を除去します。', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-01', '식사 전 비누로 양손을 씻는다', '매 식사 전에 세균을 제거하십시오.', 'nutrition', '🧼', 10, 'afternoon', 1, false),
  ('WIT-NUT-02', 'Invita la famiglia a mangiare prima del pasto', 'Invitare educatamente nonni e genitori a partecipare al pasto.', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', 'Invitar a la familia a comer antes de la comida.', 'Invite cortésmente a los abuelos y padres a unirse a la comida.', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', 'Invite the family to eat before the meal', 'Politely invite grandparents and parents to join the meal.', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', 'Inviter la famille à manger avant le repas', 'Invitez poliment les grands-parents et les parents à se joindre au repas.', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', 'Laden Sie die Familie vor dem Essen zum Essen ein', 'Laden Sie Großeltern und Eltern höflich zum Essen ein.', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', 'Phẩm chất Lễ: Khoanh tay mời cả nhà trước khi ăn cơm', 'Lễ phép mời ông bà, bố mẹ và anh chị em cùng dùng bữa', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', '家族を食事の前に食事に招待する', '祖父母や両親を丁寧に食事に招待しましょう。', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', '饭前请家人吃饭', '礼貌地邀请祖父母和父母一起用餐。', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-02', '식사 전에 가족을 초대하여 식사를 하세요.', '조부모와 부모를 정중하게 식사에 초대하십시오.', 'nutrition', '🥢', 15, 'afternoon', 0, false),
  ('WIT-NUT-03', 'Asseyez-vous correctement et mangez sans téléphone ni télévision', 'Concentrez-vous sur la nourriture et discutez avec la famille.', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', 'Siediti correttamente e mangia senza telefono o TV', 'Concentrati sul cibo e parla con la famiglia.', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', 'Sit properly and eat without a phone or TV', 'Focus on the food and talk with the family.', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', 'Sitzen Sie richtig und essen Sie ohne Telefon oder Fernseher', 'Konzentrieren Sie sich auf das Essen und sprechen Sie mit der Familie.', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', 'Siéntate correctamente y come sin teléfono ni televisión', 'Concéntrate en la comida y habla con la familia.', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', 'Văn hóa bàn ăn: Ngồi ngay ngắn, không xem điện thoại / TV', 'Tập trung nhai kỹ, cảm nhận vị ngon món ăn và trò chuyện vui vẻ cùng gia đình', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', '正确坐姿吃饭，不看手机或电视', '专注于食物并与家人交谈。', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', '電話やテレビを使わずに正しく座って食事をする', '食事に集中して家族と会話しましょう。', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-03', '전화기나 TV 없이 바르게 앉아서 식사하기', '음식에 집중하고 가족과 이야기를 나눠보세요.', 'nutrition', '📵', 20, 'evening', 0, false),
  ('WIT-NUT-04', 'Come prolijamente y termina las verduras.', 'Prueba todos los alimentos y mantén la mesa limpia.', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', 'Eat neatly and finish the vegetables', 'Try every food and keep the table clean.', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', 'Essen Sie ordentlich und essen Sie das Gemüse fertig', 'Probieren Sie jedes Essen und halten Sie den Tisch sauber.', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', 'Mangez soigneusement et terminez les légumes', 'Essayez tous les aliments et gardez la table propre.', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', 'Mangia bene e finisci le verdure', 'Prova ogni cibo e mantieni la tavola pulita.', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', 'Tự xúc ăn gọn gàng, không để rơi vãi thức ăn ra bàn', 'Giữ bàn ăn sạch sẽ, không bốc tay hay vung vãi cơm thức ăn', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', '吃得整齐，把蔬菜吃完', '尝试每种食物并保持桌子清洁。', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', '野菜もしっかり食べて完食', 'あらゆる食べ物を試して、テーブルをきれいに保ちましょう。', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-04', '깔끔하게 먹고 야채도 마무리', '모든 음식을 맛보고 식탁을 깨끗하게 유지하세요.', 'nutrition', '🍚', 15, 'afternoon', 0, false),
  ('WIT-NUT-05', 'Come sin mamparas y termina las verduras', 'Protege el estómago y los ojos.', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', 'Eat without screens and finish the vegetables', 'Protect the stomach and eyes.', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', 'Essen Sie ohne Siebe und essen Sie das Gemüse fertig', 'Magen und Augen schützen.', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', 'Mangez sans écran et terminez les légumes', 'Protéger l''estomac et les yeux.', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', 'Mangia senza schermi e finisci le verdure', 'Proteggi lo stomaco e gli occhi.', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', 'Ăn đa dạng các món & vui vẻ ăn hết phần rau xanh', 'Không kén ăn, bổ sung nhiều vitamin và chất xơ từ rau củ tươi ngon', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', 'スクリーンなしで食べて野菜を完食する', '胃と目を保護します。', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', '吃饭不用屏风，把蔬菜吃完', '保护胃和眼睛。', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-05', '스크린 없이 먹고 야채를 마무리하세요', '위와 눈을 보호하십시오.', 'nutrition', '🥦', 20, 'evening', 0, false),
  ('WIT-NUT-06', 'Hände waschen und die Familie zum Essen einladen', 'Üben Sie höfliche Tischmanieren.', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', 'Lavarse las manos e invitar a la familia a comer.', 'Practique buenos modales en la mesa.', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', 'Lavarsi le mani e invitare la famiglia a mangiare', 'Pratica buone maniere a tavola.', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', 'Nhai kỹ no lâu, không ngậm thức ăn trong miệng', 'Nhai đều đặn, nuốt nhẹ nhàng, ăn xong bữa đúng giờ không quá 30 phút', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', 'Se laver les mains et inviter la famille à manger', 'Adoptez des manières polies à table.', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', 'Wash hands and invite the family to eat', 'Practice polite table manners.', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', '手を洗い、家族を食事に招待する', '礼儀正しいテーブルマナーを実践しましょう。', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', '洗手并邀请家人吃饭', '练习礼貌的餐桌礼仪。', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-06', '손을 씻고 가족을 초대하여 식사하세요', '예의바른 테이블 매너를 실천하세요.', 'nutrition', '😋', 15, 'afternoon', 0, false),
  ('WIT-NUT-07', 'Metti i piatti nel lavandino dopo aver mangiato', 'Costruisci l''indipendenza ripulendo dopo il pasto.', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', 'Mettre la vaisselle dans l''évier après avoir mangé', 'Développez votre indépendance en faisant le ménage après le repas.', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', 'Pon los platos en el fregadero después de comer.', 'Desarrolle su independencia limpiando después de la comida.', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', 'Put dishes in the sink after eating', 'Build independence by cleaning up after the meal.', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', 'Stellen Sie das Geschirr nach dem Essen in die Spüle', 'Bauen Sie Unabhängigkeit auf, indem Sie nach dem Essen aufräumen.', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', 'Thân thí: Tự bưng bát đĩa cất vào bồn rửa sau khi ăn', 'Chủ động dọn phần ăn của mình, rèn luyện tính tự lập và phụ giúp mẹ', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', '吃完饭后将餐具放入水槽', '通过饭后清理来建立独立性。', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', '食後は食器をシンクに置く', '食後の片づけをすることで自立心を育みます。', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-07', '식사 후에는 그릇을 싱크대에 놓으세요.', '식사 후 청소를 통해 독립성을 키워보세요.', 'nutrition', '🥣', 15, 'evening', 0, false),
  ('WIT-NUT-08', 'Aidez à essuyer la table à manger après le repas', 'Aidez à garder la maison familiale propre.', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', 'Aiuta a pulire il tavolo da pranzo dopo il pasto', 'Aiuta a mantenere pulita la casa della famiglia.', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', 'Ayuda a limpiar la mesa del comedor después de la comida.', 'Ayude a mantener limpia la casa familiar.', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', 'Helfen Sie mit, den Esstisch nach dem Essen abzuwischen', 'Helfen Sie mit, das Zuhause der Familie sauber zu halten.', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', 'Help wipe the dining table after the meal', 'Help keep the family home clean.', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', 'Lấy khăn sạch lau bàn ăn giúp mẹ sau bữa cơm', 'Lau sạch bề mặt bàn ăn, để lại không gian sạch bong cho cả gia đình', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', '食後にダイニングテーブルを拭くのを手伝ってください', '家族の家をきれいに保つのに役立ちます。', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', '饭后帮忙擦餐桌', '帮助保持家庭清洁。', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-08', '식사 후에 식탁을 닦는 것을 도와주세요', '가족의 집을 깨끗하게 유지하도록 도와주세요.', 'nutrition', '🧽', 15, 'evening', 0, false),
  ('WIT-NUT-09', 'Acuéstate antes de las 21:30', 'Apoye el crecimiento saludable durmiendo lo suficiente.', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', 'Gehen Sie vor 21:30 Uhr zu Bett', 'Unterstützen Sie ein gesundes Wachstum mit ausreichend Schlaf.', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', 'Go to bed before 9:30 PM', 'Support healthy growth with enough sleep.', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', 'Se coucher avant 21h30', 'Favorisez une croissance saine avec suffisamment de sommeil.', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', 'Uống đủ nước ấm sau bữa ăn, không uống nước ngọt có ga', 'Chọn nước lọc hoặc nước ấm thanh lọc cơ thể thay vì nước có đường', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', 'Vai a letto prima delle 21:30', 'Supporta una crescita sana con un sonno sufficiente.', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', '午後9時30分までに就寝してください', '十分な睡眠で健やかな成長をサポートします。', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', '晚上 9:30 之前上床睡觉', '通过充足的睡眠支持健康成长。', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-NUT-09', '오후 9시 30분 이전에 잠자리에 드세요', '충분한 수면으로 건강한 성장을 돕습니다.', 'nutrition', '💧', 10, 'afternoon', 0, false),
  ('WIT-PER-01', 'Freundliches Lächeln: Begrüßen Sie die Familie herzlich', 'Lächle und grüße Großeltern und Eltern jeden Morgen.', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', 'Kind smile: Greet family warmly', 'Smile and greet grandparents and parents each morning.', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', 'Nhân cách Vui vẻ: Mang lại tiếng cười cho gia đình', 'Kể chuyện cười, hát vui vẻ hoặc hỏi thăm để bố mẹ vui sau giờ làm', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', 'Sonrisa amable: Salude calurosamente a la familia.', 'Sonríe y saluda a los abuelos y padres cada mañana.', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', 'Sorriso gentile: saluta calorosamente la famiglia', 'Sorridi e saluta i nonni e i genitori ogni mattina.', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', 'Sourire aimable : Saluez chaleureusement la famille', 'Souriez et saluez les grands-parents et les parents chaque matin.', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', '亲切的微笑：热情地问候家人', '每天早上微笑着向祖父母和父母打招呼。', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', '優しい笑顔：家族を温かく迎えます', '毎朝、祖父母や両親に笑顔で挨拶しましょう。', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-01', '친절한 미소: 가족에게 따뜻하게 인사하기', '매일 아침 조부모님과 부모님들에게 미소를 지으며 인사하십시오.', 'personality', '😄', 15, 'evening', 0, false),
  ('WIT-PER-02', 'Encouraging words: Offer praise and thanks', 'Use kind words that build confidence.', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', 'Ermutigende Worte: Loben und danken Sie', 'Verwenden Sie freundliche Worte, die Vertrauen aufbauen.', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', 'Mots encourageants : offrez des éloges et des remerciements', 'Utilisez des mots gentils qui renforcent la confiance.', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', 'Nhân cách Khiêm tốn: Lắng nghe không ngắt lời', 'Biết ghi nhận thành tích của người khác và khiêm tốn học hỏi', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', 'Palabras de aliento: Ofrezca elogios y agradecimiento.', 'Utilice palabras amables que generen confianza.', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', 'Parole incoraggianti: offri lodi e ringraziamenti', 'Usa parole gentili che creano fiducia.', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', '励ましの言葉：褒めたり感謝したりする', '自信を高めるような優しい言葉を使いましょう。', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', '鼓励的话：表扬和感谢', '使用友善的话语来建立信心。', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-02', '격려의 말: 칭찬과 감사를 드립니다', '자신감을 키우는 친절한 말을 사용하십시오.', 'personality', '👂', 15, 'anytime', 0, false),
  ('WIT-PER-03', 'Admettez vos erreurs et apportez des changements sincères', 'Grandissez grâce à l’honnêteté et au courage.', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', 'Admit mistakes and make sincere changes', 'Grow through honesty and courage.', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', 'Admitir errores y hacer cambios sinceros.', 'Crecer a través de la honestidad y el coraje.', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', 'Ammetti gli errori e apporta cambiamenti sinceri', 'Crescere attraverso l’onestà e il coraggio.', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', 'Geben Sie Fehler zu und nehmen Sie ernsthafte Änderungen vor', 'Wachsen Sie durch Ehrlichkeit und Mut.', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', 'Nhân cách Chân thật: Trung thực nhận lỗi khi làm sai', 'Dũng cảm nói thật, nhận lỗi chân thành và sẵn sàng sửa đổi', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', '承认错误并真诚改变', '通过诚实和勇气成长。', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', '間違いを認め、誠実に変化を起こす', '正直さと勇気によって成長します。', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-03', '실수를 인정하고 진심으로 변화하라', '정직과 용기를 통해 성장하세요.', 'personality', '🛡️', 25, 'anytime', 0, true),
  ('WIT-PER-04', 'Coraggio di cambiare: lasciarsi alle spalle una cattiva abitudine', 'Impegnarsi a cambiare e diventare migliori.', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', 'Coraje para cambiar: dejar atrás un mal hábito', 'Comprométete a cambiar y ser mejor.', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', 'Courage de changement : abandonnez une mauvaise habitude', 'Engagez-vous à changer et à devenir meilleur.', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', 'Courage to change: Leave one poor habit behind', 'Commit to change and become better.', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', 'Mut zur Veränderung: Lassen Sie eine schlechte Angewohnheit hinter sich', 'Verpflichten Sie sich, sich zu verändern und besser zu werden.', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', 'Nhân cách Hy vọng & Niềm tin: Động viên bạn bè vượt khó', 'Truyền niềm tin và nói lời khích lệ khi thấy người khác gặp khó khăn', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', '勇于改变：改掉一个坏习惯', '致力于改变并变得更好。', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', '変える勇気: 悪い習慣を 1 つだけ残す', '変化し、より良くなることを約束します。', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PER-04', '변화하는 용기: 나쁜 습관 하나를 버리세요', '변화하고 더 나아지겠다고 다짐하세요.', 'personality', '🌟', 20, 'afternoon', 0, false),
  ('WIT-PHY-01', 'Brossez-vous les dents pendant deux minutes, matin et soir', 'Gardez les dents propres et fraîches.', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', 'Brush teeth for two minutes, morning and night', 'Keep teeth clean and fresh.', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', 'Cepillarse los dientes durante dos minutos, mañana y noche.', 'Mantenga los dientes limpios y frescos.', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', 'Lavarsi i denti per due minuti, mattina e sera', 'Mantieni i denti puliti e freschi.', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', 'Putzen Sie morgens und abends zwei Minuten lang die Zähne', 'Halten Sie die Zähne sauber und frisch.', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', 'Vận động thể thao / Thể dục buổi sáng 15 phút', 'Tập thể dục, hít thở không khí trong lành, tăng cường sức bền', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', '早晚刷牙两分钟', '保持牙齿清洁、新鲜。', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', '朝と夜、2分間歯を磨きましょう', '歯を清潔で新鮮に保ちます。', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-01', '아침 저녁으로 2분간 양치를 하세요.', '치아를 깨끗하고 신선하게 유지하세요.', 'physical', '🏃', 15, 'morning', 15, false),
  ('WIT-PHY-02', 'Acuéstate antes de las 21:30', 'Apoye el crecimiento saludable durmiendo lo suficiente.', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', 'Gehen Sie vor 21:30 Uhr zu Bett', 'Unterstützen Sie ein gesundes Wachstum mit ausreichend Schlaf.', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', 'Go to bed before 9:30 PM', 'Support healthy growth with enough sleep.', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', 'Se coucher avant 21h30', 'Favorisez une croissance saine avec suffisamment de sommeil.', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', 'Vai a letto prima delle 21:30', 'Supporta una crescita sana con un sonno sufficiente.', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', 'Đánh răng sáng & tối đúng 2 phút', 'Chăm sóc răng miệng sạch sẽ', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', '午後9時30分までに就寝してください', '十分な睡眠で健やかな成長をサポートします。', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', '晚上 9:30 之前上床睡觉', '通过充足的睡眠支持健康成长。', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-PHY-02', '오후 9시 30분 이전에 잠자리에 드세요', '충분한 수면으로 건강한 성장을 돕습니다.', 'physical', '🪥', 10, 'morning', 2, false),
  ('WIT-VIR-01', 'Amabilidad: Comparte algo delicioso.', 'Piensa en las necesidades de los demás.', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', 'Freundlichkeit: Teilen Sie etwas Leckeres', 'Denken Sie an die Bedürfnisse anderer.', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', 'Gentilezza: condividi qualcosa di delizioso', 'Pensa ai bisogni degli altri.', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', 'Gentillesse : partagez quelque chose de délicieux', 'Pensez aux besoins des autres.', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', 'Kindness: Share something delicious', 'Think about the needs of others.', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', 'Phẩm chất Nhân: Yêu thương & chia sẻ món ngon', 'Nuôi dưỡng lòng trắc ẩn, biết chia sẻ đồ ăn, đồ chơi với người khác', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', '優しさ：おいしいものをシェアする', '他の人のニーズについて考えてみましょう。', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', '善良：分享好吃的东西', '想想别人的需要。', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-01', '친절: 맛있는 것을 나눠주세요', '다른 사람들의 필요 사항에 대해 생각해 보십시오.', 'virtue', '❤️', 15, 'afternoon', 0, false),
  ('WIT-VIR-02', 'Phẩm chất Lễ: Lễ phép chào hỏi & cảm ơn, xin lỗi', 'Đi thưa về trình, khoanh tay chào người lớn và nói năng dạ vâng', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', 'Respect: Greet adults politely', 'Show good manners to adults.', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', 'Respect : Saluez poliment les adultes', 'Faites preuve de bonnes manières envers les adultes.', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', 'Respekt: Begrüßen Sie Erwachsene höflich', 'Zeigen Sie Erwachsenen gegenüber gute Manieren.', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', 'Respeto: Saludar cortésmente a los adultos.', 'Muestre buenos modales a los adultos.', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', 'Rispetto: saluta gli adulti educatamente', 'Mostra buone maniere agli adulti.', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', '尊重：有礼貌地向成年人打招呼', '对成年人表现出良好的举止。', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', '敬意：大人に対して礼儀正しく挨拶する', '大人に対してマナーを守ってください。', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-02', '공경: 어른들에게 공손하게 인사하기', '어른들에게 예의를 보여주세요.', 'virtue', '🙇', 15, 'morning', 0, false),
  ('WIT-VIR-03', 'Phẩm chất Nghĩa: Có trách nhiệm với việc được giao', 'Ý thức trách nhiệm hoàn thành nhiệm vụ và tri ân những điều nhận được', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', 'Responsabilidad: Completar el trabajo asignado.', 'Trabaja con cuidado y no dejes tareas sin terminar.', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', 'Responsabilità: portare a termine il lavoro assegnato', 'Lavora con attenzione e non lasciare i compiti incompiuti.', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', 'Responsabilité : Terminer le travail assigné', 'Travaillez avec soin et ne laissez pas les tâches inachevées.', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', 'Responsibility: Complete assigned work', 'Work carefully and do not leave tasks unfinished.', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', 'Verantwortung: Erledigung der zugewiesenen Arbeiten', 'Arbeiten Sie sorgfältig und lassen Sie keine Aufgaben unvollendet.', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', '职责：完成分配的工作', '认真工作，不要半途而废。', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', '責任: 割り当てられた仕事を完了する', '慎重に作業し、タスクを未完了のままにしないでください。', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-03', '책임: 할당된 작업을 완료합니다.', '주의 깊게 작업하고 작업을 완료하지 않은 상태로 두지 마십시오.', 'virtue', '⚖️', 20, 'evening', 0, false),
  ('WIT-VIR-04', 'Phẩm chất Trí: Đặt câu hỏi hay & tìm hiểu điều mới', 'Lắng nghe sáng suốt, tìm tòi nguyên lý hoạt động của thế giới xung quanh', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', 'Sabiduría: haga preguntas reflexivas y explore', 'Explora la ciencia con curiosidad y creatividad.', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', 'Sagesse : posez des questions réfléchies et explorez', 'Explorez la science avec curiosité et créativité.', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', 'Saggezza: fai domande ponderate ed esplora', 'Esplora la scienza con curiosità e creatività.', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', 'Weisheit: Stellen Sie nachdenkliche Fragen und erkunden Sie', 'Entdecken Sie die Wissenschaft mit Neugier und Kreativität.', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', 'Wisdom: Ask thoughtful questions and explore', 'Explore science with curiosity and creativity.', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', '智慧：提出深思熟虑的问题并探索', '带着好奇心和创造力探索科学。', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', '知恵: 思慮深い質問をして探索する', '好奇心と創造力を持って科学を探究しましょう。', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-04', '지혜: 사려 깊은 질문을 하고 탐색하세요', '호기심과 창의력으로 과학을 탐구해보세요.', 'virtue', '🧠', 20, 'afternoon', 15, false),
  ('WIT-VIR-05', 'Affidabilità: mantenere le promesse e essere puntuali', 'Costruisci fiducia attraverso piccole azioni quotidiane.', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', 'Confiabilidad: cumplir las promesas y ser puntual', 'Genera confianza a través de pequeñas acciones diarias.', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', 'Fiabilité : Tenez vos promesses et soyez ponctuel', 'Établissez la confiance grâce à de petites actions quotidiennes.', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', 'Phẩm chất Tín: Giữ đúng lời hứa & đúng giờ hẹn', 'Làm đúng những gì đã hứa với bố mẹ và bạn bè, luôn đúng giờ', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', 'Trustworthiness: Keep promises and be punctual', 'Build trust through small daily actions.', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', 'Vertrauenswürdigkeit: Halten Sie Versprechen und seien Sie pünktlich', 'Bauen Sie Vertrauen durch kleine tägliche Aktionen auf.', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', '信頼性: 約束を守り、時間を厳守します', '日々の小さな行動から信頼関係を築きましょう。', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', '守信：信守承诺、准时', '通过日常小行动建立信任。', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-VIR-05', '신뢰성: 약속을 지키고 시간 엄수', '일상의 작은 행동을 통해 신뢰를 쌓아보세요.', 'virtue', '⏳', 25, 'evening', 0, false),
  ('WIT-WIS-01', '15분 동안 풍성한 책을 읽어보세요', '이해의 폭을 넓혀주는 유용한 책을 읽어보세요.', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', 'Lee un libro enriquecedor durante 15 minutos.', 'Lea libros útiles que amplíen la comprensión.', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', 'Leggi un libro arricchente per 15 minuti', 'Leggi libri utili che ampliano la comprensione.', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', 'Lesen Sie 15 Minuten lang ein bereicherndes Buch', 'Lesen Sie nützliche Bücher, die das Verständnis erweitern.', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', 'Lire un livre enrichissant pendant 15 minutes', 'Lisez des livres utiles qui élargissent la compréhension.', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', 'Read an enriching book for 15 minutes', 'Read useful books that broaden understanding.', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', 'Sức học tập: Đọc sách nuôi dưỡng tâm hồn 15 phút', 'Đọc truyện tranh đạo đức, sách khoa học hoặc sách phát triển tư duy', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', '内容の濃い本を 15 分間読む', '理解を広げる有益な本を読んでください。', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-01', '阅读一本内容丰富的书 15 分钟', '阅读可以拓宽理解的有用书籍。', 'wisdom', '📚', 20, 'afternoon', 15, false),
  ('WIT-WIS-02', 'Bài học tâm đắc: Chia sẻ 1 điều ngộ ra trong ngày', 'Đúc kết bài học hay từ câu chuyện ở lớp, ở nhà hoặc sách vở', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', 'Completa i compiti in modo indipendente', 'Studia senza aspettare i promemoria.', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', 'Completar la tarea de forma independiente', 'Estudia sin esperar recordatorios.', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', 'Complete homework independently', 'Study without waiting for reminders.', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', 'Faire ses devoirs de manière autonome', 'Étudiez sans attendre les rappels.', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', 'Hausaufgaben selbständig erledigen', 'Lernen Sie, ohne auf Erinnerungen zu warten.', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', '独立完成作业', '无需等待提醒即可学习。', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', '自主的に宿題を終わらせる', 'リマインダーを待たずに勉強しましょう。', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-02', '숙제를 독립적으로 완료', '알림을 기다리지 않고 공부하세요.', 'wisdom', '💡', 20, 'evening', 0, false),
  ('WIT-WIS-03', 'Chủ động hoàn thành bài tập về nhà không cần nhắc', 'Tự giác ngồi vào bàn học tập trung và hoàn thành nhiệm vụ', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', 'Comparta una lección significativa del día', 'Reflexiona sobre una lección y cuéntasela a tus padres.', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', 'Condividi una lezione significativa della giornata', 'Rifletti su una lezione e raccontala ai tuoi genitori.', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', 'Partagez une leçon significative de la journée', 'Réfléchissez à une leçon et racontez-la à vos parents.', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', 'Share one meaningful lesson from the day', 'Reflect on a lesson and tell it to your parents.', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', 'Teilen Sie eine bedeutungsvolle Lektion des Tages', 'Denken Sie über eine Lektion nach und erzählen Sie sie Ihren Eltern.', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', 'その日の有意義な教訓を 1 つ共有する', '授業を振り返って保護者に伝えてください。', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', '分享当天有意义的一课', '反思教训并将其告诉你的父母。', 'wisdom', '✍️', 25, 'afternoon', 30, true),
  ('WIT-WIS-03', '그날의 의미 있는 교훈 하나를 공유하세요', '수업 내용을 곰곰이 생각해보고 부모님께 말씀드리세요.', 'wisdom', '✍️', 25, 'afternoon', 30, true)
)
update public.habit_activities as activity
set legacy_template_id = catalog.legacy_template_id
from catalog
where activity.legacy_template_id is null
  and activity.framework_habit_id is null
  and activity.journey_habit_key is null
  and activity.child_id is null
  and activity.is_active = true
  and activity.is_parent_role = false
  and activity.target_age_stage = 'all'
  and activity.portrait16_key is null
  and activity.bo_thi7_key is null
  and activity.title = catalog.title
  and activity.description = catalog.description
  and (activity.instructions is null or activity.instructions = catalog.description)
  and activity.category = catalog.category
  and activity.icon = catalog.icon
  and activity.points = catalog.points
  and activity.time_of_day = catalog.time_of_day
  and activity.duration_minutes = catalog.duration_minutes
  and activity.requires_approval = catalog.requires_approval
  and activity.recurrence_type = 'daily'
  and to_jsonb(activity.recurrence_days) = '[0,1,2,3,4,5,6]'::jsonb;

commit;
